// Batch B: Buch 75 (4. Esra) Kapitel 5–8
const fs = require('fs');

const ch5 = [
'Gleichwohl was die Zeichen betrifft: Sieh, die Tage werden kommen, daß die auf Erden wohnen in einer großen Zahl weggenommen werden, und der Weg der Wahrheit verborgen wird, und das Land des Glaubens beraubt wird.',
'Aber die Ungerechtigkeit wird mehr zunehmen als das, was du jetzt siehst, oder was du vor langer Zeit gehört hast.',
'Und das Land, das du jetzt Wurzel fassen siehst, wirst du plötzlich wüste sehen.',
'Wenn aber der Allerhöchste dir das Leben läßt, wirst du nach der dritten Posaune sehen, daß die Sonne plötzlich in der Nacht aufleuchtet und der Mond dreimal am Tage.',
'Und Blut wird aus Holz tropfen, und der Stein wird seine Stimme geben, und die Völker werden erschüttert werden:',
'und er soll herrschen, auf den die auf Erden Wohnenden nicht warten; und die Vögel werden ihre Flüge zusammen nehmen.',
'Und das Sodomitische Meer soll Fische herauswerfen und bei Nacht ein Geräusch machen, das viele nicht kannten; aber alle werden seine Stimme hören.',
'Es wird auch Verwirrung an vielen Orten geben, und das Feuer wird oft wieder ausgesandt werden, und die wilden Tiere werden ihre Plätze wechseln, und menstruierende Frauen werden Mißgeburten gebären.',
'Und das Salzwasser wird im Süßwasser gefunden werden, und alle Freunde werden einander zerstören; dann wird der Witz sich verstecken und der Verstand sich in sein geheimes Gemach zurückziehen,',
'und soll von vielen gesucht und doch nicht gefunden werden; dann werden Ungerechtigkeit und Zügellosigkeit auf Erden vervielfältigt.',
'Ein Land wird das andere fragen und sagen: Ist die Gerechtigkeit, die einen Mann gerecht macht, durch dich gegangen? Und es wird sagen: Nein.',
'Zu derselben Zeit werden Menschen hoffen, aber nichts erlangen; sie werden sich mühen, aber ihre Wege werden nicht gedeihen.',
'Um dir solche Zeichen zu zeigen, habe ich Erlaubnis; und wenn du wieder beten und weinen und sieben Tage lang fasten willst, wirst du noch größere Dinge hören.',
'Da erwachte ich, und ein außerordentliches Entsetzen fuhr durch meinen ganzen Leib; und mein Gemüt war beunruhigt, so daß es in Ohnmacht fiel.',
'So hielt mich der Engel, der gekommen war, mit mir zu reden, fest, tröstete mich und stellte mich auf meine Füße.',
'Und in der zweiten Nacht geschah es, daß Salathiel, der Hauptmann des Volkes, zu mir kam und sprach: Wo bist du gewesen? und warum ist dein Angesicht so traurig?',
'Weißt du nicht, daß Israel in der Gefangenschaft dir anvertraut ist?',
'Steh auf und iß Brot und verlaß uns nicht, wie ein Hirte, der seine Herde in die Hände grausamer Wölfe gibt.',
'Da sprach ich zu ihm: Geh weg von mir und komm mir nicht nahe. Und er hörte, was ich sagte, und ging von mir weg.',
'Und so fastete ich sieben Tage lang, trauernd und weinend, wie mir Uriel, der Engel, befohlen hatte.',
'Und nach sieben Tagen geschah es, daß die Gedanken meines Herzens abermals sehr schwer waren für mich,',
'und meine Seele empfing den Geist des Verstandes wieder, und ich begann abermals mit dem Allerhöchsten zu reden,',
'und sprach: O Herr, der du herrschest, von allem Holz der Erde und von allen Bäumen derselben hast du dir einen einzigen Weinstock erwählt:',
'und von allen Ländern der ganzen Welt hast du dir eine einzige Grube erwählt: und von allen Blumen derselben eine einzige Lilie:',
'und von allen Tiefen des Meeres hast du dir einen einzigen Strom gefüllt: und von allen gebauten Städten hast du Zion dir selbst geheiligt:',
'und von allen Vögeln, die erschaffen sind, hast du dir eine einzige Taube genannt: und von allem Vieh, das gemacht ist, hast du dir ein einziges Schaf bereitet:',
'und unter aller Menge der Völker hast du dir ein einziges Volk erworben: und diesem Volk, das du liebst, hast du ein Gesetz gegeben, das von allen gebilligt wird.',
'Und nun, o Herr, warum hast du dieses eine Volk den vielen preisgegeben? und auf die eine Wurzel hast du andere bereitet, und warum hast du dein einziges Volk unter viele zerstreut?',
'Und die, welche deinen Verheißungen widersprochen und deinen Bündnissen nicht geglaubt haben, haben sie zertreten.',
'Wenn du dein Volk so sehr gehaßt hättest, solltest du es doch mit deiner eigenen Hand gestraft haben.',
'Da nun diese meine Worte gesprochen waren, wurde der Engel, der in der vorigen Nacht zu mir gekommen war, zu mir gesandt',
'und sprach zu mir: Höre mich an und ich werde dich unterweisen; achte auf das, was ich sage, und ich werde dir noch mehr sagen.',
'Da sprach ich: Rede, mein Herr. Da sagte er zu mir: Du bist sehr beunruhigt um Israels willen: liebst du dieses Volk mehr als der, der es gemacht hat?',
'Und ich sprach: Nein, Herr; aber aus lauter Kummer habe ich geredet; denn meine Nieren schmerzen mich jede Stunde, während ich mich bemühe, den Weg des Allerhöchsten zu begreifen und einen Teil seines Urteils zu erkunden.',
'Er aber sprach zu mir: Du kannst nicht. Da sprach ich: Warum, Herr? wozu bin ich denn geboren? oder warum war nicht der Leib meiner Mutter mein Grab, damit ich die Mühsal Jakobs und das beschwerliche Getöse des Geschlechts Israels nicht sehen müßte?',
'Er aber sprach zu mir: Zähle mir die Dinge, die noch nicht gekommen sind; versammle mir die zerstreuten Abfälle; laß die verwelkten Blumen wieder grün werden;',
'öffne mir die geschlossenen Räume und bringe mir die darin verschlossenen Winde heraus; zeige mir das Bild einer Stimme: und dann werde ich dir die Sache erklären, um die du dich mühst zu wissen.',
'Da sprach ich: O Herr, der du herrschest, wer kann diese Dinge kennen außer dem, der nicht bei den Menschen wohnt?',
'Was mich betrifft, so bin ich unverständig: wie kann ich dann über diese Dinge reden, nach denen du mich fragst?',
'Da sprach er zu mir: Wie du keine dieser Dinge tun kannst, die ich genannt habe, so kannst du auch nicht mein Gericht finden, noch zuletzt die Liebe, die ich meinem Volk verheißen habe.',
'Da sprach ich: Sieh, o Herr, und doch bist du nahe bei denen, die aufbewahrt sind bis ans Ende: was sollen denn jene tun, die vor mir waren, oder wir, die jetzt sind, oder die nach uns kommen werden?',
'Er antwortete mir und sprach: Ich will mein Gericht einem Ring vergleichen: wie am letzten keine Trägheit ist, so ist am ersten keine Eile.',
'Da antwortete ich und sprach: Konntest du nicht jene, die gemacht sind und sind und sein werden, auf einmal machen, damit du dein Gericht desto eher zeigen könntest?',
'Da antwortete er mir und sprach: Die Schöpfung kann nicht den Schöpfer übereilen; auch kann die Welt nicht alle die auf einmal tragen, die in ihr erschaffen werden sollen.',
'Und ich sprach: Wie du zu deinem Knecht gesagt hast, daß du, der du allem das Leben gibst, der Schöpfung, die du erschaffen hast, das Leben auf einmal gegeben hast, und die Schöpfung es trug: so könnte sie auch jetzt alle die auf einmal tragen, die jetzt vorhanden sind.',
'Da sprach er zu mir: Frage den Leib einer Frau und sag ihr: Wenn du Kinder gebärst, warum tust du es nicht auf einmal, sondern eines nach dem anderen? Bitte sie daher, zehn Kinder auf einmal zu gebären.',
'Da sprach ich: Sie kann das nicht; sie muß es in zeitlichen Abständen tun.',
'Da sprach er zu mir: Ebenso habe ich dem Schoß der Erde denen gegeben, die in ihr gesät sind, zu ihren Zeiten.',
'Denn wie ein junges Kind nicht die Dinge für das Alter hervorbringen kann, so habe ich die Welt, die ich erschaffen habe, geordnet.',
'Und ich fragte und sprach: Weil du mir nun den Weg gezeigt hast, will ich vor dir weiterreden; denn unsere Mutter, von der du mir gesagt hast, daß sie jung ist, nähert sich jetzt dem Alter.',
'Er antwortete mir und sprach: Frage eine Frau, die Kinder gebiert, und sie wird es dir sagen.',
'Sage ihr: Warum sind die, die du neulich geboren hast, nicht wie jene, die vor ihnen waren, sondern kleiner von Gestalt?',
'Und sie wird dir antworten: Die in der Kraft der Jugend Geborenen sind von einer Gestalt, und die in der Zeit des Alters Geborenen, wenn der Leib sich erschöpft, sind anders geartet.',
'Betrachte nun auch du, daß ihr kleiner von Gestalt seid als die, die vor euch waren.',
'Und so sind auch die nach euch Kommenden kleiner als ihr, wie die Schöpfung, die jetzt anfängt zu altern, und die Stärke der Jugend hinter sich gelassen hat.',
'Da sprach ich: Herr, ich bitte dich, wenn ich Gnade vor deinen Augen gefunden habe, zeige deinem Knecht, durch wen du deine Schöpfung heimsuchen wirst.'
];

const ch6 = [
'Er aber sprach zu mir: Im Anfang, als die Erde gemacht wurde, ehe die Grenzen der Welt standen, oder je die Winde wehten,',
'ehe es donnerte und blitzte, oder je die Grundlagen des Paradieses gelegt wurden,',
'ehe die schönen Blumen gesehen wurden, oder je die beweglichen Kräfte eingesetzt wurden, ehe die unzählige Schar der Engel versammelt war,',
'oder je die Höhen der Luft aufgehoben wurden, ehe die Maße des Firmaments benannt wurden, oder je die Schornsteine in Zion heiß wurden,',
'und ehe die gegenwärtigen Jahre gesucht wurden, oder je die Erfindungen derer, die jetzt sündigen, sich umgewandt hatten, ehe sie versiegelt wurden, die den Glauben als Schatz gesammelt haben:',
'da erwog ich diese Dinge, und sie alle wurden durch mich allein gemacht, und durch sonst niemanden: durch mich sollen sie auch enden, und durch sonst niemanden.',
'Da antwortete ich und sprach: Was soll die Teilung der Zeiten sein? oder wann ist das Ende des Ersten und der Anfang des Folgenden?',
'Er antwortete mir und sprach: Von Abraham bis Isaak, als von ihm Jakob und Esau geboren wurden, war Jakobs Hand zuerst an der Ferse Esaus.',
'Denn Esau ist das Ende dieser Welt, und Jakob der Anfang des Folgenden.',
'Die Hand des Menschen ist zwischen der Ferse und der Hand: andere Frage, Esra, stelle nicht.',
'Da antwortete ich und sprach: O Herr, der du herrschest, wenn ich Gnade vor deinen Augen gefunden habe,',
'so bitte ich dich, zeige deinem Knecht das Ende deiner Zeichen, die du mir in der vorigen Nacht zum Teil gezeigt hast.',
'Er antwortete mir und sprach: Stehe auf auf deine Füße und höre eine mächtige tönende Stimme.',
'Und es soll sein wie ein großes Bewegen; aber der Ort, wo du stehst, soll nicht bewegt werden.',
'Und darum, wenn es redet, fürchte dich nicht; denn das Wort ist vom Ende, und die Grundlagen der Erde werden verstanden.',
'Und warum? weil die Rede dieser Dinge bebt und bewegt wird; denn sie weiß, daß das Ende dieser Dinge verändert werden muß.',
'Und es begab sich, als ich es gehört hatte, daß ich auf meine Füße stand und horchte; und sieh, da war eine Stimme, die redete, und ihr Klang war wie der Klang vieler Wasser.',
'Und sie sprach: Sieh, die Tage kommen, daß ich anfangen werde, mich zu nähern und die zu besuchen, die auf Erden wohnen,',
'und werde anfangen, Rechenschaft von ihnen zu fordern, was sie sind, die ungerechterweise mit ihrer Ungerechtigkeit geschädigt haben, und wenn die Bedrängnis Zions erfüllt sein wird;',
'und wenn die Welt, die anfangen wird zu verschwinden, vollendet sein wird, dann will ich diese Zeichen zeigen: die Bücher sollen vor dem Firmament geöffnet werden, und sie werden alle zusammen sehen:',
'und die Kinder eines Jahres werden mit ihren Stimmen reden; die Schwangeren werden unreife Kinder von drei oder vier Monaten gebären, und sie werden leben und auferstehen.',
'Und plötzlich sollen die bestellten Felder unbestellt erscheinen, die vollen Scheunen sollen plötzlich leer gefunden werden.',
'Und die Posaune soll einen Ton geben, den wenn jeder Mensch hört, sie sich plötzlich erschrecken werden.',
'Zu jener Zeit werden Freunde wie Feinde gegeneinander kämpfen, und die Erde wird mit denen, die darin wohnen, in Angst stehen, die Quellen der Brunnen werden stillstehen und in drei Stunden nicht fließen.',
'Wer von all diesen Dingen, die ich dir gesagt habe, übrig bleibt, soll entrinnen und mein Heil sehen und das Ende eurer Welt.',
'Und die Menschen, die aufgenommen werden, sollen es sehen, die den Tod von ihrer Geburt an nicht geschmeckt haben: und das Herz der Einwohner soll geändert und in einen anderen Sinn verwandelt werden.',
'Denn das Böse soll ausgerottet, der Betrug getilgt werden.',
'Was den Glauben betrifft, er wird blühen; die Verderbnis wird überwunden werden; und die Wahrheit, die so lange ohne Frucht war, wird offenbart werden.',
'Und als er mit mir redete, sieh, da schaute ich nach und nach auf ihn, vor dem ich stand.',
'Und diese Worte sprach er zu mir: Ich bin gekommen, dir die Nacht der Zeit zu zeigen, die kommt.',
'Wenn du noch weiter beten und sieben Tage lang fasten wirst, werde ich dir am Tage noch Größeres sagen als ich in jener Nacht gehört habe.',
'Denn deine Stimme wird vor dem Allerhöchsten erhört; denn der Mächtige hat dein gerechtes Verhalten gesehen, er hat auch deine Keuschheit gesehen, die du seit deiner Jugend gehabt hast.',
'Und darum hat er mich gesandt, dir alle diese Dinge zu zeigen und dir zu sagen: Sei getrost und fürchte dich nicht.',
'Und haste nicht mit der vergangenen Zeit, eitle Dinge zu bedenken, damit du nicht von der letzten Zeit eilst.',
'Und es begab sich nach diesem, daß ich abermals weinte und sieben Tage lang fastete, wie er mir sagte, damit ich die drei Wochen erfüllte, die er mir sagte.',
'Und in der achten Nacht wurde mein Herz abermals in mir beunruhigt, und ich begann vor dem Allerhöchsten zu reden.',
'Denn mein Geist war sehr entflammt, und meine Seele war in Nöten.',
'Und ich sprach: O Herr, du hast vom Anfang der Schöpfung geredet, am ersten Tage, und hast also gesprochen: Es werde Himmel und Erde; und dein Wort war ein vollkommenes Werk.',
'Und dann war der Geist, und Finsternis und Stille waren auf allen Seiten; der Klang der menschlichen Stimme war noch nicht geformt.',
'Da befahlst du, daß ein schönes Licht aus deinen Schätzen hervorleuchten sollte, damit dein Werk erschiene.',
'Am zweiten Tag machtest du den Geist des Firmaments und befahlst ihm, sich zu teilen und eine Scheidung zwischen den Wassern zu machen, damit der eine Teil hinaufsteige und der andere unten bleibe.',
'Am dritten Tag befahlst du, daß die Wasser auf dem siebten Teil der Erde versammelt werden sollten; sechs Teile hast du getrocknet und aufbewahrt, damit von diesen einige, von Gott gepflanzt und bestellt, dir dienten.',
'Denn sobald dein Wort hervorging, war das Werk gemacht.',
'Denn sogleich entstanden große und unzählige Früchte und vielerlei angenehme Dinge für den Geschmack und Blumen von unveränderlicher Farbe und Düfte von wunderbarem Geruch: und dies geschah am dritten Tag.',
'Am vierten Tag befahlst du, daß die Sonne leuchten und der Mond ihr Licht geben und die Sterne in Ordnung sein sollten:',
'und gabst ihnen den Auftrag, dem Menschen zu dienen, der erschaffen werden sollte.',
'Am fünften Tag sprachst du zum siebten Teil, wo die Wasser versammelt waren, daß er lebendige Wesen, Vögel und Fische hervorbringen sollte: und so geschah es.',
'Denn das stumme und leblose Wasser brachte auf Gottes Befehl lebendige Wesen hervor, damit alle Völker deine wunderbaren Werke loben sollten.',
'Da ordnetest du zwei lebendige Wesen; das eine nanntest du Enoch und das andere Leviathan;',
'und schiedest das eine vom anderen: denn der siebte Teil, nämlich wo das Wasser versammelt war, konnte sie beide nicht halten.',
'Dem Enoch gabst du einen Teil, der am dritten Tag trocken gelegt wurde, damit er in eben dem Teil wohnen sollte, darin tausend Berge sind:',
'dem Leviathan aber gabst du den siebten Teil, nämlich das Feuchte; und hast ihn aufbewahrt, daß er von dem gefressen werde, dem du willst, und wann.',
'Am sechsten Tag gabst du der Erde den Befehl, vor dir Tiere, Vieh und kriechende Tiere hervorzubringen:',
'und danach auch Adam, den du zum Herrn aller deiner Schöpfung gesetzt hast: von ihm kommen wir alle, und das Volk, das du erwählt hast.',
'Dies alles habe ich vor dir gesprochen, o Herr, weil du die Welt um unsertwillen gemacht hast.',
'Was aber das andere Volk betrifft, das auch von Adam kommt, hast du gesagt, daß es nichts ist, und gleich dem Speichel ist; und den Überfluß desselben hast du einem Tropfen verglichen, der aus einem Gefäß fällt.',
'Und nun, o Herr, siehe, diese Heiden, die immer als nichts angesehen worden sind, haben angefangen, über uns zu herrschen und uns zu verzehren.',
'Wir aber, dein Volk, das du deinen Erstgeborenen, deinen Eingeborenen und deinen eifrigen Liebhaber nanntest, sind in ihre Hände gegeben.',
'Wenn nun die Welt um unsertwillen gemacht ist, warum besitzen wir kein Erbteil mit der Welt? wie lange soll dies dauern?'
];

const ch7 = [
'Und als ich diese Worte gesprochen hatte, wurde zu mir der Engel gesandt, der mir in den vorigen Nächten gesandt worden war.',
'Er sprach zu mir: Stehe auf, Esra, und höre die Worte, die ich dir sagen komme.',
'Ich sprach: Rede, mein Gott. Da sprach er zu mir: Das Meer ist in einem weiten Raum gesetzt, damit es tief und groß sein kann.',
'Aber wenn der Eingang schmal wäre und wie ein Fluß;',
'wer könnte dann ins Meer gehen, um es zu besehen und es zu regieren? Wenn er nicht durch den Engen ginge, wie käme er in das Weite?',
'Es gibt noch ein anderes Ding: Eine Stadt ist gebaut und auf einem breiten Feld gestellt, und voll aller guten Dinge:',
'der Eingang derselben ist eng und an einem gefährlichen Ort gelegen, wie wenn rechts Feuer wäre und links tiefes Wasser:',
'und nur ein einziger Pfad zwischen ihnen beiden, zwischen dem Feuer und dem Wasser, so schmal, daß dort nur ein Mensch auf einmal gehen kann.',
'Wenn nun diese Stadt einem Menschen als Erbe gegeben würde, wenn er die Gefahr, die vor ihr liegt, nie überwinden wird, wie soll er dieses Erbe empfangen?',
'Ich sprach: So ist es, Herr. Da sagte er zu mir: Ebenso ist Israels Teil.',
'Denn um ihretwillen habe ich die Welt gemacht: und als Adam meine Satzungen übertrat, wurde das beschlossen, was nun getan ist.',
'Da wurden die Eingänge dieser Welt eng gemacht, voll von Schmerz und Mühsal; sie sind wenige und böse, voller Gefahren und sehr mühsam.',
'Denn die Eingänge der älteren Welt waren weit und sicher und brachten unsterbliche Frucht.',
'Wenn also jene, die jetzt leben, sich nicht mühen, in diese engen und nichtigen Dinge einzutreten, können sie nie das empfangen, was ihnen bereitet ist.',
'Warum also beunruhigst du dich, da du doch nur ein vergänglicher Mensch bist? und warum bewegt dich das, da du doch sterblich bist?',
'Warum hast du nicht das, was kommen soll, in deinem Sinn erwogen, mehr als das, was gegenwärtig ist?',
'Da antwortete ich und sprach: O Herr, der du herrschest, du hast in deinem Gesetz verordnet, daß die Gerechten diese Dinge erben sollen, die Gottlosen aber umkommen sollen.',
'Gleichwohl sollen die Gerechten enge Dinge leiden und weite erhoffen; denn die Gottlosen haben enge Dinge gelitten und werden die Weiten nicht sehen.',
'Da sprach er zu mir: Es ist kein Richter über Gott, noch keiner mit Einsicht über den Allerhöchsten.',
'Denn viele kommen in diesem Leben um, weil sie das Gesetz Gottes, das ihnen gesetzt ist, verachten.',
'Denn Gott hat denen, die kamen, ein strenges Gebot gegeben, was sie tun sollen, um zu leben, wie sie kamen, und was sie beobachten sollen, um Strafe zu vermeiden.',
'Gleichwohl waren sie ihm nicht gehorsam, sondern redeten wider ihn und bildeten sich eitle Dinge ein;',
'und betrogen sich selbst durch ihre gottlosen Werke; und sagten vom Allerhöchsten, daß er nicht sei; und erkannten seine Wege nicht:',
'aber sein Gesetz haben sie verachtet und seinen Bund verleugnet; seinen Satzungen waren sie nicht treu und haben seine Werke nicht getan.',
'Und darum, Esra: Für die Leeren sind die leeren Dinge, und für die Vollen sind die vollen Dinge.',
'Sieh, die Zeit soll kommen, da diese Zeichen, die ich dir gesagt habe, eintreten werden, und die Braut soll erscheinen, und die kommend erscheinende soll gesehen werden, die jetzt von der Erde verborgen wird.',
'Und wer von den vorgenannten Übeln erlöst wird, der soll meine Wunder sehen.',
'Denn mein Sohn Jesus soll offenbart werden mit denen, die bei ihm sind, und die übrig bleiben, sollen vierhundert Jahre in Wonne sein.',
'Nach diesen Jahren soll mein Sohn Christus sterben und alle Menschen, die Leben haben.',
'Und die Welt soll sieben Tage lang in die alte Stille zurückkehren, wie in den früheren Gerichten: so daß kein Mensch übrig bleibt.',
'Und nach sieben Tagen soll die Welt, die noch nicht aufgewacht ist, auferweckt werden, und das Verderbliche soll sterben.',
'Und die Erde soll die wiedergeben, die in ihr schlafen, und so der Staub die darin still Wohnenden, und die verborgenen Orte sollen die Seelen abliefern, die ihnen anvertraut waren.',
'Und der Allerhöchste soll auf dem Richterstuhl erscheinen, und das Elend soll vergehen, und die Langmut soll ein Ende haben:',
'aber das Gericht allein soll bleiben, die Wahrheit soll bestehen und der Glaube erstarken:',
'und das Werk soll folgen, und die Belohnung soll gezeigt werden, die guten Werke sollen gelten, und die bösen Werke sollen keine Herrschaft haben.',
'Da sprach ich: Abraham hat zuerst für die Sodomiter gebeten, und Mose für die Väter, die in der Wüste sündigten:',
'und Jesus danach für Israel zur Zeit Achans;',
'und Samuel und David für die Vertilgung; und Salomo für die, die ins Heiligtum kommen sollten:',
'und Elias für die, die Regen empfingen; und für den Toten, damit er leben möge:',
'und Ezechias für das Volk zur Zeit Sanheribs; und viele für viele.',
'Wenn nun die Verderbnis zugenommen hat und die Gottlosigkeit gewachsen ist, und die Gerechten für die Gottlosen gebetet haben: warum sollte es jetzt nicht auch so sein?',
'Er antwortete mir und sprach: Dieses gegenwärtige Leben ist nicht das Ende, in dem die große Herrlichkeit bleibt; darum haben sie für die Schwachen gebetet.',
'Aber der Tag des Gerichts soll das Ende dieser Zeit und der Anfang der zukünftigen Unsterblichkeit sein, da die Verderbnis vergangen,',
'Zügellosigkeit ein Ende hat, der Unglaube abgeschnitten ist, die Gerechtigkeit gewachsen und die Wahrheit aufgegangen ist.',
'Da kann kein Mensch den retten, der vernichtet ist, noch den unterdrücken, der den Sieg errungen hat.',
'Ich antwortete dann und sprach: Dies ist mein erstes und letztes Wort, daß es besser gewesen wäre, der Erde Adam nicht zu geben: oder als sie ihm gegeben war, ihn am Sündigen zu hindern.',
'Denn was nützt es den Menschen, jetzt in diesem Leben in Schwermut zu leben und nach dem Tod Strafe zu erwarten?',
'O du Adam, was hast du getan? Denn wenn du auch der Sünder warst, so bist du nicht allein gefallen, sondern wir alle, die von dir kommen.',
'Denn was nützt es uns, daß uns eine unsterbliche Zeit verheißen ist, da wir die Werke getan haben, die den Tod bringen?',
'Und daß uns eine ewige Hoffnung verheißen ist, da wir selbst, die wir sehr gottlos sind, eitel geworden sind?',
'Und daß für uns Wohnstätten der Gesundheit und Sicherheit aufbewahrt sind, da wir gottlos gelebt haben?',
'Und daß die Herrlichkeit des Allerhöchsten aufbewahrt ist, die zu schützen, die ein vorsichtiges Leben geführt haben, da wir in den gottlosesten Wegen aller gewandelt sind?',
'Und daß ein Paradies gezeigt werden soll, dessen Frucht in Ewigkeit dauert, worin Sicherheit und Heilmittel ist, da wir nicht eintreten dürfen?',
'(Denn wir sind in unangenehmen Orten gewandelt.)',
'Und daß die Angesichter derer, die Enthaltsamkeit geübt haben, heller als die Sterne leuchten sollen, da unsere Angesichter schwärzer als Dunkelheit sein werden?',
'Denn während wir lebten und Ungerechtigkeit begingen, bedachten wir nicht, daß wir dafür nach dem Tod leiden sollten.',
'Da antwortete er mir und sprach: Dies ist die Bedingung des Kampfes, den jeder Mensch, der auf Erden geboren ist, kämpfen muß;',
'daß wenn er überwunden wird, er das leiden soll, was du gesagt hast: wenn er aber den Sieg erringt, soll er das empfangen, was ich sage.',
'Denn das ist das Leben, wovon Mose zum Volk redete, als er lebte, und sprach: Erwähle das Leben, damit du lebest.',
'Gleichwohl glaubten sie ihm nicht, noch den Propheten nach ihm, noch mir, der ich zu ihnen geredet habe,',
'daß nicht so große Traurigkeit in ihrer Vernichtung sein sollte, wie Freude über die sein soll, die zur Seligkeit überredet werden.',
'Ich antwortete dann und sprach: Ich weiß, Herr, daß der Allerhöchste barmherzig genannt wird, indem er Erbarmen hat mit denen, die noch nicht in die Welt gekommen sind,',
'und auch mit denen, die sich zu seinem Gesetz bekehren;',
'und daß er geduldig ist und diejenigen, die gegen ihn gesündigt haben, als seine Geschöpfe, lange erträgt;',
'und daß er gütig ist, denn er ist bereit zu geben, wo es nötig ist;',
'und daß er von großem Erbarmen ist, denn er vervielfältigt mehr und mehr Erbarmungen denen, die gegenwärtig sind, die vergangen sind und auch denen, die kommen werden.',
'Denn wenn er seine Erbarmungen nicht vervielfältigte, würde die Welt mit denen, die in ihr erben, nicht bestehen.',
'Und er vergibt; denn wenn er es nicht täte, aus seiner Güte, damit die, welche Ungerechtigkeit begangen haben, ihrer erleichtert würden, der zehnte Teil der Menschen würde nicht am Leben bleiben.',
'Und wenn er als Richter die nicht begnadigte, die durch sein Wort geheilt werden, und die Menge der Streitereien nicht ausrottete,',
'würden vielleicht sehr wenige in einer unzähligen Menge übrig bleiben.'
];

const ch8 = [
'Er antwortete mir und sprach: Der Allerhöchste hat diese Welt für viele gemacht, die zukünftige Welt aber für wenige.',
'Ich will dir ein Gleichnis sagen, Esra: Wie wenn du die Erde fragst, so wird sie dir sagen, daß sie viel Ton gibt, woraus Tonwaren gemacht werden, aber wenig Staub, woraus Gold kommt: so ist auch der Lauf dieser gegenwärtigen Welt.',
'Es werden viele erschaffen, aber wenige werden gerettet werden.',
'So antwortete ich und sprach: Schlinge dann, o meine Seele, Einsicht hinunter und verschlinge Weisheit.',
'Denn du hast zugestimmt zuzuhören, und bist willens zu weissagen; denn du hast keinen längeren Raum als nur zu leben.',
'O Herr, wenn du deinem Knecht es nicht gestattest, daß wir vor dir beten, und du gibst uns Samen in unser Herz und Bestellung unseres Verstandes, damit eine Frucht daraus entstehe; wie soll jeder verderbte Mensch leben, der den Platz eines Menschen einnimmt?',
'Denn du allein bist, und wir alle sind ein Werk deiner Hände, wie du gesagt hast.',
'Denn wenn der Leib jetzt im Leib der Mutter geformt wird und du ihm Glieder gibst, wird deine Schöpfung in Feuer und Wasser bewahrt; und neun Monate erträgt dein Werk die Schöpfung, die in ihr erschaffen wird.',
'Aber das, was sie bewahrt und bewahrt wird, soll beide erhalten werden; und wenn die Zeit kommt, liefert der bewahrte Leib die Dinge ab, die in ihm gewachsen sind.',
'Denn du hast befohlen, daß aus den Teilen des Leibes, das heißt aus den Brüsten, Milch gegeben werde, die die Frucht der Brüste ist,',
'damit die geformte Sache eine Zeitlang genährt werde, bis du sie deiner Barmherzigkeit zuordnest.',
'Du hast sie mit deiner Gerechtigkeit aufgezogen und mit deinem Gesetz erzogen und mit deinem Gericht reformiert.',
'Und du wirst sie als deine Schöpfung sterben lassen und als dein Werk beleben.',
'Wenn du also ihn vernichten wolltest, der mit so großer Mühe geformt wurde, ist es eine leichte Sache, auf dein Gebot hin so anzuordnen, daß das Gemachte bewahrt werden soll.',
'Nun, Herr, werde ich reden; über die Menschen im allgemeinen weißt du am besten; über dein Volk aber, um dessen willen ich betrübt bin,',
'und wegen deines Erbes, um dessen willen ich trauere; und wegen Israels, um das ich schwer bin; und wegen Jakobs, um dessen willen ich bekümmert bin:',
'darum werde ich beginnen, vor dir für mich und für sie zu beten: denn ich sehe die Fälle von uns, die im Lande wohnen.',
'Aber ich habe die Schnelligkeit des Richters gehört, der kommen soll.',
'Darum höre meine Stimme und verstehe meine Worte, und ich werde vor dir reden. Dies ist der Anfang der Worte Esras, bevor er hinaufgenommen wurde; und ich sagte:',
'O Herr, der du in der Ewigkeit wohnst, der du von oben auf die Dinge im Himmel und in der Luft schaust:',
'dessen Thron unschätzbar ist; dessen Herrlichkeit nicht begriffen werden kann; vor dem die Heerscharen der Engel mit Zittern stehen,',
'dessen Dienst im Wind und Feuer ist; dessen Wort wahr und dessen Aussagen beständig sind; dessen Gebot stark und dessen Ordnung furchtbar ist;',
'dessen Blick die Tiefen austrocknet und dessen Zorn die Berge zum Schmelzen bringt; was die Wahrheit bezeugt:',
'O erhöre das Gebet deines Knechts und achte auf die Bitte deiner Schöpfung.',
'Denn solange ich lebe, werde ich reden, und solange ich Verstand habe, werde ich antworten.',
'O sieh nicht auf die Sünden deines Volkes; sieh auf die, die dir in Wahrheit dienen.',
'Beachte nicht die gottlosen Erfindungen der Heiden, sondern das Verlangen derer, die deine Zeugnisse in Bedrängnissen bewahren.',
'Denke nicht an die, die vor dir unaufrichtig gewandelt sind: aber erinnere dich an die, die nach deinem Willen deine Furcht erkannt haben.',
'Es sei nicht dein Wille, die zu vernichten, die wie Tiere gelebt haben; sondern sieh auf die, die dein Gesetz deutlich gelehrt haben.',
'Bringe keinen Unmut über die, die schlimmer als Tiere geachtet werden; sondern liebe die, die immer auf deine Gerechtigkeit und Herrlichkeit vertrauen.',
'Denn wir und unsere Väter leiden an solchen Krankheiten: aber um unsertwillen, der Sünder, wirst du barmherzig genannt werden.',
'Denn wenn du willst, Erbarmen über uns zu haben, wirst du barmherzig genannt werden, zu uns nämlich, die keine Werke der Gerechtigkeit haben.',
'Denn die Gerechten, die viele gute Werke bei dir aufbewahrt haben, sollen aus ihren eigenen Werken Lohn empfangen.',
'Denn was ist der Mensch, daß du Mißfallen an ihm haben solltest? oder was ist ein vergängliches Geschlecht, daß du so bitter über es sein solltest?',
'Denn in Wahrheit gibt es keinen Menschen unter den Geborenen, der nicht gottlos gehandelt hat; und unter den Treuen gibt es keinen, der nicht gesündigt hat.',
'Denn darin, o Herr, sollen deine Gerechtigkeit und deine Güte erklärt werden, wenn du derer barmherzig bist, die das Vertrauen auf gute Werke nicht haben.',
'Da antwortete er mir und sprach: Einiges hast du recht gesprochen, und nach deinen Worten soll es geschehen.',
'Denn ich werde in der Tat nicht bedenken die Gesinnung derer, die vor dem Tod, vor dem Gericht, vor der Vernichtung gesündigt haben:',
'aber ich werde mich über die Gesinnung der Gerechten freuen, und werde auch ihrer Pilgerschaft gedenken und ihrer Errettung und der Belohnung, die sie empfangen sollen.',
'Wie ich jetzt geredet habe, so soll es geschehen.',
'Denn wie der Ackersmann viel Samen auf den Boden sät und viele Bäume pflanzt, und doch das, was gut gesät ist, zu seiner Zeit nicht aufgeht, noch alles, was gepflanzt ist, Wurzel faßt: so ist es auch mit denen, die in der Welt gesät sind; sie werden nicht alle gerettet.',
'Ich antwortete dann und sprach: Wenn ich Gnade gefunden habe, laß mich reden.',
'Wie der Samen des Ackersmanns verkommt, wenn er nicht aufgeht und nicht deinen Regen zu seiner Zeit empfängt; oder wenn zu viel Regen kommt und ihn verdirbt:',
'so kommt auch der Mensch um, der mit deinen Händen geformt ist und dein Bild genannt wird, um dessenwillen du alle Dinge gemacht hast und den du dem Samen des Ackersmanns verglichen hast.',
'Sei nicht zornig über uns, sondern schone dein Volk und habe Erbarmen mit deinem Erbe; denn du bist deiner Schöpfung gegenüber barmherzig.',
'Da antwortete er mir und sprach: Die gegenwärtigen Dinge sind für die Gegenwart, und die zukünftigen für die, die kommen.',
'Denn du hast weit gefehlt, daß du die Liebe zu meiner Schöpfung mehr haben könntest als ich: aber ich habe mich oft dir und ihr genähert, nie aber den Ungerechten.',
'Auch darin bist du wunderbar vor dem Allerhöchsten:',
'daß du dich gedemütigt hast, wie es sich für dich ziemt, und dich nicht für würdig gehalten hast, sehr verherrlicht zu werden unter den Gerechten.',
'Denn viele große Unglücksfälle werden denen geschehen, die in den letzten Zeiten auf der Erde wohnen werden, weil sie in großem Hochmut gewandelt haben.',
'Verstehe du aber für dich selbst und suche die Herrlichkeit für solche, die dir ähnlich sind.',
'Denn euch ist das Paradies geöffnet, der Baum des Lebens gepflanzt, die zukünftige Zeit bereitet, der Überfluß gemacht, eine Stadt gebaut, die Ruhe erlaubt, ja vollkommene Güte und Weisheit.',
'Die Wurzel des Bösen ist bei euch versiegelt; Schwachheit und der Wurm sind vor euch verborgen, und die Verderbnis ist in die Hölle geflohen, um vergessen zu werden:',
'Schmerzen sind vergangen, und am Ende ist der Schatz der Unsterblichkeit gezeigt.',
'Und darum frage nicht mehr nach der Menge derer, die umkommen.',
'Denn als sie Freiheit hatten, verachteten sie den Allerhöchsten, achteten sein Gesetz gering und verließen seine Wege.',
'Dazu haben sie seine Gerechten zertreten,',
'und sagten in ihrem Herzen, daß kein Gott sei; ja, das sagten sie, obwohl sie wußten, daß sie sterben müßten.',
'Denn wie euch die genannten Dinge empfangen werden, so sollen Durst und Pein für sie bereitet werden; denn es war nicht sein Wille, daß die Menschen ins Verderben kommen:',
'aber die Erschaffenen haben den Namen des, der sie gemacht hat, entehrt und waren undankbar dem gegenüber, der ihnen das Leben bereitet hatte.',
'Und darum ist mein Gericht jetzt nah.',
'Diese Dinge habe ich nicht allen Menschen gezeigt, sondern dir und einigen wenigen, die dir gleich sind. Da antwortete ich und sprach:',
'Sieh, o Herr, nun hast du mir die Menge der Wunder gezeigt, die du in der letzten Zeit zu tun beginnen wirst: zu welcher Zeit aber, hast du mir nicht gezeigt.'
];

const out = JSON.parse(fs.readFileSync(__dirname+'/tmp_b75_a.json','utf8'));
[ch5, ch6, ch7, ch8].forEach((verses, i) => {
  const cn = i+5;
  const vv = {};
  verses.forEach((t,j)=>{ vv[j+1]={verse:j+1,text:t}; });
  out.chapters[cn] = {chapter:cn, name:'', verses:vv};
});

fs.writeFileSync(__dirname+'/tmp_b75_b.json', JSON.stringify(out), 'utf8');
const total = [ch5,ch6,ch7,ch8].reduce((s,c)=>s+c.length,0);
console.log('Batch B fertig: Kapitel 5-8, '+total+' Verse');
