// Batch C: Buch 75 (4. Esra) Kapitel 9–12
const fs = require('fs');

const ch9 = [
'Er antwortete mir dann und sprach: Messe die Zeit sorgfältig in sich selbst: und wenn du siehst, daß ein Teil der Zeichen, die ich dir vorher gesagt habe, vergangen ist,',
'dann wirst du verstehen, daß eben dies die Zeit ist, in der der Allerhöchste anfangen wird, die Welt heimzusuchen, die er gemacht hat.',
'Wenn also Erdbeben und Aufruhr der Völker in der Welt gesehen werden:',
'dann wirst du wohl verstehen, daß der Allerhöchste von den Tagen an, die vor dir waren, von Anfang an von diesen Dingen geredet hat.',
'Denn wie alles, was in der Welt gemacht ist, einen Anfang und ein Ende hat und das Ende offenbar ist:',
'so haben auch die Zeiten des Allerhöchsten klare Anfänge in Wundern und mächtigen Werken, und Enden in Wirkungen und Zeichen.',
'Und wer auch immer gerettet wird und in der Lage sein wird, durch seine Werke und durch den Glauben zu entrinnen, durch den ihr geglaubt habt,',
'soll von den genannten Gefahren bewahrt werden und mein Heil in meinem Lande und innerhalb meiner Grenzen sehen; denn ich habe sie mir vom Anfang geheiligt.',
'Dann sollen es betrübt empfangen, die jetzt meine Wege mißbraucht haben; und die sie mit Verachtung von sich geworfen haben, sollen in Qualen wohnen.',
'Denn solche, die zu Lebzeiten Wohltaten empfangen haben und mich nicht erkannt haben;',
'und die mein Gesetz verachtet haben, solange sie noch Freiheit hatten, und da noch ein Ort der Reue offen stand, ihn nicht verstanden, sondern verachtet haben;',
'die müssen es nach dem Tod durch Schmerzen erkennen.',
'Darum sei nicht neugierig, wie die Gottlosen gestraft werden und wann: forsche aber, wie die Gerechten gerettet werden, deren die Welt ist und für die die Welt erschaffen ist.',
'Da antwortete ich und sprach:',
'Ich habe vorher gesagt und spreche es jetzt und werde es auch hernach sagen, daß mehr zugrunde gehen als gerettet werden,',
'wie eine Welle größer ist als ein Tropfen.',
'Er antwortete mir und sprach: Wie das Feld ist, so ist auch der Same; wie die Blumen sind, so sind auch die Farben; wie das Werk des Arbeiters ist, so ist auch das Werk; und wie der Ackersmann selbst ist, so ist auch sein Ackerbau: denn das war die Zeit der Welt.',
'Und nun, als ich die Welt bereitete, die noch nicht gemacht war, gar für die, die jetzt darin wohnen, sprach keiner gegen mich.',
'Denn damals gehorchte ein jeder: nun aber sind die Sitten derer, die in dieser gemachten Welt erschaffen sind, durch einen beständigen Samen und durch ein unergründliches Gesetz verdorben.',
'So betrachtete ich die Welt, und sieh, da war Gefahr wegen der Pläne, die in sie hereingekommen waren.',
'Und ich sah und schonte sie sehr, und bewahrte mir eine Traube aus der Traube, und ein Pflänzchen aus einer großen Menge.',
'So mag denn die Menge umkommen, die vergebens geboren wurde; und meine Traube und mein Pflänzchen sollen bewahrt werden; denn mit großer Mühe habe ich es vollkommen gemacht.',
'Gleichwohl, wenn du noch sieben Tage zuwarten willst, (aber du sollst darin nicht fasten,',
'sondern geh auf ein Blumenfeld, wo kein Haus gebaut ist, und iß nur die Blumen des Feldes; koste kein Fleisch, trinke keinen Wein, sondern iß nur Blumen;)',
'und bete ohne Unterlaß zum Allerhöchsten, dann werde ich kommen und mit dir reden.',
'So ging ich meines Weges auf das Feld, das Ardath heißt, wie er mir befohlen hatte; und da saß ich bei den Blumen und aß von den Kräutern des Feldes, und das Essen derselben sättigte mich.',
'Nach sieben Tagen saß ich auf dem Grase, und mein Herz war abermals in mir geängstet wie zuvor:',
'und ich öffnete meinen Mund und begann vor dem Allerhöchsten zu reden, und sprach:',
'O Herr, der du dich uns offenbarest, du wurdest unsern Vätern in der Wüste gezeigt, an einem Ort, wo kein Mensch wandelt, in einem öden Land, als sie aus Ägypten auszogen.',
'Und du sprachst und sagtest: Höre mich, Israel; merke auf meine Worte, du Same Jakobs.',
'Denn sieh, ich säe mein Gesetz in euch, und es soll in euch Frucht bringen, und ihr sollt in ihm auf ewig geehrt werden.',
'Aber unsere Väter, die das Gesetz empfingen, hielten es nicht und beobachteten nicht deine Satzungen; und obwohl die Frucht deines Gesetzes nicht umkam, noch konnte sie das; denn sie war dein;',
'vergingen doch die, die es empfingen, weil sie die Sache nicht bewahrten, die in sie gesät war.',
'Und das ist ein gewöhnliches Geschick: wenn der Boden Samen empfangen hat, oder das Meer ein Schiff, oder ein Gefäß Speise oder Trank,',
'daß das Ding, in dem es gesät oder geworfen oder aufgenommen worden ist, vergeht, und die Sache, die darin gesät oder geworfen oder aufgenommen war, auch vergeht und nicht bei uns bleibt: mit uns aber ist es nicht so gewesen.',
'Denn wir, die wir das Gesetz empfangen haben, gehen durch Sünde zugrunde, und unser Herz auch, das es empfangen hat.',
'Gleichwohl vergeht das Gesetz nicht, sondern bleibt in seiner Kraft.',
'Und als ich diese Dinge in meinem Herzen redete, blickte ich mit meinen Augen um mich, und sah zur Rechten ein Weib; und sieh, sie trauerte und weinte mit lauter Stimme und war sehr betrübt im Herzen; und ihre Kleider waren zerrissen und Asche auf ihrem Haupt.',
'Da ließ ich die Gedanken, mit denen ich beschäftigt war, fahren, und wandte mich ihr zu',
'und sprach zu ihr: Warum weinst du? warum bist du so betrübt im Herzen?',
'Sie aber sprach zu mir: Herr, laß mich für mich selbst klagen und zu meinem Schmerz hinzutun; denn ich bin sehr bedrängt in meinem Sinn und sehr erniedrigt.',
'Und ich sprach zu ihr: Was fehlt dir? sage mir.',
'Sie sprach zu mir: Ich, deine Magd, war unfruchtbar und hatte kein Kind, obwohl ich dreißig Jahre lang einen Mann hatte,',
'und diese dreißig Jahre habe ich nichts anderes getan, Tag und Nacht und jede Stunde, als mein Gebet zum Allerhöchsten zu machen.',
'Nach dreißig Jahren erhörte mich Gott, deine Magd, blickte auf mein Elend, achtete auf meine Bedrängnis, und gab mir einen Sohn: und ich freute mich sehr über ihn, und so tat auch mein Mann und alle meine Nachbarn; und wir gaben dem Allmächtigen große Ehre.',
'Und ich nährte ihn mit großer Mühe.',
'Als er nun aufwuchs und die Zeit kam, daß er eine Frau haben sollte, machte ich ein Gastmahl.',
'Und es begab sich, als mein Sohn in sein Brautgemach eingetreten war, fiel er nieder und starb.',
'Dann warfen wir alle die Lichter um, und alle meine Nachbarn standen auf, um mich zu trösten; so ruhte ich bis zur zweiten Nacht.',
'Und es begab sich, als alle aufgehört hatten, mich zu trösten, damit ich Ruhe haben möchte; da stand ich auf in der Nacht und floh und kam hierher auf dieses Feld, wie du siehst.',
'Und ich habe nun beschlossen, nicht in die Stadt zurückzukehren, sondern hier zu bleiben und weder zu essen noch zu trinken, sondern beständig zu trauern und zu fasten, bis ich sterbe.',
'Da ließ ich die Überlegungen, darin ich war, fahren und redete sie in Zorn an und sprach:',
'Du törichtes Weib über alle anderen, siehst du nicht unsere Trauer und was uns begegnet?',
'Wie daß Zion, unsere Mutter, voll aller Schwermut und sehr gedemütigt ist, sehr schwer trauernd?',
'Und nun, da wir alle trauern und betrübt sind, denn wir sind alle in Schwermut, bist du wegen eines einzigen Sohnes betrübt?',
'Denn frage die Erde, und sie wird dir sagen, daß sie es ist, die trauern soll um den Fall so vieler, die auf ihr wachsen.',
'Denn von ihr kamen alle im Anfang, und andere werden von ihr kommen; und sieh, fast alle gehen ins Verderben und die Menge derselben wird ganz ausgerottet.',
'Wer soll also mehr trauern als sie, die eine so große Menge verloren hat; und nicht du, die du nur um einen betrübt bist?',
'Wenn du aber zu mir sagst: Meine Klage ist nicht wie die Klage der Erde, denn ich habe die Frucht meines Leibes verloren, den ich mit Schmerzen geboren und mit Mühen getragen habe;',
'aber die Erde nicht so: denn die Menge, die in ihr vorhanden ist, nach dem Lauf der Erde, ist gegangen, wie sie gekommen ist:',
'dann sage ich zu dir: Wie du mit Mühen geboren hast; so hat auch die Erde ihre Frucht, nämlich den Menschen, von Anfang an von jeher dem gegeben, der sie gemacht hat.',
'Behalte nun deinen Schmerz für dich und trage mit Fassung, was dich betroffen hat.',
'Denn wenn du das Urteil Gottes als gerecht anerkennst, wirst du deinen Sohn zur Zeit empfangen und unter den Frauen gelobt werden.',
'Geh nun in die Stadt zu deinem Mann.',
'Sie aber sprach zu mir: Das werde ich nicht tun; ich will nicht in die Stadt gehen, sondern will hier sterben.',
'So fuhr ich fort zu ihr zu reden und sprach:',
'Tu das nicht, sondern laß dich von mir raten; denn wie viele sind die Widerwärtigkeiten Zions? Laß dich trösten wegen der Betrübnis Jerusalems.',
'Denn du siehst, daß unser Heiligtum verwüstet ist, unser Altar niedergerissen, unser Tempel zerstört;',
'unser Psalter liegt auf dem Boden, unser Lied ist verstummt, unsere Freude ist ein Ende, das Licht unseres Leuchters ist ausgelöscht, die Lade unseres Bundes geraubt, unsere Heiligkeiten entweiht und der Name, der über uns ausgerufen wird, ist fast entheiligt: unsere Kinder sind beschämt, unsere Priester sind verbrannt, unsere Leviten sind in die Gefangenschaft geführt, unsere Jungfrauen sind geschändet und unsere Frauen vergewaltigt; unsere Gerechten sind weggeführt, unsere Kleinen vernichtet, unsere Jünglinge in Knechtschaft gebracht und unsere Starken sind schwach geworden;',
'und was das Größte von allem ist, das Siegel Zions hat jetzt ihre Ehre verloren; denn sie ist in die Hände derer gegeben, die uns hassen.',
'Und darum schüttele deine große Schwermut ab und lege die Menge der Traurigkeiten beiseite, damit der Mächtige dir wieder gnädig sein möge und der Allerhöchste dir Ruhe und Erquickung von deiner Mühsal geben möge.',
'Und es begab sich, während ich mit ihr redete, sieh, ihr Angesicht leuchtete plötzlich strahlend auf und ihr Antlitz glänzte, so daß ich mich vor ihr fürchtete und überlegte, was das bedeuten möge.',
'Und sieh, plötzlich machte sie einen großen und sehr furchtbaren Schrei; so daß die Erde vor dem Schrei des Weibes erbebte.',
'Und ich sah, und sieh, das Weib erschien mir nicht mehr, sondern da war eine Stadt gebaut und ein großer Platz zeigte sich von den Grundmauern: da erschrak ich und schrie mit lauter Stimme und sprach:',
'Wo ist Uriel, der Engel, der zuerst zu mir kam? denn er hat mich in viele Ohnmachten fallen lassen, und mein Ende ist in Verderbnis verwandelt und mein Gebet zum Tadel geworden.',
'Und als ich diese Worte redete, sieh, da kam er zu mir und blickte mich an.',
'Und sieh, ich lag wie ein Toter, und mein Verstand war mir genommen; und er ergriff mich an der rechten Hand, tröstete mich und stellte mich auf meine Füße und sprach zu mir:',
'Was fehlt dir? und warum bist du so beunruhigt? und warum ist dein Verstand getrübt und die Gedanken deines Herzens?',
'Ich antwortete und sprach: Weil du mich verlassen hast, und ich doch nach deinen Worten handelte, und auf das Feld ging, und sieh, ich habe gesehen und sehe noch, was ich nicht auszudrücken vermag.',
'Er sprach zu mir: Stehe mannhaft auf und ich will dich beraten.',
'Da sprach ich: Rede, mein Herr, in mir; verlaß mich nicht, damit ich nicht vergebens der Hoffnung beraubt sterbe.',
'Denn ich habe gesehen, was ich nicht wußte, und höre, was ich nicht kenne.',
'Oder ist mein Sinn getäuscht, oder meine Seele in einem Traum?',
'Nun bitte ich dich, daß du deinem Knecht dieses Gesicht erklärst.',
'Er antwortete mir dann und sprach: Höre mich, so will ich dich unterweisen und dir sagen, warum du erschrocken bist; denn der Allerhöchste wird dir viele verborgene Dinge offenbaren.',
'Er hat gesehen, daß dein Weg recht ist; denn daß du beständig um dein Volk trauerst und über Zion sehr klagst.',
'Dies nun ist die Bedeutung des Gesichts, das du neulich gesehen hast:',
'Du sahst ein Weib trauern und begannest sie zu trösten:',
'aber nun siehst du die Gleichheit des Weibes nicht mehr, sondern es erschien dir eine Stadt gebaut.',
'Und während sie dir vom Tod ihres Sohnes erzählte, ist dies die Deutung:',
'Dieses Weib, das du sahst, ist Zion: und da sie dir sagte, daß sie dreißig Jahre unfruchtbar gewesen sei, bedeutet das die dreißig Jahre, in denen kein Opfer in ihr dargebracht wurde.',
'Aber nach dreißig Jahren baute Salomo die Stadt und brachte Opfer dar; da gebar die Unfruchtbare einen Sohn.',
'Und da sie dir sagte, daß sie ihn mit Mühe aufzog, bedeutet das die Wohnung in Jerusalem.',
'Da sie dir aber sagte, daß mein Sohn, als er in sein Brautgemach eingetreten war, einen Fall tat und starb: das war die Zerstörung, die über Jerusalem kam.',
'Und sieh, du sahst ihre Gleichheit; und weil sie um ihren Sohn trauerte, begannest du sie zu trösten: und von diesen Dingen, die geschehen sind, sollen dir diese geöffnet werden.',
'Denn nun sieht der Allerhöchste, daß du aufrichtig betrübt bist und von ganzem Herzen um sie leidest, so hat er dir die Herrlichkeit ihrer Pracht und die Schönheit ihrer Anmut gezeigt.',
'Und darum hieß ich dich auf dem Feld bleiben, wo kein Haus gebaut war:',
'denn ich wußte, daß der Allerhöchste dir dies zeigen würde.',
'Darum befahl ich dir, auf das Feld zu gehen, wo kein Fundament irgendwelchen Bauwerkes war.',
'Denn an dem Ort, wo der Allerhöchste anfängt, seine Stadt zu zeigen, kann kein von Menschenhand errichtetes Gebäude bestehen.',
'Darum fürchte dich nicht, und erschrecke dein Herz nicht; sondern geh hinein und sieh die Schönheit und Größe des Bauwerkes, soviel deine Augen sehen können;',
'und dann wirst du so viel hören, als deine Ohren fassen können.',
'Denn du bist über viele andere seliggepriesen und bist gerufen von dem Allerhöchsten; und so sind es nur wenige.',
'Aber morgen nacht sollst du hier bleiben;',
'und der Allerhöchste soll dir Gesichte von den hohen Dingen zeigen, die der Allerhöchste an denen, die auf Erden wohnen, in den letzten Tagen tun wird. So schlief ich jene Nacht und eine andere, wie er mir befohlen hatte.'
];

const ch10 = [
'Und es begab sich, als mein Sohn in sein Brautgemach eingetreten war, fiel er nieder und starb.',
'Da warfen wir alle die Lichter um, und alle meine Nachbarn standen auf, um mich zu trösten; so ruhte ich bis zur zweiten Nacht.',
'Und es begab sich, als alle aufgehört hatten mich zu trösten, damit ich Ruhe haben möchte; da stand ich auf in der Nacht und floh und kam hierher auf dieses Feld, wie du siehst.',
'Und ich habe nun beschlossen, nicht in die Stadt zurückzukehren, sondern hier zu bleiben und weder zu essen noch zu trinken, sondern beständig zu trauern und zu fasten, bis ich sterbe.',
'Da ließ ich die Überlegungen, darin ich war, fahren und redete sie im Zorn an und sprach:',
'Du törichtes Weib über alle anderen, siehst du nicht unsere Trauer und was uns begegnet?',
'Wie daß Zion, unsere Mutter, voll aller Schwermut und sehr gedemütigt ist, schwer trauernd?',
'Und nun, da wir alle trauern und betrübt sind; denn wir sind alle in Schwermut, bist du wegen eines einzigen Sohnes betrübt?',
'Denn frage die Erde, und sie wird dir sagen, daß sie es ist, die trauern soll um den Fall so vieler, die auf ihr wachsen.',
'Denn von ihr kamen alle im Anfang, und andere werden von ihr kommen; und sieh, fast alle gehen ins Verderben und die Menge derselben wird ganz ausgerottet.',
'Wer soll also mehr trauern als sie, die eine so große Menge verloren hat; und nicht du, die du nur um einen betrübt bist?',
'Wenn du aber zu mir sagst: Meine Klage ist nicht wie die Klage der Erde, denn ich habe die Frucht meines Leibes verloren, den ich mit Schmerzen geboren und mit Mühen getragen habe;',
'aber die Erde nicht so: denn die Menge, die in ihr vorhanden ist, ist nach dem Lauf der Erde gegangen, wie sie gekommen ist:',
'dann sage ich zu dir: Wie du mit Mühen geboren hast; so hat auch die Erde ihre Frucht, nämlich den Menschen, von Anfang an dem gegeben, der sie gemacht hat.',
'Behalte nun deinen Schmerz für dich und trage mit Fassung, was dich betroffen hat.',
'Denn wenn du das Urteil Gottes als gerecht anerkennst, wirst du deinen Sohn zur Zeit empfangen und unter den Frauen gelobt werden.',
'Geh nun in die Stadt zu deinem Mann.',
'Sie aber sprach zu mir: Das werde ich nicht tun; ich will nicht in die Stadt gehen, sondern will hier sterben.',
'So fuhr ich fort zu ihr zu reden und sprach:',
'Tu das nicht, sondern laß dich von mir raten: denn wie viele sind die Widerwärtigkeiten Zions? Laß dich trösten wegen der Betrübnis Jerusalems.',
'Denn du siehst, daß unser Heiligtum verwüstet ist, unser Altar niedergerissen, unser Tempel zerstört;',
'unser Psalter liegt auf dem Boden, unser Lied ist verstummt, unsere Freude ist ein Ende, das Licht unseres Leuchters ist ausgelöscht, die Lade unseres Bundes geraubt, unsere Heiligkeiten entweiht; unsere Kinder sind beschämt, unsere Priester verbrannt, unsere Leviten in die Gefangenschaft geführt, unsere Jungfrauen geschändet und unsere Frauen vergewaltigt; unsere Gerechten weggeführt, unsere Kleinen vernichtet, unsere Jünglinge in Knechtschaft gebracht und unsere Starken schwach geworden;',
'und was das Größte ist, das Siegel Zions hat ihre Ehre verloren; denn sie ist in die Hände derer gegeben, die uns hassen.',
'Darum schüttele deine Schwermut ab und lege die Traurigkeiten beiseite, damit der Mächtige dir wieder gnädig sei und der Allerhöchste dir Ruhe von deiner Mühsal gebe.',
'Und es begab sich, während ich mit ihr redete, leuchtete ihr Angesicht plötzlich strahlend auf und ihr Antlitz glänzte, so daß ich mich vor ihr fürchtete.',
'Und sieh, plötzlich machte sie einen großen und sehr furchtbaren Schrei; so daß die Erde erbebte.',
'Und ich sah, und sieh, das Weib erschien mir nicht mehr, sondern da war eine Stadt gebaut und ein großer Platz zeigte sich von den Grundmauern: da erschrak ich und schrie mit lauter Stimme.',
'Wo ist Uriel, der Engel? denn er hat mich in viele Ohnmachten fallen lassen, und mein Ende ist in Verderbnis verwandelt.',
'Und als ich diese Worte redete, kam er zu mir und blickte mich an.',
'Und sieh, ich lag wie ein Toter, und mein Verstand war mir genommen; und er ergriff mich an der rechten Hand, tröstete mich und stellte mich auf meine Füße.',
'Was fehlt dir? und warum bist du so beunruhigt? und warum ist dein Verstand getrübt?',
'Ich antwortete: Weil du mich verlassen hast, und ich auf das Feld ging, und sieh, ich sehe, was ich nicht auszudrücken vermag.',
'Er sprach: Stehe mannhaft auf und ich will dich beraten.',
'Rede, mein Herr; verlaß mich nicht, damit ich nicht vergebens sterbe.',
'Denn ich habe gesehen, was ich nicht wußte, und höre, was ich nicht kenne.',
'Höre mich, so will ich dich unterweisen, warum du erschrocken bist; denn der Allerhöchste wird dir viele Dinge offenbaren.',
'Er hat gesehen, daß dein Weg recht ist; denn du trauerst beständig um dein Volk und klagst sehr über Zion.',
'Dies ist die Bedeutung des Gesichts, das du neulich gesehen hast:',
'Du sahst ein Weib trauern und begannest sie zu trösten:',
'aber nun siehst du die Gleichheit des Weibes nicht mehr, sondern es erschien dir eine Stadt gebaut.',
'Und während sie dir vom Tod ihres Sohnes erzählte, ist dies die Deutung:',
'Dieses Weib ist Zion: und ihre dreißig Jahre der Unfruchtbarkeit bedeuten die dreißig Jahre, in denen kein Opfer in ihr dargebracht wurde.',
'Aber nach dreißig Jahren baute Salomo die Stadt und brachte Opfer dar; da gebar die Unfruchtbare einen Sohn.',
'Und daß sie ihn mit Mühe aufzog, bedeutet die Wohnung in Jerusalem.',
'Da sie aber sagte, daß mein Sohn in sein Brautgemach eingetreten einen Fall tat und starb: das war die Zerstörung Jerusalems.',
'Und sieh, du sahst ihre Gleichheit und weil sie trauerte, tröstetest du sie: und von diesen Dingen werden dir diese geöffnet.',
'Denn nun sieht der Allerhöchste, daß du aufrichtig betrübt bist und von ganzem Herzen um sie leidest, so hat er dir die Herrlichkeit ihrer Pracht gezeigt.',
'Darum hieß ich dich auf dem Feld bleiben, wo kein Haus gebaut war:',
'denn ich wußte, daß der Allerhöchste dir dies zeigen würde.',
'Darum befahl ich dir, auf das Feld zu gehen, wo kein Fundament war.',
'Denn an dem Ort, wo der Allerhöchste anfängt, seine Stadt zu zeigen, kann kein von Menschenhand errichtetes Gebäude bestehen.',
'Darum fürchte dich nicht, sondern geh hinein und sieh die Schönheit des Bauwerkes;',
'und dann wirst du so viel hören, als deine Ohren fassen können.',
'Denn du bist über viele andere seliggepriesen und bist gerufen von dem Allerhöchsten; und so sind es nur wenige.',
'Aber morgen nacht sollst du hier bleiben;',
'und der Allerhöchste soll dir Gesichte von hohen Dingen zeigen, die er an denen, die auf Erden wohnen, in den letzten Tagen tun wird. So schlief ich jene Nacht und eine weitere, wie er mir befohlen hatte.'
];

const ch11 = [
'Da sah ich einen Traum, und sieh, da stieg aus dem Meer ein Adler auf, der zwölf gefiederte Flügel und drei Köpfe hatte.',
'Und ich sah, und sieh, er breitete seine Flügel über die ganze Erde; und alle Winde der Luft bliesen auf ihn und wurden zusammengeführt.',
'Und ich sah, und aus seinen Federn wuchsen andere Federn entgegen; und sie wurden kleine und kleine Federn.',
'Aber seine Köpfe ruhten; der Kopf in der Mitte war größer als die anderen, und doch ruhte er mit dem Rest.',
'Dazu sah ich, daß der Adler mit seinen Federn flog und auf der Erde regierte und über die darin wohnten.',
'Und ich sah, daß alles unter dem Himmel ihm untertan war, und kein Mensch redete gegen ihn, keines der Geschöpfe auf Erden.',
'Und ich sah, und sieh, der Adler erhob sich auf seinen Klauen und redete zu seinen Federn und sprach:',
'Wachet nicht alle auf einmal; schläft jeder an seinem Platz, und wacht nach der Reihe:',
'aber die Köpfe sollen für das Letzte aufbewahrt werden.',
'Und ich sah, und sieh, die Stimme ging nicht von seinen Köpfen aus, sondern aus der Mitte seines Leibes.',
'Und ich zählte seine entgegengewachsenen Federn, und sieh, es waren acht.',
'Und ich sah, und sieh, auf der rechten Seite stand eine Feder auf und herrschte über die ganze Erde;',
'und so geschah es: als sie herrschte, kam ihr Ende, und ihr Platz erschien nicht mehr; so trat die nächste an und herrschte und hatte eine lange Zeit;',
'und es geschah, als sie herrschte, kam ihr Ende auch, wie das erste, so daß sie nicht mehr erschien.',
'Da kam eine Stimme zu ihr und sprach:',
'Höre du, die du lange Zeit über die Erde geherrscht hast; das sage ich dir, ehe du anfängst nicht mehr zu erscheinen:',
'es soll keiner nach dir zu deiner Zeit kommen, noch zur Hälfte derselben.',
'Da stand die dritte auf und herrschte wie die anderen zuvor, und erschien auch nicht mehr.',
'So erging es allen übrigen, einem nach dem anderen: ein jeder herrschte und erschien dann nicht mehr.',
'Da sah ich, und sieh, nach einiger Zeit standen die folgenden Federn auf der rechten Seite auf, daß auch sie herrschten; und einige von ihnen herrschten, aber nach kurzer Zeit erschienen sie auch nicht mehr:',
'denn einige von ihnen wurden aufgestellt, herrschten aber nicht.',
'Danach sah ich, daß die zwölf Federn und die zwei kleinen Federn nicht mehr erschienen;',
'und am Leib des Adlers war nichts mehr als die drei Köpfe, die ruhten, und sechs kleine Flügel.',
'Dann sah ich auch, daß sich zwei kleine Federn von den sechs absonderten und unter dem Kopf, der auf der rechten Seite war, blieben; denn die vier blieben an ihrem Ort.',
'Und ich sah, und sieh, die Federn, die unter dem Flügel waren, dachten daran, sich aufzustellen und die Herrschaft zu haben.',
'Und ich sah, und sieh, eine wurde aufgestellt, aber kurz darauf erschien sie nicht mehr.',
'Und die zweite war früher weg als die erste.',
'Und ich sah, und sieh, die zwei übrigen dachten auch in sich selbst zu herrschen:',
'und als sie so dachten, sieh, da erwachte einer der Köpfe, die ruhten, nämlich der, der in der Mitte war; denn der war größer als die zwei anderen.',
'Und dann sah ich, daß die zwei anderen Köpfe mit ihm vereint wurden.',
'Und sieh, der Kopf wandte sich mit denen, die bei ihm waren, und fraß die zwei Federn unter dem Flügel, die herrschen wollten.',
'Aber dieser Kopf brachte die ganze Erde in Furcht und herrschte über sie über alle die, die darin wohnten, mit großer Unterdrückung; und er hatte die Regierung der Welt mehr als alle Flügel, die gewesen waren.',
'Und nach diesem sah ich, und sieh, der Kopf, der in der Mitte war, erschien plötzlich nicht mehr, wie auch die Flügel.',
'Aber es blieben die zwei Köpfe, die auch in gleicher Weise über die Erde und die darin wohnten herrschten.',
'Und ich sah, und sieh, der Kopf auf der rechten Seite fraß den, der auf der linken war.',
'Da hörte ich eine Stimme, die zu mir sprach: Sieh vor dir und betrachte das, was du siehst.',
'Und ich sah, und sieh, wie ein brüllender Löwe aus dem Walde gejagt wurde: und ich sah, daß er eine Menschenstimme zu dem Adler sandte und sprach:',
'Höre du, ich will mit dir reden, und der Allerhöchste soll dir sagen:',
'Bist du nicht du, der noch von den vier Tieren übrig ist, die ich machte, in meiner Welt zu herrschen, damit das Ende ihrer Zeiten durch sie kommen möchte?',
'Und der vierte kam und überwand alle Tiere, die zuvor waren, und hatte Macht über die Welt mit großem Schrecken und über den ganzen Umkreis der Erde mit viel gottloser Unterdrückung; und so lange wohnte er auf der Erde mit Betrug.',
'Denn die Erde hast du nicht mit Wahrheit gerichtet.',
'Denn du hast die Sanftmütigen bedrückt, die Friedlichen verletzt, die Lügner geliebt und die Wohnstätten derer, die Frucht brachten, zerstört und die Mauern derer niedergerissen, die dir nichts Böses getan hatten.',
'Darum ist dein ungerechtes Handeln zum Allerhöchsten hinaufgelangt und dein Hochmut zum Mächtigen.',
'Der Allerhöchste hat auch die stolzen Zeiten angeschaut, und sieh, sie sind vollendet, und seine Greuel sind erfüllt.',
'Und darum erscheine nicht mehr, du Adler, noch deine furchtbaren Flügel, noch deine gottlosen Federn noch deine bösen Köpfe noch deine schädlichen Klauen noch dein ganzer nichtiger Leib:',
'damit die ganze Erde erquickt werde und aufatme, erlöst von deiner Gewalt, und hoffe auf das Gericht und die Barmherzigkeit dessen, der sie gemacht hat.'
];

const ch12 = [
'Und es begab sich, als der Löwe diese Worte zu dem Adler geredet hatte, sah ich,',
'und sieh, der verbleibende Kopf und die vier Flügel erschienen nicht mehr, und die zwei gingen zu ihm und setzten sich auf, um zu herrschen, und ihr Königreich war klein und voll Unruhe.',
'Und ich sah, und sieh, sie erschienen nicht mehr, und der ganze Leib des Adlers wurde verbrannt, so daß die Erde in großer Furcht war: da erwachte ich aus Aufruhr und Angst meines Geistes und aus großer Furcht und sprach zu meinem Geist:',
'Sieh, dies hast du mir getan, daß du die Wege des Allerhöchsten erforschtest.',
'Sieh, nun bin ich in meinem Sinn müde und sehr schwach in meinem Geist; und wenig Kraft ist in mir wegen der großen Furcht, mit der ich diese Nacht gequält wurde.',
'Darum werde ich nun den Allerhöchsten bitten, daß er mich bis ans Ende trösten möge.',
'Und ich sprach: Herr, der du herrschest, wenn ich Gnade vor deinen Augen gefunden habe, und wenn ich vor dir vielen anderen gerechtfertigt bin, und wenn mein Gebet wirklich vor dein Angesicht gelangt ist:',
'so tröste mich dann und zeige deinem Knecht die Auslegung und den klaren Unterschied dieses furchtbaren Gesichts, damit du meine Seele vollkommen trösten mögest.',
'Denn du hast mich für würdig gehalten, mir die letzte Zeit zu zeigen.',
'Er sprach zu mir: Dies ist die Auslegung des Gesichts:',
'Der Adler, den du aus dem Meer aufsteigen sahst, ist das Königreich, das im Gesicht deines Bruders Daniel gesehen wurde.',
'Aber es wurde ihm nicht erklärt; darum erkläre ich es jetzt dir.',
'Sieh, die Tage werden kommen, daß ein Königreich auf Erden aufsteigen wird, und es wird mehr gefürchtet werden als alle Königreiche, die vor ihm waren.',
'In demselben werden zwölf Könige nacheinander herrschen:',
'davon wird der zweite anfangen zu herrschen und mehr Zeit haben als alle zwölf.',
'Das bedeuten die zwölf Flügel, die du sahst.',
'Was die Stimme betrifft, die du hörtest reden, und die du nicht von den Köpfen ausgehen sahst, sondern aus der Mitte seines Leibes: dies ist die Auslegung:',
'daß nach der Zeit jenes Königreiches große Kämpfe entstehen werden, und es wird in Gefahr stehen zu fallen; gleichwohl wird es nicht fallen, sondern wieder zu seinem Anfang hergestellt werden.',
'Und da du die acht kleinen Federn sahst, die an ihren Flügeln hingen: dies ist die Auslegung:',
'daß in ihm acht Könige aufstehen werden, deren Zeiten kurz und die Jahre schnell sein sollen.',
'Und zwei von ihnen werden umkommen, wenn sich die Mitte der Zeit nähert: vier sollen bewahrt werden bis zu ihrem Ende; aber zwei sollen bis ans Ende bewahrt werden.',
'Und da du drei Köpfe ruhend sahst: dies ist die Auslegung:',
'In seinen letzten Tagen wird der Allerhöchste drei Königreiche auferwecken und viele Dinge darin erneuern, und sie sollen über die Erde herrschen,',
'und über die darin wohnen, mit vieler Unterdrückung, mehr als alle vor ihnen: darum werden sie die Köpfe des Adlers genannt.',
'Denn diese sind es, die seine Gottlosigkeit vollenden und sein letztes Ende herbeiführen sollen.',
'Und da du sahst, daß der große Kopf nicht mehr erschien, bedeutet es, daß einer von ihnen auf seinem Bett sterben und doch mit Schmerzen.',
'Denn die zwei, die bleiben, sollen durch das Schwert getötet werden.',
'Denn das Schwert des einen soll den anderen fressen; aber zuletzt soll er selbst durch das Schwert fallen.',
'Und da du zwei Federn unter den Flügeln sahst, die über den Kopf gingen, der auf der rechten Seite war;',
'bedeutet es, daß diese diejenigen sind, die der Allerhöchste bis ans Ende aufbewahrt hat: dies ist das kleine Königreich, voll Unruhes, wie du sahst.',
'Und der Löwe, den du aus dem Walde aufsteigen, brüllen und mit dem Adler reden sahst, und der ihn seiner Ungerechtigkeit mit all den Worten, die du gehört hast, schalt:',
'das ist der Gesalbte, den der Allerhöchste für sie und ihre Gottlosigkeit bis ans Ende aufbewahrt hat; er soll sie strafen und ihnen ihre Grausamkeit vorwerfen.',
'Denn er soll sie lebend vor sein Gericht stellen und sie strafen und zurechtweisen.',
'Denn den Rest meines Volkes soll er mit Barmherzigkeit erretten, die auf meine Grenzen hin gedrückt wurden, und er soll sie fröhlich machen bis zur Ankunft des Gerichtstages, von dem ich dir vom Anfang geredet habe.',
'Dies ist der Traum, den du gesehen hast, und dies sind die Auslegungen.',
'Du allein bist würdig gewesen, dieses Geheimnis des Allerhöchsten zu wissen.',
'Darum schreibe alle diese Dinge, die du gesehen hast, in ein Buch und verbirg sie:',
'und lehre sie die Weisen unter dem Volk, deren Herzen du kennst, die diese Geheimnisse fassen und bewahren können.',
'Aber warte du hier selbst noch sieben Tage, damit dir gezeigt werde, was auch immer es dem Allerhöchsten beliebt, dir zu offenbaren. Und damit ging er seines Weges.',
'Und es begab sich, als alles Volk sah, daß die sieben Tage vergangen waren und ich nicht in die Stadt zurückgekehrt war, kamen sie alle zusammen, vom Geringsten bis zum Größten, und kamen zu mir und sprachen:',
'Womit haben wir dich beleidigt? und was Böses haben wir gegen dich getan, daß du uns verlässest und an diesem Ort sitzest?',
'Denn von allen Propheten bist du uns allein übrig, wie eine Traube der Weinlese und wie ein Licht an einem finsteren Ort und wie ein Hafen oder Schiff, das vor dem Sturm bewahrt ist.',
'Sind nicht die Übel, die uns widerfahren sind, genug?',
'Wenn du uns verlässest, wieviel besser wäre es für uns gewesen, wenn auch wir mitten in Zion verbrannt wären?',
'Denn wir sind nicht besser als die, die dort starben. Und sie weinten mit lauter Stimme. Da antwortete ich ihnen und sprach:',
'Seid getrost, o Israel; und sei nicht schwer, du Haus Jakob:',
'denn der Allerhöchste hält euch im Gedächtnis, und der Mächtige hat euch in der Versuchung nicht vergessen.',
'Was mich betrifft, ich habe euch nicht verlassen und bin nicht von euch gegangen; sondern bin an diesen Ort gegangen, um für die Verwüstung Zions zu beten und Erbarmen für den niedrigen Stand eures Heiligtums zu suchen.',
'Und nun gehet jeder Mann nach Hause, und nach diesen Tagen werde ich zu euch kommen.',
'So ging das Volk in die Stadt, wie ich ihnen befohlen hatte:',
'ich aber blieb noch sieben Tage auf dem Feld, wie der Engel mir befohlen hatte; und ich aß in jenen Tagen nur von den Blumen des Feldes, und hatte meine Nahrung von den Kräutern.'
];

const out = JSON.parse(fs.readFileSync(__dirname+'/tmp_b75_b.json','utf8'));
[ch9, ch10, ch11, ch12].forEach((verses, i) => {
  const cn = i+9;
  const vv = {};
  verses.forEach((t,j)=>{ vv[j+1]={verse:j+1,text:t}; });
  out.chapters[cn] = {chapter:cn, name:'', verses:vv};
});

fs.writeFileSync(__dirname+'/tmp_b75_c.json', JSON.stringify(out), 'utf8');
const total = [ch9,ch10,ch11,ch12].reduce((s,c)=>s+c.length,0);
console.log('Batch C fertig: Kapitel 9-12, '+total+' Verse');
