const fs = require('fs');
const BASE = __dirname + '/data-orthodox/german/';

const ch1 = [
'Josias hielt das Passahfest in Jerusalem seinem Herrn und opferte das Passah am vierzehnten Tage des ersten Monats,',
'nachdem er die Priester ihren täglichen Ordnungen gemäß in langen Gewändern im Tempel des Herrn aufgestellt hatte.',
'Und er sprach zu den Leviten, den heiligen Dienern Israels, daß sie sich dem Herrn heiligen sollten, um die heilige Lade des Herrn in das Haus zu setzen, das Salomo, der Sohn des Königs David, gebaut hatte.',
'Und sprach: Ihr sollt die Lade nicht mehr auf euren Schultern tragen; nun dienet dem Herrn, eurem Gott, und seinem Volk Israel und bereitet euch nach euren Geschlechtern und Familien,',
'so wie David, der König Israels, es verordnet hatte, und nach der Herrlichkeit seines Sohnes Salomo; und stehet im Tempel nach der besonderen Würde eurer Familien, ihr Leviten, die ihr im Angesicht eurer Brüder, der Kinder Israels, dient,',
'opfert das Passah der Reihe nach und bereitet die Opfer für eure Brüder und haltet das Passah nach dem Gebot des Herrn, das durch Mose gegeben ward.',
'Und dem Volk, das da zugegen war, gab Josias dreißigtausend Lämmer und Böcke und dreitausend Kälber; diese Dinge wurden aus dem Schatz des Königs gegeben, wie er dem Volk, den Priestern und Leviten versprochen hatte.',
'Und Helkia, Sacharja und Syelus, die Vorsteher des Tempels, gaben den Priestern für das Passah zweitausendsechshundert Schafe und dreihundert Kälber.',
'Und Jechonia, Samaias und Nathanael, sein Bruder, und Assabias und Ochiel und Joram, Hauptleute über tausend, gaben den Leviten für das Passah fünftausend Schafe und siebenhundert Kälber.',
'Und als dies geschehen war, standen die Priester und Leviten mit dem ungesäuerten Brot in schöner Ordnung nach Geschlechtern',
'und nach den besonderen Würden der Väter vor dem Volk, dem Herrn zu opfern, wie es im Buch Moses geschrieben steht; und so taten sie am Morgen.',
'Und sie rösteten das Passah mit Feuer, wie es sich gehört; die Opfer aber kochten sie in Messingtöpfen und Pfannen mit gutem Geruch',
'und setzten sie vor allem Volk; danach bereiteten sie für sich selbst und für die Priester, ihre Brüder, die Söhne Aarons.',
'Denn die Priester opferten das Fett bis in die Nacht; und die Leviten bereiteten für sich selbst und für die Priester, ihre Brüder, die Söhne Aarons.',
'Die heiligen Sänger auch, die Söhne Asaphs, standen nach ihrer Ordnung, nach der Anordnung Davids: Asaph, Sacharja und Jeduthun, der des Königs Hofstaat zugehörte.',
'Auch die Torhüter standen an jedem Tor; es war keinem erlaubt, von seinem gewöhnlichen Dienst abzuweichen; denn ihre Brüder, die Leviten, bereiteten für sie.',
'So wurden die Dinge, die zu den Opfern des Herrn gehörten, an jenem Tage vollbracht, damit sie das Passah halten',
'und Opfer auf dem Altar des Herrn darbringen könnten, nach dem Gebot des Königs Josias.',
'So hielten die Kinder Israels, die zugegen waren, zu jener Zeit das Passah und das Fest der süßen Brote sieben Tage.',
'Ein solches Passah war in Israel nicht gehalten worden seit den Tagen des Propheten Samuel.',
'Ja, alle Könige Israels hatten kein solches Passah gehalten wie Josias und die Priester und die Leviten und die Juden mit ganz Israel, das zu Jerusalem wohnhaft gefunden ward.',
'Im achtzehnten Jahr der Regierung Josias wurde dieses Passah gehalten.',
'Und die Werke Josias waren aufrecht vor seinem Herrn mit einem Herzen voll Gottesfurcht.',
'Was aber in seiner Zeit geschah, das ist von früheren Zeiten her aufgeschrieben über die, die sündigten und übel handelten wider den Herrn über alle Völker und Königreiche, und wie sie ihn über die Maßen betrübten, so daß sich das Wort des Herrn wider Israel erhob.',
'Nun aber, nach all diesen Taten Josias, geschah es, daß Pharao, der König Ägyptens, heraufzog, einen Krieg an Karchamis am Euphrat zu führen; und Josias zog ihm entgegen.',
'Der König von Ägypten aber sandte zu ihm und sprach: Was habe ich mit dir zu schaffen, König von Judäa?',
'Ich bin nicht vom Herrn, meinem Gott, wider dich gesandt; denn mein Krieg ist am Euphrat; und nun ist der Herr mit mir, ja der Herr mit mir treibt mich an: weiche von mir und widersetze dich nicht dem Herrn.',
'Aber Josias wandte seinen Streitwagen nicht von ihm und suchte ihn zu bekämpfen, ohne die Worte zu beachten, die der Prophet Jeremia aus dem Munde des Herrn gesprochen hatte.',
'Und er lieferte ihm eine Schlacht in der Ebene von Megiddo, und die Fürsten fielen über König Josias her.',
'Da sprach der König zu seinen Knechten: Bringet mich aus der Schlacht; denn ich bin sehr schwach. Und alsbald brachten ihn seine Knechte aus der Schlacht.',
'Da stieg er auf seinen zweiten Wagen; und als er nach Jerusalem zurückgebracht wurde, starb er und wurde im Grabe seiner Väter begraben.',
'Und in ganz Judäa trauerten sie um Josias; ja der Prophet Jeremia klagte um Josias, und die Vornehmen mit den Frauen hielten Klage um ihn bis auf diesen Tag; und dies ward als Verordnung gegeben, daß es stets in ganz Israel gehalten werden sollte.',
'Diese Dinge sind im Buch der Geschichten der Könige Judas geschrieben, und alles, was Josias getan hat, und seine Herrlichkeit und sein Verständnis im Gesetz des Herrn und die Dinge, die er vorher getan hat und diese jetzigen, sind im Buch der Könige Israels und Judas berichtet.',
'Und das Volk nahm Joachaz, den Sohn Josias, und machte ihn zum König anstelle seines Vaters Josias, als er dreiundzwanzig Jahre alt war.',
'Und er regierte in Judäa und in Jerusalem drei Monate; und dann setzte ihn der König von Ägypten von der Regierung in Jerusalem ab.',
'Und er legte dem Land eine Steuer auf von hundert Talenten Silber und einem Talent Gold.',
'Der König von Ägypten machte auch Joakim, seinen Bruder, zum König über Judäa und Jerusalem.',
'Und er band Joakim und die Vornehmsten; aber seinen Bruder Sarakes ergriff er und brachte ihn aus Ägypten.',
'Fünfundzwanzig Jahre alt war Joakim, als er König wurde im Land Judäa und Jerusalem; und er tat Böses vor dem Herrn.',
'Daher zog Nebukadnezar, der König von Babel, gegen ihn herauf und band ihn mit einer ehernen Kette und führte ihn weg nach Babel.',
'Nebukadnezar nahm auch die heiligen Gefäße des Herrn und führte sie weg und stellte sie in seinem Tempel zu Babel auf.',
'Aber was von ihm aufgezeichnet ist, von seiner Unreinheit und Gottlosigkeit, das steht in den Jahrbüchern der Könige geschrieben.',
'Und Joakim, sein Sohn, regierte an seiner Statt; als er König wurde, war er achtzehn Jahre alt;',
'und er regierte nur drei Monate und zehn Tage in Jerusalem; und tat Böses vor dem Herrn.',
'So schickte Nebukadnezar nach einem Jahr und ließ ihn nach Babel bringen mit den heiligen Gefäßen des Herrn;',
'und machte Zedekia zum König über Judäa und Jerusalem, als er einundzwanzig Jahre alt war; und er regierte elf Jahre:',
'Und er tat auch Böses vor dem Herrn und achtete nicht auf die Worte, die der Prophet Jeremia aus dem Munde des Herrn zu ihm sprach.',
'Und nachdem ihn König Nebukadnezar bei dem Namen des Herrn hatte schwören lassen, war er treulos und rebellierte; und indem er seinen Hals und sein Herz verhärtete, übertrat er die Gesetze des Herrn, des Gottes Israels.',
'Auch die Vorsteher des Volkes und der Priester taten vieles wider die Gesetze und übertrafen alle Greuel aller Völker und entweihten den Tempel des Herrn, der in Jerusalem geheiligt war.',
'Aber der Gott ihrer Väter sandte durch seinen Boten, sie zurückzurufen, weil er sie und seine Wohnstätte schonte.',
'Aber sie verspotteten seine Boten; und als der Herr zu ihnen redete, trieben sie Spott mit seinen Propheten:',
'So sehr, daß er, über sein Volk um ihrer großen Gottlosigkeit willen ergrimmt, den Königen der Chaldäer gebot, gegen sie herzuziehen;',
'die erschlugen ihre jungen Männer mit dem Schwert, ja selbst innerhalb des Bereichs ihres heiligen Tempels, und schonten weder jungen Mann noch Maid, weder Greis noch Kind unter ihnen; denn er gab alle in ihre Hände.',
'Und sie nahmen alle heiligen Gefäße des Herrn, sowohl die großen als die kleinen, mit den Gefäßen der Lade Gottes und den Schätzen des Königs, und führten sie nach Babel.',
'Das Haus des Herrn aber verbrannten sie und brachen die Mauern Jerusalems nieder und zündeten ihre Türme an.',
'Und was an herrlichen Dingen war, das hörten sie nicht auf zu zerstören, bis sie alles vernichtet und zu nichte gemacht hatten; und das Volk, das nicht mit dem Schwert getötet ward, führten sie nach Babel;',
'und sie wurden ihm und seinen Kindern Knechte, bis die Perser regierten, um das Wort des Herrn zu erfüllen, das durch den Mund Jeremias gesprochen war:',
'bis das Land seine Sabbate genoß; die ganze Zeit ihrer Verwüstung soll sie ruhen, bis das volle Maß von siebzig Jahren erfüllt ist.'
];

const ch2 = [
'Im ersten Jahr des Kyrus, des Königs der Perser, auf daß das Wort des Herrn erfüllt würde, das er durch den Mund Jeremias geredet hatte,',
'erweckte der Herr den Geist des Kyrus, des Königs der Perser, und er ließ durch sein ganzes Königreich ausrufen und auch schriftlich verkündigen:',
'So spricht Kyrus, der König der Perser: Der Herr Israels, der höchste Herr, hat mich zum König der ganzen Welt gemacht',
'und hat mir befohlen, ihm ein Haus zu Jerusalem in Judäa zu bauen.',
'Wenn nun jemand unter euch ist von seinem Volk, so sei der Herr, sein Gott, mit ihm, und er ziehe auf gen Jerusalem, das in Judäa liegt, und baue das Haus des Herrn Israels; denn er ist der Herr, der zu Jerusalem wohnt.',
'Und alle, die in der Umgebung wohnen, sollen ihm helfen, die ich meine, die seine Nachbarn sind, mit Gold und mit Silber,',
'mit Geschenken, mit Pferden und mit Vieh und anderem Gut, das zu Ehren des Tempels des Herrn zu Jerusalem als Gelübde dargebracht worden ist.',
'Da machten sich die Häupter der Geschlechter Judas und des Stammes Benjamin auf; die Priester auch und die Leviten und alle, deren Geist der Herr erregt hatte, um hinaufzuziehen und dem Herrn ein Haus zu Jerusalem zu bauen,',
'und die rings um sie wohnten und ihnen in allem halfen mit Silber und Gold, mit Pferden und Vieh und sehr vielen freiwilligen Gaben einer großen Zahl derer, deren Sinn dazu angeregt worden war.',
'König Kyrus brachte auch die heiligen Gefäße heraus, die Nebukadnezar aus Jerusalem weggeführt und in seinem Göttertempel aufgestellt hatte.',
'Und als Kyrus, der König der Perser, sie herausgebracht hatte, übergab er sie seinem Schatzmeister Mithridates;',
'und durch diesen wurden sie dem Statthalter von Judäa, Sanabassar, ausgehändigt.',
'Und das war ihre Zahl: tausend goldene Becher und tausend silberne, neunundzwanzig silberne Weihrauchgefäße, dreißig goldene Schalen und zweitausendvierhundertzehn silberne und tausend andere Gefäße.',
'So betrugen alle Gefäße von Gold und Silber, die weggeführt worden waren, fünftausendfourhundertneunundsechzig.',
'Diese wurden durch Sanabassar zusammen mit denen aus der Gefangenschaft von Babel nach Jerusalem gebracht.',
'Aber zur Zeit des Artaxerxes, des Königs der Perser, schrieben Belemus und Mithridates und Tabellius und Rathum und Beeltethmus und Semellius, der Schreiber, mit anderen, die in ihrem Auftrag handelten und in Samaria und anderen Orten wohnten, an ihn wider die in Judäa und Jerusalem Wohnenden folgende Briefe:',
'An den König Artaxerxes, unsern Herrn: deine Knechte Rathum, der Berichtschreiber, und Semellius, der Schreiber, und die übrigen ihres Rates und die Richter in Cölesyrien und Phönizien.',
'Sei es nun dem Herrn König bekannt, daß die Juden, die von dir zu uns heraufgekommen sind und nach Jerusalem gelangt sind, diese aufständische und böse Stadt bauen und ihre Märkte wiederherstellen und die Grundmauern des Tempels legen.',
'Wenn nun diese Stadt und ihre Mauern wieder aufgebaut werden, so werden sie nicht nur den Zoll verweigern, sondern auch gegen die Könige rebellieren.',
'Da nun die Arbeiten am Tempel in Angriff genommen sind, halten wir es für angebracht, eine solche Sache nicht zu vernachlässigen,',
'sondern unserem Herrn dem König zu schreiben, damit, wenn es ihm gefällig ist, in den Büchern deiner Väter nachgesucht werden möge:',
'und du wirst in den Jahrbüchern finden, was über diese Dinge geschrieben steht, und wirst verstehen, daß diese Stadt von Alters her aufständisch war und Könige und Städte beunruhigte;',
'und daß die Juden rebellisch waren und darin immer wieder Kriege anzettelten; aus diesem Grund wurde auch diese Stadt zerstört.',
'Daher machen wir dir, Herr König, bekannt, daß wenn diese Stadt wieder aufgebaut und ihre Mauern erneuert werden, du von nun an keinen Durchgang in Cölesyrien und Phönizien haben wirst.',
'Da schrieb der König zurück an Rathum, den Berichtschreiber, und Beeltethmus und Semellius, den Schreiber, und die übrigen, die in ihrem Auftrag handelten und in Samaria und Syrien und Phönizien wohnten, auf diese Weise:',
'Ich habe den Brief gelesen, den ihr mir geschickt habt; daher habe ich befohlen, sorgfältig nachzuforschen, und es wurde gefunden, daß diese Stadt von Anfang an gegen Könige Anschläge gemacht hat;',
'und die Männer darin waren zu Aufruhr und Krieg geneigt; und mächtige und kühne Könige waren in Jerusalem, die in Cölesyrien und Phönizien regierten und Steuern erhoben.',
'Nun also habe ich befohlen, diese Männer am Bau der Stadt zu hindern, und daß dafür gesorgt werde, daß dort nichts weiter geschehe;',
'und daß diese bösen Arbeiter nicht fortfahren, den Königen Schaden zuzufügen.',
'Als dann die Briefe des Königs Artaxerxes gelesen worden waren, zogen Rathum und Semellius, der Schreiber, und die übrigen, die in ihrem Auftrag handelten, eilends nach Jerusalem mit einer Schar Reiter und einer Menge Volkes in Schlachtordnung und begannen, die Bauleute zu hindern; und der Bau des Tempels zu Jerusalem hörte auf bis zum zweiten Jahr der Regierung des Darius, des Königs der Perser.'
];

const ch3 = [
'Als nun Darius regierte, machte er ein großes Gastmahl für alle seine Untertanen, für sein ganzes Haus und für alle Fürsten der Meder und Perser,',
'und für alle Statthalter und Hauptleute und Leutnants, die unter ihm standen, von Indien bis nach Äthiopien, der hundertsiebenundzwanzig Provinzen.',
'Und nachdem sie gegessen und getrunken hatten und satt heimgegangen waren, ging Darius, der König, in seine Schlafkammer, schlief und erwachte bald darauf.',
'Da sprachen drei junge Männer, die zur Leibwache des Königs gehörten, einer zum andern:',
'Laßt jeden von uns einen Spruch tun; wer siegt und dessen Spruch weiser scheint als die der anderen, dem soll König Darius große Geschenke und große Ehrungen geben:',
'nämlich in Purpur gekleidet zu werden, in Gold zu trinken, auf Gold zu schlafen, und einen Streitwagen mit goldenen Zügeln und ein Kopftuch aus feinem Leinen und eine Kette um den Hals:',
'und er soll wegen seiner Weisheit neben Darius sitzen und Darius\' Verwandter genannt werden.',
'Und dann schrieb jeder seinen Spruch, versiegelte ihn und legte ihn unter das Kopfkissen des Königs Darius;',
'und sagten, daß wenn der König aufgestanden sei, man ihm die Schriften geben solle; und von welcher Seite der König und die drei Fürsten Persiens urteilen, daß sein Spruch der weiseste sei, dem solle der Sieg gegeben werden, wie es verabredet worden war.',
'Der erste schrieb: Der Wein ist am stärksten.',
'Der zweite schrieb: Der König ist am stärksten.',
'Der dritte schrieb: Die Frauen sind am stärksten; aber über alle Dinge trägt die Wahrheit den Sieg davon.',
'Als nun der König aufgestanden war, nahmen sie ihre Schriften und überreichten sie ihm, und er las sie;',
'und er sandte aus und berief alle Fürsten der Perser und Meder und die Statthalter und Hauptleute und Leutnants und die obersten Beamten;',
'und setzte sich auf den königlichen Richterstuhl; und die Schriften wurden vor ihnen gelesen.',
'Und er sprach: Rufet die jungen Männer, und sie sollen ihre eigenen Sprüche erklären. So wurden sie gerufen, und sie traten ein.',
'Und er sprach zu ihnen: Erkläret uns eure Meinung über die Schriften. Da begann der erste, der über die Stärke des Weines geredet hatte;',
'und er sprach also: O ihr Männer, wie überaus stark ist der Wein! Er bringt alle, die von ihm trinken, zum Irren:',
'er macht den Sinn des Königs und des vaterlosen Kindes gleich; des Sklaven und des Freien, des Armen und des Reichen:',
'er wandelt auch jeden Gedanken in Lust und Freude, so daß ein Mensch weder Kummer noch Schuld mehr erinnert:',
'und er macht jedes Herz reich, so daß ein Mensch weder König noch Statthalter mehr erinnert; und er bringt alle Dinge mit Talent zum Reden:',
'und wenn sie in ihren Bechern trinken, vergessen sie ihre Liebe zu Freunden und Brüdern und ziehen kurz danach Schwerter;',
'aber wenn sie vom Wein weg sind, erinnern sie sich nicht, was sie getan haben.',
'O ihr Männer, ist nicht der Wein der stärkste, der so zu tun zwingt? Und als er so gesprochen hatte, schwieg er.'
];

const ch4 = [
'Da begann der zweite, der von der Stärke des Königs geredet hatte, zu sagen:',
'O ihr Männer, übertreffen nicht die Menschen an Kraft, die über See und Land und alle Dinge darin herrschen?',
'Aber doch ist der König mächtiger: denn er ist Herr über all dieses und hat Gewalt über sie; und was auch immer er ihnen befiehlt, das tun sie.',
'Wenn er sie befiehlt, einen Krieg gegeneinander zu führen, so tun sie es; wenn er sie gegen die Feinde ausschickt, so gehen sie und durchbrechen Berge, Mauern und Türme.',
'Sie töten und werden getötet, und übertreten des Königs Gebot nicht: wenn sie den Sieg erringen, bringen sie alles dem König, sowohl die Beute als auch alles andere.',
'Ebenso auch die, welche keine Soldaten sind und nicht mit Kriegen zu tun haben, sondern Ackerbau treiben: wenn sie wieder geerntet haben, was sie gesät haben, bringen sie es dem König und zwingen einander, dem König Zins zu zahlen.',
'Und er ist doch nur ein einziger Mensch: wenn er befiehlt zu töten, so töten sie; wenn er befiehlt zu schonen, so schonen sie;',
'wenn er befiehlt zu schlagen, so schlagen sie; wenn er befiehlt zu verwüsten, so verwüsten sie; wenn er befiehlt zu bauen, so bauen sie;',
'wenn er befiehlt zu fällen, so fällen sie; wenn er befiehlt zu pflanzen, so pflanzen sie.',
'So gehorchen ihm sein ganzes Volk und seine Heere; überdies liegt er nieder, er ißt und trinkt und nimmt seine Ruhe:',
'und diese halten rings um ihn Wacht, und keiner darf sich entfernen und sein eigenes Geschäft tun; noch gehorchen sie ihm in irgendeiner Sache nicht.',
'O ihr Männer, wie sollte der König nicht der mächtigste sein, da er auf solche Weise gehorcht wird? Und er hielt inne.',
'Da begann der dritte, der von den Frauen und von der Wahrheit gesprochen hatte (das war Zorobabel):',
'O ihr Männer, nicht der große König, noch die Menge der Menschen, noch der Wein übertrifft; wer ist es denn, der über sie herrscht oder die Oberherrschaft über sie hat? Sind es nicht die Frauen?',
'Frauen haben den König und alles Volk geboren, das über See und Land regiert.',
'Von ihnen kamen diese; und sie nährten jene auf, die die Weinberge pflanzten, aus welchen der Wein kommt.',
'Diese machen auch die Kleider der Männer; diese bringen den Männern Herrlichkeit; und ohne Frauen können Männer nicht sein.',
'Ja, und wenn Männer Gold und Silber oder irgendein anderes schönes Ding gesammelt haben, lieben sie da nicht eine Frau, die in Gestalt und Schönheit anmutig ist?',
'Und lassen sie all jene Dinge fahren und sperren sie nicht den Mund auf und richten die Augen fest auf sie; und haben nicht alle Männer mehr Verlangen nach ihr als nach Silber oder Gold oder irgendwelchen schönen Dingen?',
'Ein Mann verläßt seinen eigenen Vater, der ihn aufgezogen hat, und sein eigenes Land und hängt an seiner Frau.',
'Er schrickt nicht davor zurück, sein Leben mit seiner Frau zu verbringen, und erinnert sich weder an Vater noch Mutter noch an sein Land.',
'Darum müßt ihr auch wissen, daß die Frauen Gewalt über euch haben: arbeitet und müht ihr euch nicht und gebt und bringt ihr alles der Frau?',
'Ja, ein Mann nimmt sein Schwert und geht seinen Weg, zu rauben und zu stehlen, zu segeln auf dem Meer und auf Flüssen;',
'und schaut einem Löwen ins Angesicht und geht in der Dunkelheit; und wenn er gestohlen, geplündert und geraubt hat, bringt er es seiner Geliebten.',
'Daher liebt ein Mann seine Frau mehr als Vater oder Mutter.',
'Ja, viele sind um der Frauen willen von Sinnen gegangen und um ihretwillen Knechte geworden.',
'Viele auch sind umgekommen, haben sich vergangen und gesündigt um der Frauen willen.',
'Und glaubt ihr mir nun nicht? Ist nicht der König groß in seiner Macht? Fürchten nicht alle Gebiete, ihn anzurühren?',
'Und doch sah ich ihn und Apame, die Beischläferin des Königs, die Tochter des wunderbaren Bartakus, zur Rechten des Königs sitzen,',
'und die Krone vom Kopf des Königs nehmen und auf ihren eigenen setzen; sie schlug auch den König mit ihrer linken Hand.',
'Und doch gaffte und starrte der König mit offenem Mund auf sie: wenn sie ihn anlachte, lachte er auch; wenn sie aber irgendeine Ungnade gegen ihn hatte, mußte der König schmeicheln, damit sie wieder mit ihm versöhnt würde.',
'O ihr Männer, wie kann es anders sein, als daß die Frauen stark sind, da sie so handeln?',
'Da sahen der König und die Fürsten einander an: und da begann er über die Wahrheit zu reden.',
'O ihr Männer, sind nicht die Frauen stark? Groß ist die Erde, hoch ist der Himmel, schnell ist die Sonne in ihrem Lauf; denn sie umkreist die Himmel ringsum und holt ihren Lauf an ihrem eigenen Ort in einem Tage wieder ein.',
'Ist er nicht groß, der diese Dinge macht? Deshalb ist die Wahrheit groß und stärker als alle Dinge.',
'Die ganze Erde ruft die Wahrheit an, und der Himmel segnet sie: alle Werke zittern und beben vor ihr, und mit ihr ist keine Ungerechtigkeit.',
'Der Wein ist böse, der König ist böse, die Frauen sind böse, alle Kinder der Menschen sind böse und so sind alle ihre bösen Werke; und keine Wahrheit ist in ihnen; in ihrer Ungerechtigkeit werden sie auch verderben.',
'Was aber die Wahrheit betrifft, sie besteht und ist allezeit stark; sie lebt und herrscht in Ewigkeit.',
'Bei ihr gibt es keine Annahme von Personen oder Belohnungen; sondern sie tut, was gerecht ist, und enthält sich allem Ungerechten und Bösen; und alle Menschen gefallen sich an ihren Werken.',
'Auch in ihrem Gericht ist keine Ungerechtigkeit; und sie ist die Kraft, das Königreich, die Macht und die Majestät aller Zeiten. Gelobt sei der Gott der Wahrheit!',
'Und damit schwieg er. Und da schrien alle Leute und sagten: Groß ist die Wahrheit und mächtiger als alles!',
'Da sagte der König zu ihm: Bitte, was du willst, mehr als was im Schreiben bestimmt ist, und wir werden es dir geben; denn du bist als der Weiseste befunden worden; und du sollst neben mir sitzen und mein Verwandter genannt werden.',
'Da sagte er zum König: Gedenke deines Gelübdes, das du gelobt hast, Jerusalem zu bauen an dem Tage, da du zur Königswürde kamst,',
'und alle Gefäße wegzuschicken, die aus Jerusalem weggenommen wurden, die Kyrus beiseitegelegt hatte, als er Babel zu zerstören gelobte, und sie dorthin zurückzuschicken.',
'Du hast auch gelobt, den Tempel wieder aufzubauen, den die Idumäer verbrannt haben, als Judäa durch die Chaldäer verwüstet wurde.',
'Und nun, Herr König, das ist es, was ich fordere und begehre von dir, und das ist die königliche Großmut, die von dir selbst ausgeht: Ich bitte dich also, daß du dein Gelübde einlösest, dessen Erfüllung du mit deinem eigenen Munde dem König des Himmels gelobt hast.',
'Da stand Darius, der König, auf und küßte ihn und schrieb Briefe für ihn an alle Schatzmeister und Statthalter und Hauptleute und Gouverneure, daß sie ihn und alle, die mit ihm hinaufziehen, um Jerusalem zu bauen, sicher geleiten sollten.',
'Er schrieb auch Briefe an die Statthalter in Cölesyrien und Phönizien und an die im Libanon, daß sie Zedernholz vom Libanon nach Jerusalem bringen sollten und daß sie die Stadt mit ihm bauen sollten.',
'Er schrieb auch für alle Juden, die aus seinem Reich nach Judäa hinaufzogen, ihre Freiheit betreffend, daß kein Beamter, kein Herrscher, kein Leutnant und kein Schatzmeister ihre Türen mit Gewalt betreten solle;',
'und daß das ganze Land, das sie besitzen, steuerfrei sein solle; und daß die Idumäer die Dörfer der Juden abgeben sollten, die sie damals besaßen:',
'ja, daß jährlich zwanzig Talente für den Bau des Tempels gegeben werden sollten, bis er fertig gebaut sei;',
'und weitere zehn Talente jährlich zur Unterhaltung der Brandopfer auf dem Altar an jedem Tage, wie ihnen geboten war, siebzehn darzubringen;',
'und daß alle, die von Babel hinaufziehen, um die Stadt zu bauen, freie Freiheit haben sollten, sowohl sie als auch ihre Nachkommen und alle Priester, die weggezogen waren.',
'Er schrieb auch über die Aufwendungen und die Priesterkleider, in denen sie dienen;',
'und ebenso für die Aufwendungen der Leviten, ihnen zu geben, bis das Haus fertig und Jerusalem aufgebaut sei.',
'Und er befahl, allen, die die Stadt bewachten, Pensionen und Lohn zu geben.',
'Er schickte auch alle Gefäße aus Babel zurück, die Kyrus beiseitegelegt hatte; und alles, was Kyrus in Auftrag gegeben hatte, das hieß er auch tun und nach Jerusalem senden.',
'Als dieser junge Mann hinausgegangen war, hob er sein Angesicht zum Himmel gen Jerusalem und pries den König des Himmels',
'und sprach: Von dir kommt der Sieg, von dir kommt die Weisheit, und dein ist die Herrlichkeit, und ich bin dein Knecht.',
'Gelobt seist du, der du mir Weisheit gegeben hast; denn dir sage ich Dank, Herr unserer Väter.',
'Und so nahm er die Briefe und zog aus und kam nach Babel und erzählte es allen seinen Brüdern.',
'Und sie lobten den Gott ihrer Väter, weil er ihnen Freiheit und Erlösung gegeben hatte,',
'hinauszuziehen und Jerusalem und den Tempel, der nach seinem Namen genannt wird, aufzubauen: und sie feierten sieben Tage lang mit Musikinstrumenten und Freude.'
];

const ch5 = [
'Danach wurden die Hauptleute der Geschlechter nach ihren Stämmen ausgewählt, um mit ihren Frauen und Söhnen und Töchtern, mit ihren Knechten und Mägden und ihrem Vieh hinaufzuziehen.',
'Darius aber schickte mit ihnen tausend Reiter, bis sie die Gefangenen sicher nach Jerusalem geleitet hatten, mit Musikinstrumenten, Pauken und Flöten.',
'Und alle ihre Brüder spielten, und er ließ sie alle zusammen hinaufziehen.',
'Und das sind die Namen der Männer, die hinaufzogen, nach ihren Geschlechtern unter ihren Stämmen, nach ihren besonderen Häuptern.',
'Die Priester, die Söhne des Phinees, des Sohnes Aarons: Jesus, der Sohn des Josedech, des Sohnes Sarajas, und Joakim, der Sohn Zorobabels, des Sohnes Sealthiels, vom Hause Davids, vom Geschlecht des Phares, vom Stamme Juda;',
'der in Weisheit sprach vor Darius, dem König der Perser, im zweiten Jahr seiner Regierung, im Monat Nisan, der der erste Monat ist.',
'Und das sind die von Judäa, die aus der Gefangenschaft heraufkamen, wo sie als Fremdlinge wohnten, die Nebukadnezar, der König von Babel, nach Babel weggeführt hatte.',
'Und sie kehrten nach Jerusalem und in die anderen Teile Judäas zurück, jeder in seine Stadt, die mit Zorobabel, Jesus, Nehemias, Sacharja, Reesaias, Enenius, Mardochai, Beelsarus, Aspharasus, Reelius, Roimus und Baana kamen, ihren Führern.',
'Die Zahl von ihnen aus dem Volk und ihren Vorstehern: die Söhne des Phoros, zweitausendeihhundertundzweiundsiebzig; die Söhne des Saphat, vierhundertundzweiundsiebzig:',
'die Söhne des Ares, siebenhundertundsechsundfünfzig:',
'die Söhne des Phaath-Moab, zweitausendachthundertundzwölf:',
'die Söhne des Elam, tausendundzweihundertundfünfundfünfzig: die Söhne des Sathul, neunhundertundvierundvierzig: die Söhne des Korbe, siebenhundertundfünf: die Söhne des Bani, sechshundertundachtundvierzig:',
'die Söhne des Bebai, sechshundertunddreiundzwanzig: die Söhne des Sadas, dreitausendundzweihundertundzweiundwanzig:',
'die Söhne des Adonikam, sechshundertundsiebenundsechzig: die Söhne des Bagoi, zweitausendundsechsundsechzig: die Söhne des Adin, vierhundertundvierundfünfzig:',
'die Söhne des Aterezias, zweiundneunzig: die Söhne des Ceilan und Asetas, siebenundsechzig: die Söhne des Asur, vierhundertundzweiundvierzig:',
'die Söhne des Ananias, einhundertundein: die Söhne des Arom, zweiunddreißig: und die Söhne des Bassa, dreihundertunddreiundzwanzig: die Söhne des Asephurith, einhundertundzwei:',
'die Söhne des Meterus, dreitausendundfünf: die Söhne des Bethlomon, einhundertunddreiundzwanzig:',
'die von Netopha, fünfundfünfzig: die von Anatoth, einhundertundachtundfünfzig: die von Bethsamos, zweiundvierzig:',
'die von Kiriath-Jarius, fünfundzwanzig: die von Kaphira und Beroth, siebenhundertdreiundvierzig: die von Pira, siebenhundert:',
'die von Chadias und Ammidoi, vierhundertundzweiundwanzig: die von Kirama und Gabdes, sechshunderteinundzwanzig:',
'die von Makalon, einhundertundzweiundwanzig: die von Betolius, zweiundvierzig: die Söhne des Nephis, einhundertundsechsundfünfzig:',
'die Söhne des Kalamolalus und Onus, siebenhundertundfünfundzwanzig: die Söhne des Jerichus, zweihundertundvierundvierzig:',
'die Söhne des Annas, dreitausendunddreihundertunddreißig.',
'Die Priester: die Söhne des Jeddu, des Sohnes Jesu, unter den Söhnen des Sanasib, neunhundertundzweiundsiebzig: die Söhne des Meruth, tausendundzweiundvierzig:',
'die Söhne des Phassaron, tausendundsiebenundvierzig: die Söhne des Karme, tausendundsiebzehn.',
'Die Leviten: die Söhne des Jessue und Kadmiel und Banuas und Sudias, vierundsiebzig.',
'Die heiligen Sänger: die Söhne des Asaph, einhundertundachtundzwanzig.',
'Die Torhüter: die Söhne des Salum, die Söhne des Jatal, die Söhne des Talmon, die Söhne des Dakobi, die Söhne des Teta, die Söhne des Sami, insgesamt einhundertundneununddreißig.',
'Die Diener des Tempels: die Söhne des Esau, die Söhne des Asipha, die Söhne des Tabath, die Söhne des Keras, die Söhne des Sud, die Söhne des Phalea, die Söhne des Labana, die Söhne des Graba,',
'die Söhne des Akua, die Söhne des Uta, die Söhne des Ketab, die Söhne des Agaba, die Söhne des Subai, die Söhne des Anan, die Söhne des Kathua, die Söhne des Gedur,',
'die Söhne des Airus, die Söhne des Daisan, die Söhne des Noeba, die Söhne des Chaseba, die Söhne des Gasera, die Söhne des Asia, die Söhne des Phinees, die Söhne des Asare, die Söhne des Bastai, die Söhne des Asana, die Söhne des Meani, die Söhne des Naphisi, die Söhne des Akub, die Söhne des Akipha, die Söhne des Assur, die Söhne des Pharakim, die Söhne des Basaloth,',
'die Söhne des Meeda, die Söhne des Kutha, die Söhne des Charea, die Söhne des Charkus, die Söhne des Aserer, die Söhne des Thomoi, die Söhne des Nasith, die Söhne des Atipha.',
'Die Söhne der Knechte Salomos: die Söhne des Asaphion, die Söhne des Pharira, die Söhne des Jeeli, die Söhne des Lozon, die Söhne des Israel, die Söhne des Sapheth,',
'die Söhne des Hagia, die Söhne des Pharakareth, die Söhne des Sabi, die Söhne des Sarothie, die Söhne des Masias, die Söhne des Gar, die Söhne des Addus, die Söhne des Suba, die Söhne des Apherra, die Söhne des Barodis, die Söhne des Sabat, die Söhne des Allom.',
'Alle Diener des Tempels und die Söhne der Knechte Salomos waren dreihundertundzweiundsiebzig.',
'Diese kamen von Thermeleth und Thelersas herauf; Charaathalar und Aalar führten sie an;',
'aber sie konnten weder ihre Geschlechter noch ihre Abstammung nachweisen, wie sie von Israel wären: die Söhne des Ladan, des Sohnes Ban, die Söhne des Nekodan, sechshundertundzweiundfünfzig.',
'Und von den Priestern, die das Priesteramt anmaßten und nicht aufgefunden wurden: die Söhne des Obdia, die Söhne des Akkos, die Söhne des Addus, der Augia geheiratet hatte, eine der Töchter Barsillais, und nach seinem Namen genannt worden war.',
'Und als die Beschreibung der Verwandtschaft dieser Männer im Register gesucht und nicht gefunden wurde, wurden sie von der Ausübung des Priesteramtes entfernt:',
'denn Nehemia und Atharia sagten zu ihnen, daß sie keinen Anteil an den heiligen Dingen haben sollten, bis ein Hoherpriester aufstehe, bekleidet mit Lehre und Wahrheit.',
'So waren von Israel, von denen, die zwölf Jahre und darüber alt waren, insgesamt vierzigtausend, außer Knechten und Mägden zweitausendunddreihundertundsechzig.',
'Ihre Knechte und Mägde waren siebentausenddreihundertundsiebenundvierzig: die singenden Männer und Frauen, zweihundertundvierundvierzig:',
'vierhundertfünfunddreißig Kamele, siebentausendsechsunddreißig Pferde, zweihundertundvierundvierzig Maultiere, fünftausendfünfhundertfünfundzwanzig Zugtiere.',
'Und einige der Hauptleute ihrer Geschlechter, als sie zum Hause Gottes kamen, das in Jerusalem ist, gelobten, das Haus wieder an seinem Ort aufzurichten nach ihrem Vermögen,',
'und in den heiligen Schatz der Werke tausend Pfund Gold, fünftausend Silber und hundert Priesterkleider einzulegen.',
'Und so wohnten die Priester und die Leviten und das Volk in Jerusalem und im Lande, die Sänger auch und die Torhüter; und ganz Israel in seinen Dörfern.',
'Als aber der siebte Monat herbeikam und als die Kinder Israels jeder an seinem Ort waren, kamen sie alle mit einem Sinn auf den freien Platz vor dem ersten Tor, das nach Osten liegt.',
'Da stand auf Jesus, der Sohn Josedechs, und seine Brüder, die Priester, und Zorobabel, der Sohn Sealthiels, und seine Brüder und richteten den Altar des Gottes Israels auf,',
'um darauf Brandopfer zu opfern, wie es ausdrücklich geboten ist in dem Buch Moses, des Mannes Gottes.',
'Und es versammelten sich zu ihnen aus den anderen Völkern des Landes; und sie errichteten den Altar auf seinem Platz, denn alle Völker des Landes waren ihnen feindlich gesonnen und unterdrückten sie; und sie opferten nach der Zeit und brachten dem Herrn Brandopfer, morgens und abends.',
'Auch hielten sie das Laubhüttenfest, wie es im Gesetz geboten ist, und brachten täglich Opfer, wie es sich gehörte:',
'und danach das ständige Opfer und das Opfer der Sabbate und der Neumonde und aller Feste.',
'Und alle, die irgendein Gelübde Gott gegenüber gemacht hatten, fingen an, Gott Opfer darzubringen von dem ersten Tage des siebten Monats an, obwohl der Tempel des Herrn noch nicht gebaut war.',
'Und sie gaben den Maurern und Zimmerleuten Geld, Speise und Trank mit Freude.',
'Den Sidoniern und Tyriern auch gaben sie Fuhrwerk, damit sie Zedernholz vom Libanon brächten, das zu Schiff bis zum Hafen Japho gebracht werden sollte, nach dem Befehl, den ihnen Kyrus, der König der Perser, gegeben hatte.',
'Im zweiten Jahr und zweiten Monat nach seiner Ankunft am Tempel Gottes zu Jerusalem begannen Zorobabel, der Sohn Sealthiels, und Jesus, der Sohn Josedechs, und ihre Brüder und die Priester und die Leviten und alle, die aus der Gefangenschaft nach Jerusalem gekommen waren;',
'und sie legten am ersten Tage des zweiten Monats, im zweiten Jahr nach ihrer Ankunft in Judäa und Jerusalem, den Grund des Hauses Gottes.',
'Und sie stellten die Leviten von zwanzig Jahren an über die Werke des Herrn. Da stand auf Jesus und seine Söhne und Brüder und Kadmiel, sein Bruder, und die Söhne Madiabus mit den Söhnen des Joda, des Sohnes Eliaduns, mit ihren Söhnen und Brüdern, alle Leviten, einmütig als Förderer des Werks; so bauten die Arbeiter den Tempel des Herrn.',
'Und die Priester standen in ihren Gewändern mit Musikinstrumenten und Trompeten; und die Leviten, die Söhne Asaphs, hatten Zimbeln,',
'sangen Lieder des Dankes und lobten den Herrn, nach der Anordnung des Königs David von Israel.',
'Und sie sangen mit lauter Stimme Lieder zum Lob des Herrn, denn seine Güte und Herrlichkeit ist in Ewigkeit in ganz Israel.',
'Und alles Volk blies Trompeten und schrie mit lauter Stimme, Lieder des Dankes zum Herrn singend für die Errichtung des Hauses des Herrn.',
'Auch von den Priestern und Leviten und von den Hauptleuten ihrer Geschlechter, die Ältesten, die das frühere Haus gesehen hatten, kamen weinend und mit lautem Klagen zu diesem Bau.',
'Aber viele mit Trompeten und Freude schrien mit lauter Stimme,',
'so daß die Trompeten nicht gehört werden konnten wegen des Weinens des Volkes: die Menge aber schrie wunderbar laut, so daß man es weit hörte.',
'Da die Feinde des Stammes Juda und Benjamin es hörten, kamen sie herzu, was dieser Lärm der Trompeten bedeute.',
'Und sie erkannten, daß die Gefangenen den Tempel dem Herrn, dem Gott Israels, bauten.',
'So gingen sie zu Zorobabel und Jesus und zu den Hauptleuten der Geschlechter und sagten zu ihnen: Wir wollen mit euch zusammen bauen.',
'Denn wir ebenso wie ihr gehorchen eurem Herrn und bringen ihm Opfer dar seit den Tagen Asbazareth, des Königs der Assyrer, der uns hierher gebracht hat.',
'Da sagten Zorobabel und Jesus und die Hauptleute der Geschlechter Israels zu ihnen: Es steht uns und euch nicht zu, zusammen ein Haus für den Herrn, unseren Gott, zu bauen.',
'Wir alleine werden dem Herrn Israels bauen, gemäß dem Befehl, den uns Kyrus, der König der Perser, gegeben hat.',
'Aber die Heiden des Landes lagen schwer auf den Bewohnern Judäas und hielten sie eng; sie hinderten ihren Bau,',
'und durch heimliche Anschläge und öffentliche Überredungen und Aufstände hinderten sie die Vollendung des Baus die ganze Zeit, da König Kyrus lebte: so waren sie für zwei Jahre am Bauen gehindert, bis zur Regierung des Darius.'
];

const ch6 = [
'Im zweiten Jahr der Regierung des Darius weissagten Aggäus und Sacharja, der Sohn Addos, die Propheten, den Juden in Judäa und Jerusalem im Namen des Herrn, des Gottes Israels, der über ihnen war.',
'Da standen auf Zorobabel, der Sohn Salatiels, und Jesus, der Sohn Josedechs, und begannen, das Haus des Herrn zu Jerusalem zu bauen; die Propheten des Herrn waren bei ihnen und halfen ihnen.',
'Zu derselben Zeit kamen zu ihnen Sisinnes, der Statthalter von Syrien und Phönizien, mit Sathrabuzanes und seinen Gefährten und sagten zu ihnen:',
'Von wessen Genehmigung baut ihr dieses Haus und dieses Dach und richtet all die anderen Dinge aus? und wer sind die Arbeiter, die diese Dinge ausführen?',
'Aber die Ältesten der Juden erlangten Gnade, weil der Herr die Gefangenschaft besucht hatte;',
'und sie wurden am Bauen nicht gehindert, bis daß Darius Meldung über sie gemacht und eine Antwort empfangen worden war.',
'Der Abschrift der Briefe, welche Sisinnes, der Statthalter von Syrien und Phönizien, und Sathrabuzanes mit ihren Gefährten, den Vorstehern in Syrien und Phönizien, schrieben und dem Darius sandten, war dieser: An den König Darius, Heil:',
'Alles sei unserem Herrn dem König bekannt, daß wir in das Land Judäa gekommen und in die Stadt Jerusalem eingetreten sind; wir fanden im Gebiete Judäas die Ältesten der Juden aus der Gefangenschaft,',
'die dem Herrn ein Haus bauten, groß und neu, von gehauenen und kostbaren Steinen, und das Holz bereits in die Wände eingelegt.',
'Und diese Werke werden mit großem Eifer getan, und das Werk gedeiht herrlich in ihren Händen, und mit aller Ehre und Sorgfalt wird es gemacht.',
'Da fragten wir diese Ältesten und sagten: Von wessen Befehl baut ihr dieses Haus und legt die Grundmauern dieser Werke?',
'Daher, um dir durch Schreiben Nachricht geben zu können, fragten wir sie, wer die Hauptleute des Werkes waren, und wir verlangten von ihnen die Namen ihrer Hauptleute schriftlich.',
'So gaben sie uns diese Antwort: Wir sind die Knechte des Herrn, der Himmel und Erde gemacht hat.',
'Und dieses Haus wurde vor vielen Jahren von einem großen und starken König Israels gebaut und vollendet.',
'Aber als unsere Väter Gott zum Zorn reizten und gegen den Herrn Israels sündigten, der im Himmel ist, gab er sie in die Gewalt Nebukadnezars, des Königs von Babel, des Chaldäers;',
'der riß das Haus nieder und verbrannte es und führte das Volk gefangen nach Babel.',
'Aber im ersten Jahr, da König Kyrus über das Land Babel regierte, schrieb Kyrus, der König, dieses Haus aufzubauen.',
'Und die heiligen Gefäße von Gold und Silber, die Nebukadnezar aus dem Hause zu Jerusalem weggenommen und in seinem Tempel aufgestellt hatte, die brachte Kyrus, der König, wieder aus dem Tempel zu Babel heraus, und sie wurden dem Zorobabel und dem Sanabassarus, dem Statthalter, übergeben,',
'mit dem Befehl, daß er diese Gefäße wegtragen und im Tempel zu Jerusalem aufstellen solle; und daß der Tempel des Herrn an seinem Ort gebaut werden solle.',
'Da legte derselbe Sanabassarus, als er hierherkam, die Grundmauern des Hauses des Herrn zu Jerusalem; und von der Zeit an bis jetzt wird noch daran gebaut, und es ist noch nicht ganz fertig.',
'Wenn es nun dem König gefällig ist, so möge man unter den Urkunden des Königs Kyrus nachsuchen:',
'und wenn gefunden wird, daß der Bau des Hauses des Herrn zu Jerusalem mit Einwilligung des Königs Kyrus geschehen ist, und wenn unser Herr der König so gesonnen ist, so möge er uns davon Nachricht geben.',
'Da befahl König Darius, in den Urkunden zu Babel nachzusuchen; und so wurde zu Ekbatana, dem Palast im Land Medien, eine Rolle gefunden, in der folgendes aufgezeichnet war:',
'Im ersten Jahr der Regierung des Königs Kyrus befahl König Kyrus, daß das Haus des Herrn zu Jerusalem wieder aufgebaut werden sollte, wo sie mit ständigem Feuer opfern;',
'dessen Höhe soll sechzig Ellen betragen und die Breite sechzig Ellen, mit drei Reihen aus gehauenen Steinen und einer Reihe neuen Holzes des Landes; und die Kosten sollen aus dem Hause des Königs Kyrus gegeben werden:',
'und daß die heiligen Gefäße des Hauses des Herrn, sowohl von Gold als von Silber, die Nebukadnezar aus dem Hause zu Jerusalem genommen und nach Babel gebracht hatte, dem Hause zu Jerusalem zurückgegeben und an ihren früheren Platz gestellt werden sollen.',
'Auch habe ich befohlen, daß Sisinnes, der Statthalter von Syrien und Phönizien, und Sathrabuzanes und ihre Gefährten und die als Vorsteher in Syrien und Phönizien gesetzt sind, sich des Ortes nicht annehmen, sondern Zorobabel, dem Knecht des Herrn und Statthalter von Judäa, und den Ältesten der Juden erlauben sollen, das Haus des Herrn an diesem Ort zu bauen.',
'Ich habe auch befohlen, daß es ganz wieder aufgebaut werde; und daß sie sorgfältig darauf achten sollen, denen zu helfen, die aus der Gefangenschaft der Juden sind, bis das Haus des Herrn fertiggestellt sei:',
'und aus dem Tribut von Cölesyrien und Phönizien soll diesen Männern ein Anteil sorgfältig für die Opfer des Herrn gegeben werden, das heißt Zorobabel, dem Statthalter, für Stiere und Widder und Lämmer;',
'und auch Getreide, Salz, Wein und Öl, und zwar ständig jedes Jahr ohne weitere Nachfrage, wie die Priester in Jerusalem angeben werden, was täglich ausgegeben wird:',
'damit dem höchsten Gott für den König und für seine Kinder Opfer dargebracht werden, und damit sie für ihr Leben beten.',
'Und er befahl, daß wer auch immer dem Vorgeschriebenen oder Geschriebenen zuwiderhandeln oder es gering achten sollte, aus seinem eigenen Hause ein Baum genommen und er daran gehenkt und alle seine Güter dem König verfallen sein sollen.',
'Der Herr also, dessen Name dort angerufen wird, möge jeden König und jedes Volk, das seine Hand ausstreckt zu hindern oder zu schädigen das Haus des Herrn zu Jerusalem, ganz und gar vernichten.',
'Ich, Darius, der König, habe geordnet, daß es gemäß diesen Dingen mit Sorgfalt geschehe.'
];

const ch7 = [
'Da überwachten Sisinnes, der Statthalter von Cölesyrien und Phönizien, und Sathrabuzanes mit ihren Gefährten, den Befehlen des Königs Darius folgend,',
'sehr sorgfältig die heiligen Werke und unterstützten die Ältesten der Juden und die Vorsteher des Tempels.',
'Und so gediehen die heiligen Werke, als die Propheten Aggäus und Sacharja weissagten.',
'Und sie vollendeten diese Dinge auf Befehl des Herrn, des Gottes Israels, und mit dem Einverständnis des Kyrus, Darius und Artaxerxes, der Könige der Perser.',
'Und so wurde das heilige Haus vollendet am dreiundzwanzigsten Tage des Monats Adar, im sechsten Jahr der Regierung des Darius, des Königs der Perser.',
'Und die Kinder Israels, die Priester und die Leviten und andere aus der Gefangenschaft, die zu ihnen hinzugetan worden waren, taten das, was im Buch Moses geschrieben stand.',
'Und zur Weihe des Tempels des Herrn brachten sie hundert Stiere, zweihundert Widder, vierhundert Lämmer dar;',
'und zwölf Böcke für die Sünde ganz Israels, nach der Zahl der Häupter der Stämme Israels.',
'Auch die Priester und die Leviten standen in ihren Gewändern nach ihren Geschlechtern geordnet im Dienst des Herrn, des Gottes Israels, nach dem Buch Moses; und die Torhüter an jedem Tor.',
'Und die Kinder Israels, die aus der Gefangenschaft gekommen waren, hielten das Passah am vierzehnten Tage des ersten Monats, nachdem die Priester und die Leviten zusammen geheiligt worden waren.',
'Die aus der Gefangenschaft waren nicht alle zusammen geheiligt worden; aber die Leviten waren alle zusammen geheiligt.',
'Und so opferten sie das Passah für alle aus der Gefangenschaft und für ihre Brüder, die Priester, und für sich selbst.',
'Und die Kinder Israels, die aus der Gefangenschaft kamen, aßen, auch alle die, die sich von den Greueln der Völker des Landes abgesondert und den Herrn gesucht hatten.',
'Und sie hielten das Fest der ungesäuerten Brote sieben Tage und freuten sich vor dem Herrn,',
'weil er den Ratschluß des Königs von Assyrien zu ihren Gunsten gewendet hatte, ihre Hände zu stärken in den Werken des Herrn, des Gottes Israels.'
];

const ch8 = [
'Und nach diesen Dingen, als Artaxerxes, der König der Perser, regierte, kam Esra, der Sohn des Saraja, des Sohnes des Eseria, des Sohnes des Helkia, des Sohnes des Salum,',
'des Sohnes des Sadduk, des Sohnes des Achitob, des Sohnes des Amarja, des Sohnes des Esja, des Sohnes des Meremoth, des Sohnes des Saraja, des Sohnes des Savja, des Sohnes des Bokkas, des Sohnes des Abisum, des Sohnes des Phinees, des Sohnes des Eleasars, des Sohnes Aarons, des Hohenpriesters.',
'Dieser Esra zog aus Babel hinauf als ein Schriftgelehrter, sehr erfahren im Gesetz Moses, das vom Gott Israels gegeben war.',
'Und der König ehrte ihn; denn er fand Gnade bei ihm in allen seinen Bitten.',
'Mit ihm zogen auch etliche von den Kindern Israels hinauf, von den Priestern und Leviten, den heiligen Sängern, Torhütern und Tempeldienern nach Jerusalem,',
'im siebten Jahr der Regierung des Artaxerxes, im fünften Monat — das war das siebte Jahr des Königs; denn sie zogen am ersten Tag des ersten Monats aus Babel aus und kamen nach Jerusalem, gemäß dem glücklichen Weg, den der Herr ihnen gegeben hatte.',
'Denn Esra hatte großes Geschick, so daß er nichts aus dem Gesetz und den Geboten des Herrn ausließ, sondern ganz Israel alle Satzungen und Rechte lehrte.',
'Nun ist die Abschrift des Auftrags, der von Artaxerxes, dem König, geschrieben wurde und zu Esra, dem Priester und Leser des Gesetzes des Herrn, kam, diese:',
'König Artaxerxes grüßt Esra, den Priester und Leser des Gesetzes des Herrn:',
'Da ich entschlossen bin, gnädig zu handeln, habe ich angeordnet, daß diejenigen aus der Völkerschaft der Juden und von den Priestern und Leviten, die in meinem Reiche sind und nach Jerusalem zu ziehen willens und begierig sind, mit dir ziehen sollen.',
'Daher, so viele Lust dazu haben, sollen mit dir ausziehen, wie es mir und meinen sieben Freunden, den Ratgebern, gut schien;',
'damit sie sich der Angelegenheiten Judäas und Jerusalems gemäß dem, was im Gesetz des Herrn steht, annehmen;',
'und die Gaben für den Herrn Israels nach Jerusalem bringen, die ich und meine Freunde gelobt haben, und alles Gold und Silber, das im Land Babel aufgefunden werden kann, dem Herrn in Jerusalem,',
'dazu auch das, was vom Volk für den Tempel des Herrn, ihres Gottes, zu Jerusalem gegeben wird; und daß Silber und Gold für Stiere, Widder und Lämmer und die dazugehörigen Dinge gesammelt werden dürfe;',
'damit sie dem Herrn auf dem Altar des Herrn, ihres Gottes, der in Jerusalem ist, Opfer darbringen können.',
'Und was auch immer du und deine Brüder mit dem Silber und Gold tun wollt, das tut nach dem Willen eures Gottes.',
'Und die heiligen Gefäße des Herrn, die dir für den Gebrauch des Tempels deines Gottes gegeben werden und in Jerusalem sind, sollst du vor deinen Gott in Jerusalem stellen.',
'Und alles übrige, was du sonst für den Gebrauch des Tempels deines Gottes benötigst, sollst du aus dem königlichen Schatz geben.',
'Und ich, König Artaxerxes, habe auch den Schatzmeistern in Syrien und Phönizien geboten, daß sie alles, was Esra, der Priester und Leser des Gesetzes des höchsten Gottes, anfordert, ihm eilends geben sollen,',
'bis zu hundert Talenten Silber, und ebenso an Weizen bis zu hundert Kor und hundert Stücken Wein, und anderem in Fülle.',
'Es soll alles nach dem Gesetz Gottes sorgfältig dem höchsten Gott gegenüber getan werden, damit nicht Zorn über das Königreich des Königs und seiner Söhne komme.',
'Ich befehle euch auch, daß ihr keinen Zins und keine andere Abgabe von irgendwelchen Priestern oder Leviten oder heiligen Sängern oder Torhütern oder Tempeldienern fordert; und daß kein Mensch befugt sei, ihnen irgend etwas aufzulegen.',
'Und du, Esra, setze nach der Weisheit Gottes Richter und Urteilssprecher ein, die in ganz Syrien und Phönizien alle richten sollen, die das Gesetz deines Gottes kennen; und die es nicht kennen, sollst du es lehren.',
'Und wer auch immer das Gesetz deines Gottes und des Königs übertreten wird, der soll sorgfältig bestraft werden, sei es durch den Tod oder eine andere Strafe, durch eine Geldbuße oder Gefängnis.',
'Da sprach Esra, der Schriftgelehrte: Gelobt sei der einzige Herr, der Gott meiner Väter, der in das Herz des Königs dieses gegeben hat, sein Haus in Jerusalem zu verherrlichen:',
'und der mich geehrt hat vor dem König und seinen Ratgebern und all seinen Freunden und Edlen.',
'Daher wurde ich ermutigt durch die Hilfe des Herrn, meines Gottes, und sammelte Männer aus Israel, die mit mir hinaufziehen sollten.',
'Und das sind die Häupter nach ihren Geschlechtern und besonderen Würden, die mit mir aus Babel in der Regierung des Königs Artaxerxes hinaufzogen:',
'von den Söhnen des Phinees, Gerson: von den Söhnen des Ithamar, Gamael: von den Söhnen Davids, Lettus, der Sohn des Sechenias:',
'von den Söhnen des Phares, Sacharja; und mit ihm wurden einhundertundfünfzig Männer gezählt:',
'von den Söhnen des Pahath-Moab, Eliaonias, der Sohn des Saraja, und mit ihm zweihundert Männer:',
'von den Söhnen des Sathoe, Sechenias, der Sohn des Jesels, und mit ihm dreihundert Männer: von den Söhnen des Adin, Obeth, der Sohn des Jonathan, und mit ihm zweihundertundfünfzig Männer:',
'von den Söhnen des Elam, Josias, der Sohn des Gotholias, und mit ihm siebzig Männer:',
'von den Söhnen des Saphatias, Saraja, der Sohn des Micha, und mit ihm siebzig Männer:',
'von den Söhnen des Joab, Abadias, der Sohn des Jeselus, und mit ihm zweihundertundzwölf Männer:',
'von den Söhnen des Banid, Assalimoth, der Sohn des Josaphias, und mit ihm einhundertundsechzig Männer:',
'von den Söhnen des Babi, Sacharja, der Sohn des Bebai, und mit ihm achtundzwanzig Männer:',
'von den Söhnen des Astath, Johannes, der Sohn des Akatan, und mit ihm einhundertundzehn Männer:',
'von den Söhnen des Adonikam, die letzten, deren Namen diese sind: Eliphalet, Jewel und Samaias, und mit ihnen siebzig Männer:',
'von den Söhnen des Bago, Uthi, der Sohn des Istalcurus, und mit ihm siebzig Männer.',
'Und diese versammelte ich am Fluß, der Theras heißt, wo wir drei Tage unsere Zelte aufschlugen; und dann musterte ich sie.',
'Als ich aber dort keine Priester und Leviten vorfand,',
'sandte ich zu Eleasar und Iduel und Masman,',
'und Alnathan und Mamaias und Joribas und Nathan, Eunatan, Sacharja und Mosollamon, den Hauptleuten und Gelehrten.',
'Und ich gebot ihnen, zu Saddeus, dem Hauptmann, zu gehen, der an dem Schatzort war:',
'und ihnen zu befehlen, mit Daddeus und seinen Brüdern und den Schatzmeistern an diesem Ort zu reden, uns Männer zu schicken, die das Priesteramt im Hause des Herrn ausüben könnten.',
'Und durch die mächtige Hand unseres Herrn brachten sie uns erfahrene Männer aus den Söhnen des Moli, des Sohnes des Levi, des Sohnes Israels: Asebebia und seine Söhne und seine Brüder, die achtzehn waren.',
'Und Asebja und Annus und Osaias, sein Bruder, von den Söhnen des Channuneus, und ihre Söhne, waren zwanzig Männer.',
'Und von den Tempelknechten, die David eingesetzt hatte und die Hauptleute für den Dienst der Leviten, nämlich die Tempelknechte, zweihundertundzwanzig, deren Namen im Verzeichnis standen.',
'Und da gelobte ich für die jungen Männer vor unserem Herrn ein Fasten, um von ihm einen glücklichen Weg zu erbitten, für uns und für die, die mit uns waren, für unsere Kinder und für das Vieh:',
'denn ich schämte mich, vom König Fußvolk und Reiter und Geleit zum Schutz gegen unsere Feinde zu erbitten.',
'Denn wir hatten dem König gesagt, daß die Kraft des Herrn, unseres Gottes, bei denen sei, die ihn suchen, ihn in allen Wegen zu stärken.',
'Und wieder baten wir unsern Herrn über diese Dinge, und wir fanden ihn uns günstig gesonnen.',
'Da sonderte ich zwölf von den Hauptpriestern aus: Esebrias und Assanias und zehn Männer ihrer Brüder mit ihnen:',
'und ich wog ihnen das Gold und das Silber und die heiligen Gefäße des Hauses unseres Herrn, die der König und sein Rat und die Fürsten und ganz Israel gegeben hatten.',
'Und als ich es gewogen hatte, übergab ich ihnen sechshundertundfünfzig Talente Silber und silberne Gefäße von hundert Talenten und hundert Talenten Gold,',
'und zwanzig goldene Gefäße und zwölf eherne Gefäße aus feinem Messing, glänzend wie Gold.',
'Und ich sprach zu ihnen: Sowohl ihr als auch die Gefäße seid dem Herrn heilig, und das Gold und das Silber ist ein Gelübde an den Herrn, den Herrn unserer Väter.',
'Wacht und bewahrt sie, bis ihr sie den Hauptpriestern und Leviten und den Hauptleuten der Geschlechter Israels übergebt, in Jerusalem in die Kammern des Hauses unseres Gottes.',
'So brachten die Priester und die Leviten, die das Silber und Gold und die Gefäße empfangen hatten, sie nach Jerusalem, in den Tempel des Herrn.',
'Und wir brachen vom Fluß Theras am zwölften Tage des ersten Monats auf und kamen durch die mächtige Hand unseres Herrn nach Jerusalem; denn der Herr bewahrte uns von Anfang unseres Weges an vor jedem Feind, und so kamen wir nach Jerusalem.',
'Als wir nun drei Tage dort gewesen waren, wurden das Gold und Silber, das abgewogen worden war, am vierten Tage im Hause unseres Herrn dem Priester Marmoth, dem Sohn des Iri, ausgehändigt.',
'Und bei ihm war Eleasar, der Sohn des Phinees, und bei ihnen Josabad, der Sohn des Jesu, und Moeth, der Sohn des Sabban, Leviten: alles wurde ihnen nach Zahl und Gewicht übergeben.',
'Und das gesamte Gewicht wurde zur selben Stunde aufgeschrieben.',
'Überdies opferten die aus der Gefangenschaft Zurückgekehrten dem Herrn, dem Gott Israels, zwölf Stiere für ganz Israel, sechsundneunzig Widder,',
'zweiundsiebzig Lämmer, Böcke als Friedensopfer, zwölf; alles ein Opfer für den Herrn.',
'Und sie übergaben den Befehl des Königs den Verwaltern des Königs und den Statthaltern von Cölesyrien und Phönizien; und diese ehrten das Volk und den Tempel Gottes.',
'Als nun diese Dinge geschehen waren, kamen die Anführer zu mir und sprachen:',
'Das Volk Israel, die Fürsten, die Priester und Leviten, haben sich von den fremden Völkern des Landes und von den Greueln der Heiden nicht gesondert, nämlich von den Kanaanitern, Hethitern, Pherezitern, Jebusitern und von den Moabitern, Ägyptern und Edomitern.',
'Denn sowohl sie als auch ihre Söhne haben mit deren Töchtern geheiratet, und der heilige Same hat sich mit den fremden Völkern des Landes vermischt; und die Anführer und die Vornehmen haben von Anfang dieser Sache an an dieser Ungerechtigkeit teilgehabt.',
'Und sobald ich diese Dinge hörte, zerriß ich meine Kleider und das heilige Gewand und raufte die Haare von meinem Kopf und Bart aus und saß betrübt und sehr bestürzt nieder.',
'Da versammelten sich alle, die durch das Wort des Herrn, des Gottes Israels, bewegt waren, um mich, während ich über die Ungerechtigkeit trauerte; aber ich saß still voll Betrübtheit bis zum Abendopfer.',
'Dann stand ich vom Fasten auf, mit zerrissenen Kleidern und dem heiligen Gewand, und kniete nieder und streckte meine Hände aus zum Herrn',
'und sprach: Herr, ich bin beschämt und bestürzt vor deinem Angesicht;',
'denn unsere Sünden sind über unser Haupt gehäuft, und unsere Unwissenheit hat bis zum Himmel gereicht.',
'Denn von den Zeiten unserer Väter an bis jetzt sind wir in großer Sünde, ja bis auf diesen Tag.',
'Und um unserer Sünden und der unserer Väter willen wurden wir mit unsern Brüdern und Königen und Priestern den Königen der Erde übergeben, zum Schwert und zur Gefangenschaft und zur Beute mit Scham, bis auf diesen Tag.',
'Und nun ist uns in einem Maße Barmherzigkeit von dir, Herr, erwiesen worden, daß uns eine Wurzel und ein Name an dem Ort deines Heiligtums gelassen werden sollte;',
'und uns ein Licht im Hause des Herrn, unseres Gottes, aufzugehen und uns Nahrung in der Zeit unserer Knechtschaft zu geben.',
'Ja, als wir in der Knechtschaft waren, wurden wir von unserm Herrn nicht verlassen; sondern er machte uns gnädig vor den Königen der Perser, daß sie uns Nahrung gaben;',
'ja, sie ehrten den Tempel unseres Herrn und bauten das verödete Zion auf, daß sie uns eine sichere Stätte in Judäa und Jerusalem gegeben haben.',
'Und nun, Herr, was sollen wir sagen, da wir dies haben? Denn wir haben deine Gebote übertreten, die du durch die Hand deiner Knechte, der Propheten, gegeben hast, und gesagt hast:',
'Das Land, in das ihr einzieht, um es als Erbe zu besitzen, ist ein Land, das durch die Greuel der Fremden des Landes verunreinigt ist, und sie haben es mit ihrer Unreinheit erfüllt.',
'Darum sollt ihr eure Töchter nicht ihren Söhnen geben, noch ihre Töchter zu euren Söhnen nehmen.',
'Ihr sollt auch nimmermehr ihren Frieden suchen, damit ihr stark seiet und die guten Dinge des Landes esset und das Erbe des Landes euren Kindern auf ewig hinterlasset.',
'Und alles, was uns begegnet ist, ist uns um unserer bösen Werke und großen Sünden willen widerfahren; denn du, Herr, hast unsere Sünden erleichtert',
'und hast uns solch eine Wurzel gegeben: aber wir haben uns wieder umgewandt, dein Gesetz zu übertreten und uns mit der Unreinheit der Völker des Landes zu vermischen.',
'Konntest du nicht zürnen über uns, um uns zu vernichten, bis du weder Wurzel noch Samen noch Namen zurückgelassen hättest?',
'Herr Israels, du bist gerecht; denn wir sind heute eine Wurzel geblieben.',
'Sieh, nun stehen wir vor dir in unseren Sünden; denn wir können wegen dieser Dinge nicht länger vor dir bestehen.',
'Und als Esra in seinem Gebet seine Beichte ablegte, weinend und ausgestreckt auf dem Boden vor dem Tempel, versammelte sich zu ihm aus Jerusalem eine sehr große Menge von Männern und Frauen und Kindern; denn unter dem Volk war großes Weinen.',
'Da rief Jechonias, der Sohn des Jeelus, einer der Söhne Israels, und sprach: O Esra, wir haben gegen den Herrn, unseren Gott, gesündigt; wir haben fremde Frauen von den Heiden des Landes geheiratet; und nun ist ganz Israel obenauf.',
'Laßt uns dem Herrn einen Eid schwören, daß wir alle unsere Frauen, die wir von den Heiden genommen haben, mit ihren Kindern entlassen wollen,',
'wie du beschlossen hast und wie viele, die dem Gesetz des Herrn gehorchen.',
'Stehe auf und tue es: denn diese Sache liegt dir ob, und wir werden bei dir sein; tue es tapfer.',
'So stand Esra auf und ließ die Hauptleute der Priester und der Leviten und ganz Israels schwören, nach diesen Dingen zu tun; und sie schworen.'
];

const ch9 = [
'Da stand Esra auf vom Vorhof des Tempels und ging in die Kammer Johanans, des Sohnes des Eljasib,',
'und blieb da und aß keine Speise und trank kein Wasser, trauernd über die großen Sünden der Menge.',
'Und es wurde in ganz Judäa und Jerusalem an alle, die aus der Gefangenschaft waren, ein Aufruf gemacht, daß sie sich in Jerusalem versammeln sollten:',
'und daß, wer sich nicht innerhalb von zwei oder drei Tagen, wie die Ältesten, die das Regiment hatten, festgesetzt hatten, einfinden würde, dessen Vieh für den Tempel beschlagnahmt und er selbst aus der Gemeinschaft der Gefangenschaft ausgestoßen werden sollte.',
'Und in drei Tagen versammelten sich alle vom Stamm Juda und Benjamin in Jerusalem am zwanzigsten Tage des neunten Monats.',
'Und die ganze Menge saß auf dem freien Platz vor dem Tempel zitternd, wegen des gerade herrschenden schlechten Wetters.',
'Da stand Esra auf und sprach zu ihnen: Ihr habt das Gesetz übertreten, indem ihr fremde Frauen geheiratet habt, um die Sünden Israels zu mehren.',
'Und nun gebt dem Herrn, dem Gott unserer Väter, die Ehre durch das Bekenntnis',
'und tut seinen Willen und sondert euch von den Heiden des Landes und von den fremden Frauen.',
'Da rief die ganze Menge und sprach mit lauter Stimme: Wie du gesprochen hast, so wollen wir tun.',
'Da aber das Volk zahlreich ist und das Wetter schlecht, so daß wir nicht draußen stehen können, und dies nicht ein Werk von einem oder zwei Tagen ist, da unsere Sünde in diesen Dingen weit verbreitet ist:',
'so soll der Vorsteher der Menge bleiben, und alle, die in unseren Wohnorten fremde Frauen haben, zur festgesetzten Zeit kommen,',
'und mit ihnen die Vorsteher und Richter jeden Ortes, bis wir den Zorn des Herrn um dieser Sache willen von uns abwenden.',
'Da nahmen Jonatan, der Sohn des Asael, und Esechias, der Sohn des Theokan, dieser Sache sich an gemäß dem Übereinkommen; und Mosollam und Levis und Sabbatheus halfen ihnen.',
'Und die aus der Gefangenschaft taten gemäß allen diesen Dingen.',
'Und Esra, der Priester, wählte sich die Hauptleute ihrer Geschlechter aus, alle mit Namen; und sie saßen am ersten Tage des zehnten Monats zusammen, um die Sache zu untersuchen.',
'Und ihre Sache, die fremde Frauen gehabt hatten, wurde am ersten Tage des ersten Monats erledigt.',
'Und von den Priestern, die sich versammelt hatten und fremde Frauen gehabt hatten, wurden gefunden:',
'von den Söhnen Jesu, des Sohnes Josedechs, und seinen Brüdern: Mattelas und Eleasar und Joribus und Joadanus.',
'Und sie gaben ihre Hände dazu, ihre Frauen zu entlassen und Widder darzubringen zur Versöhnung für ihre Vergehen.',
'Von den Söhnen Emmers: Ananias und Zabdeus und Eanes und Samejus und Hiereel und Asarias.',
'Und von den Söhnen Phaisurs: Elionas, Masias, Israel und Nathanael und Okidelus und Talsas.',
'Und von den Leviten: Josabad und Semis und Kolius, der Kalitas genannt wurde, und Patheus und Judas und Jonas.',
'Von den heiligen Sängern: Eleasarus, Bakkurus.',
'Von den Torhütern: Sallumus und Tolbanes.',
'Von den Israeliten, von den Söhnen des Phoros: Hiermas und Eddias und Melchias und Maelus und Eleasar und Asibias und Baanias.',
'Von den Söhnen des Ela: Matthanias, Sacharja und Hierielus und Hieremoth und Aedias.',
'Und von den Söhnen des Samoth: Eliadas, Elisimus, Othonias, Jarimoth und Sabatus und Sardeus.',
'Von den Söhnen des Babai: Johannes und Ananias und Josabad und Amatheis.',
'Von den Söhnen des Mani: Olamus, Mamuchus, Jedeus, Jasubus, Jasael und Hieremoth.',
'Und von den Söhnen des Addi: Naathus und Moosias, Lakunus und Naidus und Mathanias und Sesthel, Balnuus und Manasseas.',
'Und von den Söhnen des Annas: Elionas und Aseas und Melchias und Sabbeus und Simon Chosameus.',
'Und von den Söhnen des Asom: Altaneus und Mattias und Baanaia, Eliphalet und Manasses und Semei.',
'Und von den Söhnen des Maani: Jeremias, Momdis, Omaerus, Joel, Mabdai und Pelias und Anos, Karabasion und Enasibus und Mamnitanaimus, Eliasis, Bannus, Eliali, Samis, Selemias, Nathanias: und von den Söhnen des Osora: Sesis, Esril, Asaelus, Samatus, Sambis, Josephus.',
'Und von den Söhnen des Ethma: Masitias, Sabadaias, Edes, Joel, Banaias.',
'Diese alle hatten fremde Frauen genommen, und sie entließen sie mit ihren Kindern.',
'Und die Priester und Leviten und die von Israel wohnten in Jerusalem und im Land, am ersten Tage des siebten Monats: so waren die Kinder Israels in ihren Wohnungen.',
'Und die ganze Menge kam einmütig zusammen auf den freien Platz des heiligen Vorhofs nach Osten;',
'und sie sprachen zu Esra, dem Priester und Leser, er solle das Gesetz Moses bringen, das vom Herrn, dem Gott Israels, gegeben war.',
'Da brachte Esra, der Hohepriester, das Gesetz zur ganzen Menge, von Mann bis Frau und zu allen Priestern, um das Gesetz zu hören am ersten Tage des siebten Monats.',
'Und er las auf dem freien Platz vor dem heiligen Vorhof von morgens bis mittags vor Männern und Frauen; und die Menge gab acht auf das Gesetz.',
'Und Esra, der Priester und Leser des Gesetzes, stand auf einem hölzernen Podest, das für diesen Zweck gemacht worden war.',
'Und neben ihm standen Mattathias, Sammus, Ananias, Asarias, Urias, Esechias, Balasamus zu seiner Rechten:',
'und zu seiner Linken standen Phaldaius, Misael, Melchias, Lothasubus und Nabarias.',
'Da nahm Esra das Buch des Gesetzes vor der Menge; denn er saß ehrenvoll an der ersten Stelle im Angesicht aller.',
'Und als er das Gesetz öffnete, standen alle sogleich gerade auf. Da pries Esra den Herrn, den Gott, den Höchsten, den Gott der Heerscharen, den Allmächtigen.',
'Und alles Volk antwortete: Amen; und die Hände aufhebend, warfen sie sich zu Boden und beteten den Herrn an.',
'Auch Jesus, Anus, Sarabias, Adinus, Jakubus, Sabateas, Auteas, Maianeas und Kalitas, Asrias und Josabad und Ananias, Biatas, die Leviten, lehrten das Gesetz des Herrn und erklärten es zugleich.',
'Da sprach Attharat zu Esra, dem Hohenpriester und Leser, und zu den Leviten, die die Menge lehrten, zu allen, und sagte:',
'Dieser Tag ist dem Herrn heilig (denn alle weinten, als sie das Gesetz hörten):',
'Gehet nun hin und esset das Fette und trinket das Süße und schicket Teile denen, die nichts haben;',
'denn der Tag ist dem Herrn heilig: und seid nicht traurig; denn der Herr wird euch zur Ehre bringen.',
'Da kundeten die Leviten alles dem Volk und sagten: Dieser Tag ist dem Herrn heilig; seid nicht traurig.',
'Da gingen sie ihrer Wege, jeder um zu essen und zu trinken und fröhlich zu sein und Teile denen zu schicken, die nichts hatten, und große Freude zu machen;',
'denn sie verstanden die Worte, in denen sie unterwiesen worden waren und zu denen sie versammelt worden waren.'
];

const chapters = [ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9];
const b74 = {chapters: {}};
chapters.forEach((verses, i) => {
  const cn = i + 1;
  const vv = {};
  verses.forEach((t, j) => { vv[j+1] = {verse: j+1, text: t}; });
  b74.chapters[cn] = {chapter: cn, name: '', verses: vv};
});

fs.writeFileSync(BASE + '074.json', JSON.stringify(b74), 'utf8');
const total = chapters.reduce((s,c)=>s+c.length,0);
console.log('074.json done: ' + total + ' verses across ' + chapters.length + ' chapters');
