// Batch D: Buch 75 (4. Esra) Kapitel 13–16
const fs = require('fs');

const ch13 = [
'Und es begab sich nach sieben Tagen, daß ich abermals träumte in der Nacht.',
'Und sieh, da stieg ein Wind aus dem Meer und bewegte alle seine Wellen.',
'Und ich sah, und sieh, dieser Wind ließ aus dem Herzen des Meeres etwas wie die Gestalt eines Mannes aufsteigen: und ich sah, und sieh, dieser Mann flog mit den Wolken des Himmels.',
'Und wohin er sein Antlitz kehrte und blickte, erbebte alles, was unter ihm gesehen wurde;',
'und wohin die Stimme seines Mundes ausging, schmolzen alle, die seine Stimme hörten, wie das Wachs schmilzt, wenn es das Feuer fühlt.',
'Und danach sah ich, und sieh, von den vier Winden des Himmels strömte eine unzählige Menge von Menschen zusammen, um mit dem Mann zu kämpfen, der aus dem Meer aufgestiegen war.',
'Und ich sah, und sieh, er schnitt sich einen großen Berg heraus und flog auf ihm.',
'Aber ich suchte die Gegend zu sehen, aus der der Berg herausgehauen wurde, und konnte nicht.',
'Und danach sah ich, und sieh, alle, die sich gegen ihn versammelten, um ihn zu bekriegen, erschraken sehr, aber wagten es gleichwohl zu kämpfen.',
'Und sieh, als er das Gedränge der anrückenden Menge sah, erhob er weder seine Hand, noch hielt er Schwert noch ein Kriegswerkzeug in der Hand:',
'sondern ich sah nur, daß er aus seinem Munde wie einen feurigen Strom ausströmen ließ, und von seinen Lippen einen flammenden Atem, und von seiner Zunge sandte er Funken und Stürme aus.',
'Und diese wurden alle zusammen gemischt; der feurige Strom, der flammende Atem und der mächtige Sturm: und fielen auf die anstürmende Menge, die bereit war zu kämpfen, und verbrannte sie alle, so daß plötzlich von einer unzähligen Menge nichts als Staub der Asche zu sehen war.',
'Da war ich erschrocken, und ich erwachte aus dem Schrecken und betete zum Allerhöchsten und sprach:',
'O Herr, der du herrschest, du hast in deinen Wundern all dieses gezeigt, und hast mich für würdig erachtet, daß du mein Gebet gehört hast.',
'Zeige mir nun auch die Auslegung dieses Traumes.',
'Denn wie ich verstehe und bedenke in meinem Sinn: wehe denen, die zur Zeit jener Tage auf Erden bleiben! und noch mehr: wehe denen, die nicht dabei sind!',
'Denn die, welche nicht dabei sind, sollen betrübt sein,',
'weil sie es verstehen werden, was in den letzten Tagen aufbewahrt ist, und doch nicht dahin kommen werden.',
'Aber wehe auch denen, die dabei sind! denn sie müssen durch große Gefahren und viele Nöte gehen, wie diese Träume zeigen.',
'Gleichwohl ist es besser, in Gefahr zu kommen und diese Dinge zu erreichen, als wie eine Wolke aus der Welt zu vergehen und das Angesicht des Allerhöchsten nicht zu sehen.',
'Er antwortete mir und sprach: Ich will dir jetzt die Auslegung deines Traumes sagen und dir erklären, was du gesagt hast.',
'Was du gesagt hast, daß ein Mann aus dem Herzen des Meeres aufsteige:',
'das ist derjenige, den der Allerhöchste in vielen Zeiten aufbewahrt hat, durch den er die Schöpfung selbst erretten und die überlebenden Seelen lenken wird.',
'Und da du sahst, daß Wind und Feuer und Sturm aus seinem Munde ausging, und daß er weder Schwert noch Kriegswerkzeug hielt, sondern daß der Anstrom der angreifenden Menge vernichtete:',
'dies ist die Auslegung:',
'Sieh, die Tage werden kommen, daß der Allerhöchste beginnen wird, die darin wohnenden Völker der Erde zu erretten, und er soll ihnen einen Schrecken bringen;',
'und da wird große Bestürzung unter ihnen entstehen, und einer soll gegen den anderen Krieg führen, Stadt gegen Stadt, Ort gegen Ort, Volk gegen Volk und Königreich gegen Königreich.',
'Und wenn diese Dinge geschehen und die Zeichen eintreten, die ich dir vorher gezeigt habe, dann soll mein Sohn offenbart werden, den du als den aufsteigenden Mann sahst.',
'Und wenn alle Völker seine Stimme hören werden, wird jeder einen Mann in seinem eigenen Land hinterlassen und eine nach der anderen ihr Heer gegen ihn bringen.',
'Aber er wird auf dem Gipfel des Berges Zion stehen.',
'Und Zion wird kommen und wird ihm gezeigt werden, das allen Menschen bereitet und das Erbaute werden wird, wie du den Berg sahst, der ohne Hände gehauen war.',
'Aber mein Sohn wird die Völker, die zu ihm kommen, scheltend und ohne Mühe vernichten, durch das Gesetz, welches dem Feuer verglichen wird.',
'Und da du sahst, daß er viele Menschen aus den vier Winden des Himmels sammelte: dies bedeutet,',
'daß er die zehn Stämme nehmen wird, die bisher nicht in ihr eigenes Land geführt wurden, und in die Gefangenschaft gingen, aus der Assur, ihr König, sie geführt hat jenseits des Flusses, und sie sind dorthin gebracht worden.',
'Sie wohnten im anderen Land bis zu dieser Zeit; und wenn sie anfangen sollen zurückzukehren, soll der Allerhöchste abermals die Ströme hemmen und ihnen Macht zu gehen geben; darum wurde die große Menge mit Frieden gesehen.',
'Aber die, welche in deinem Lande übrig gelassen wurden, soll er auch erretten.',
'Wenn also er die Menge der Völker vernichten soll, die sich versammeln, soll er sein Volk beschützen, das übrig geblieben ist,',
'und er soll viele Wunder mit ihnen zeigen.',
'Ich antwortete und sprach: O Herr, der du herrschest, zeig mir: warum sah ich den Mann aus dem Herzen des Meeres aufsteigen?',
'Er antwortete mir und sprach: Wie du nicht erforschen oder wissen kannst, was in der Tiefe des Meeres ist: ebenso kann kein Mensch auf Erden deinen Sohn sehen oder die, die bei ihm sind, außer zur Zeit seines Tages.',
'Dies ist die Auslegung des Traumes, den du gesehen hast. Und darum bist du allein erleuchtet über dieses,',
'weil du das Höchste verlassen und dich dem Niedrigen ergeben hast und das Gesetz des Allerhöchsten erforschst.',
'Er hat mich darum auf dieser Nacht zu dir gesandt, um dir diese Dinge zu sagen. Darum glaube und fürchte dich nicht!',
'Und hör nicht auf, morgen zur Zeit der Fürsten des Volkes zu suchen, denn noch kürzer wirst du sein.',
'Denn von diesen sollen sich die Zeichen bewahrheiten, die ich dir gezeigt habe, und es wird geschehen, was zukünftig ist; du wirst es sehen, wenn deine Tage vorbei sind.',
'Darum geh, und welches Gesicht immer du gesehen hast, was du gehört und was du teilweise erkannt hast, das schreibe in ein Buch und verbirg es.',
'Und morgen zur gleichen Zeit, wenn du von mir hören wirst, kehre hierher zurück,',
'und der Allerhöchste soll dir sehen lassen, was der Höchste denen anordnen soll, die auf Erden wohnen in den letzten Tagen. So schlief ich jene Nacht und eine andere, wie er mir befohlen hatte.'
];

const ch14 = [
'Und es begab sich am dritten Tag, als ich unter einer Eiche saß, sieh, da kam eine Stimme aus dem Gesträuch mir gegenüber und sprach: Esra, Esra!',
'Und ich sprach: Hier bin ich, Herr. Und ich stand auf auf meine Füße.',
'Da sprach sie zu mir: Im Gesträuch habe ich mich Mose klar gezeigt und mit ihm geredet, als mein Volk in der Knechtschaft in Ägypten war.',
'Und ich sandte ihn hin und führte mein Volk aus Ägypten und brachte ihn auf den Berg Sinai, wo ich ihn viele Tage bei mir behielt.',
'Und ich erzählte ihm viele wunderbare Dinge und zeigte ihm die Geheimnisse der Zeiten und das Ende der Zeiten erklärte ich ihm; und ich befahl ihm, zu sagen: Diese Worte zeige öffentlich, aber jene Worte verbirg.',
'Und nun befehle ich dir auch:',
'Die Zeichen, die ich dir gezeigt habe, und die Träume, die du gesehen hast, und die Auslegungen, die du gehört hast, schreibe sie in ein Buch und lege es an einen verborgenen Ort.',
'Und lehre sie die Weisen unter deinem Volk, deren Herzen du kennst, die diese Geheimnisse bewahren werden.',
'Aber jetzt halte noch sieben Tage, damit du in diesen Tagen belehrt wirst, so wie dir befohlen wurde.',
'Und am dritten Tag wirst du auch in mir sitzen wie jetzt und ich werde mit dir reden und dir viel Wichtiges sagen und dir die Wunder der letzten Dinge befehlen zu schreiben, was du finden wirst.',
'Und ich antwortete und sprach: Laß mich, Herr, nach deinem Wort reden vor die dir: sieh, ich werde gehen, wie du mir befohlen hast und die Überlebenden ermahnen; aber wer kann mich lehren und wie soll mein Herz den Anfang und das Ende dessen fassen, was du mich zu schreiben befiehlst?',
'Er aber sprach zu mir: Dein Herz soll nicht überwältigt werden, und schreke nicht dein Herz; denn du wirst zu deiner Zeit von ihm geführt werden; komm daher zu mir, und ich werde dir auf meinem Thron zeigen, was ich dir zeigen will.',
'Und er sandte mir seine Herrlichkeit, und seine Herrlichkeit machte mein Herz weise; und ein Geist des Verstehens wurde in mir geweckt.',
'Und ich öffnete meinen Mund und begann mit ihm zu reden, indem ich sprach:',
'Sieh, Herr, du willst nun leben, und die Welt wird in der Verfinsterung seiner Enden das Licht verlieren und diejenigen, die darin übrig sind, sollen vergehen.',
'Das Gesetz aber ist verbrannt; darum wissen keiner deiner Werke, was du dir vorgenommen hast, noch was erlangt werden kann.',
'Wenn nun ich Gnade vor dir gefunden habe, sende den Heiligen Geist in mich, damit ich alles aufschreiben kann, was in der Welt von Anfang an getan wurde, selbst die Dinge, die in deinem Gesetz aufgezeichnet sind, damit die Menschen, die auf der Erde leben werden, einen Weg finden und die, die im letzten Zeitalter leben wollen, leben können.',
'Er antwortete mir und sprach: Geh hin und versammle das Volk, und sag ihnen, daß sie dich vierzig Tage lang nicht suchen sollen.',
'Aber du bereite dir viele Schreibtafeln und nimm mit dir Sarea, Dabria, Selemia, Ecanus und Asiel, diese fünf, die zum Schreiben geübt sind:',
'und komm her, und ich werde das Licht der Einsicht in deinem Herzen entzünden, das nicht verlöschen wird, bis du vollendet hast, was du zu schreiben anfangen wirst.',
'Und wenn du das vollbracht hast, werde ich das, was du geschrieben hast, öffentlich und im Verborgenen verkünden lassen.',
'Und am nächsten Tag, sieh, eine Stimme rief mich und sprach: Esra, öffne deinen Mund und trinke das, was ich dir reiche.',
'Da öffnete ich meinen Mund, und sieh, mir wurde eine volle Schale gereicht, voll wie mit Wasser, aber ihre Farbe war wie Feuer.',
'Und ich nahm sie und trank: und als ich trank, fühlte mein Herz Einsicht, und die Weisheit mehrte sich in meiner Brust, denn mein Geist behielt seine Erinnerung.',
'Und mein Mund wurde geöffnet und nicht wieder geschlossen.',
'Der Allerhöchste gab den fünfen Verstand, und sie schrieben hintereinander in Zeichen, die sie nicht kannten, vierzig Tage lang.',
'Sie setzten sich tagsüber, und ich redete über Tag nicht, aber des Nachts redete ich nicht still in mir.',
'In vierzig Tagen wurden zweihundert und vier Bücher geschrieben.',
'Und es begab sich, als die vierzig Tage vollendet waren, daß der Allerhöchste sprach: Die vierundzwanzig Bücher, die du zuerst geschrieben hast, stelle heraus, daß die Würdigen und Unwürdigen sie lesen mögen.',
'Aber die siebzig zuletzt geschriebenen bewahre, damit du sie dem Weisen unter deinem Volk übergeben kannst.',
'Denn in ihnen ist die Ader des Verstandes, die Quelle der Weisheit und der Strom des Wissens.',
'Und so tat ich.',
'Und es begab sich, als die vierzig Tage erfüllt waren, daß der Allerhöchste mit mir redete; und er nahm mich an, und trug mich hin, wo die, die dem Herrn ähnlich sind, von Anfang waren. Diese Dinge wurden mit dem Namen von Esra aufgezeichnet.',
'Er sprach: Jetzt gehst du, o Esra, und machest dir und deinem Volk bekannt, was die Zeit ist, und die Zeichen und die Wunder, und all das, was ihr zu hören begierig waret, in der Zeit, die keine Zeit ist: denn du wirst aufgenommen werden zu mir; und nun erhebe meine Stimme über dein Gesicht und schreibe es auf das Volk, und sage ihnen: Seid gerecht, und brecht eure Freundschaft mit dem Ungöttlichen und befehlt eurem Volk, sich zu schämen über sein Unrecht, und schau auf die, die euch verfolgt haben, damit eure Gebete und eure Seelen erquickt werden, und die anderen euch nicht mehr verfolgen werden.',
'Der Allerhöchste mache dich stark, mein Sohn; und er gebe dir Eifer und Freude und Frieden, damit ihr in seinem Gesetz wandeln möget; und was ihr für andere tut, das wird euch vergolten werden, der euch geholfen hat durch seinen Gesalbten.'
];

const ch15 = [
'Sieh, rede in die Ohren meines Volkes die Worte der Weissagung, die ich in deinen Mund legen werde, spricht der Herr.',
'Und laß sie aufschreiben auf Papier, denn sie sind treu und wahr.',
'Fürchte dich nicht vor ihrer Einbildung; denn der Unglaube der sie nicht kennen, soll nicht aufhalten dich, mehr denn die Ungläubigen.',
'Denn alle Ungläubigen sollen sterben durch ihren Unglauben.',
'Sieh, spricht der Herr: Ich bringe Seuchen auf den Erdkreis, das Schwert und Not, Tod und Verderben.',
'Denn Ungerechtigkeit hat die ganze Erde verunreinigt und ihre verderblichen Werke sind vollkommen.',
'Darum, spricht der Herr:',
'Ich will nicht länger schweigen über ihre Gottlosigkeiten, die sie frevelhaft begehen, noch werde ich dulden, daß sie die, die ich erwählt habe, schaden; denn die Erde soll sie sehen und befragt werden.',
'Darum, mein Schwert soll nicht aufhören über diejenigen, die vergossen unschuldiges Blut auf der Erde.',
'Denn das Feuer ist aufgegangen von seinem Zorn, und wird leuchten bis auf die Fundamente der Erde.',
'Wie ein Pfeil, das von einem starken Bogenschützen geschossen worden ist, wird es nicht zurückkehren.',
'Wehe der Welt! spricht der Herr.',
'Wehe denen, die sündigen und ihre Ungerechtigkeit nicht abwenden!',
'Das Schwert und die Zerstörung, Hunger und Verderben sind als von Gott gesandte Übel zubereitet, um die Gottlosen zu schlagen.',
'Denn die Erde wird kommen und ihre vergossenen Blüten zu fall bringen, und ihr Schwert wird nicht aufhören, Diejenigen zu entzünden, die böse handeln.',
'Der Funke des Feuers wird entfacht sein, denn das Haus des Bösen ist zerstört worden.',
'Und sieh, Träume werden erschrecken, und die Gesichte werden großen Schrecken bereiten.',
'Darum sollst du niemandem deinen Traum erzählen, und von keiner Weissagung soll man jemals wieder hören.',
'Und sieh, der Herr macht sich bereit, euch heimzusuchen.',
'Denn die Äthiopier werden aus Ägypten ausziehen.',
'Und aus Arabien werden Drachen kommen, als mächtige Schlangen kriechend auf der Erde, mit dem Zischen Hauch des Atems sollten sie alle Söhne Arabiens niederstrecken.',
'Und dann werde ich ihnen Kraft geben, daß sie fallen sollen; denn ich werde eifern über sie, sagt der Herr der Heerscharen.',
'Denn mein Zorn wird über sie geraten, bis daß er sie zerstört haben wird.',
'Wehe dir, Asien, die du an der Herrlichkeit Babylons teilnimmst und an dem Ruhm seiner Person!',
'Wehe dir, du Elende, weil du seiner ähnlich bist in deinen Werken!',
'Wehe dir, Babylon und Asien! wehe dir, Ägypten und Syrien!',
'Gürtet euch mit einem Sackkleid und einem Bußgewand und hegt Trauer für eure Kinder, und flattert in eurer Zerstörung.',
'Denn die Zeit des Untergangs ist nahe und das Schwert ist geschliffen.',
'Und als die Völker sich aufmachen gegen die Herrschaft, und die Unterdrückung kommt darüber, dann wird eure Kraft hinschwinden.',
'In der Stadtmitte werden die Feinde Arabiens über euch kommen mit einem langen Gefolge; und was sie hören, werden sie bringen, und eure Größe fällt.',
'Und ihr wollt weinen und klagen über euren Untergang.',
'Denn nun habt ihr eure Schätze gesammelt für ein Ende; es werden alle Städte und ihre Bewohner hören, daß ihr Feinde habt.',
'Denn Hunger und Not und das Schwert und ihr Schrecken sollen aufkommen über sie; und diejenigen, die sich fürchten, sollen betrübt sein.',
'Feuer und Hunger werden sie erschrecken, und sie werden nicht aufhören zu weinen.',
'Und als die Zeit vergeht, werden sie gefragt werden, wer kommt, um sie zu schlagen, und wer wird es sein, der sie gebunden bringt.',
'Wer bringt sie unter Joch? wer macht ihre Versammlung wie das Heu, das im Feuer verbrannt wird?',
'Denn die Männer seiner Stärke sollen nicht schonen das Volk; und sie sollen nicht aufhören Großes zu tun auf Erden.',
'Ja, sie sollen seine Stärke in großem Schrecken kennen, und sollen ihn fürchten; sie werden zittern in der Stunde des Gerichts.',
'Und der Herr sagt: Wehe dem Haus Assur! wo sind deine Propheten und Weisen, über die du geprahlt hast?',
'Ich bin wie ein Sturm zwischen dir, und gewittriger Schauer, und der Donner soll die Ohren erschrecken derer, die von dir nicht Ahnung haben.',
'Ich will euch schlagen und an euch mein Gericht vollziehen, sagt der Herr.',
'Ich bin mächtig wie ein König, und ich lasse mein Gericht kommen auf euch, die ihr eine große Menge zusammengebracht habt.',
'Und so wie das Heu im Feuer verbrannt wird, so soll auch ihre Stadt im Feuer brennen, und ihr Ruhm und ihre Pracht sollen aufhören.',
'Ich will sie niederwerfen und ihr Ruhm wird dahinfahren.',
'Und dann werde ich in diesem Haus eine andere Stadt aufbauen, und sie soll zu mir sagen: Ich bin deine Stadt.',
'Denn das Unrecht ist vollbracht; die Stämme werden fallen, und das Ende wird kommen.',
'Und ich werde mich über sie erheben, spricht der Herr; dann wird der Herr allein in seiner Herrlichkeit dastehen.',
'So werden sie hören, und das Schwert soll sie zerstören; wer diese Worte nicht hört, wird vernichtet werden.',
'Und die, welche nicht gehorchen, werden den Tod nicht vermeiden.',
'Denn alle, die die Gottlosigkeit begehen werden, sollen umkommen.',
'Und dann wird ihr Prahlen verstummen; aber denen, die Gott dienen, wird er geben, was er verheißen hat.',
'Und die Propheten des Herrn werden reden über die letzten Dinge; denn der Herr kennt seinen Ratschluß.',
'Und dann soll der Herr sprechen zu dem Volk, das in Zion ist: Seht, ihr Seligen, und schaut auf die da mit euch sind!',
'Denn sie vertrauen auf dich, der du uns alle gerettet hast.',
'Und der Herr sagte: Schau, ich gebe ihnen ihre Häuser und Habe zurück, und sie sollen ihren Platz einnehmen.'
];

const ch16 = [
'Wehe dir, Babylon und Asien! wehe dir, Ägypten und Syrien!',
'Gürtet euch mit sackleinen Tüchern und Bußgewändern, und beweint eure Kinder, und klaget in eurem Schmerz; denn der Untergang ist nahe.',
'Das Schwert ist dir gesandt. Wer ist, der es abwendet?',
'Das Feuer ist dir gesandt. Wer ist, der es löscht?',
'Unglück ist dir gesandt. Wer ist, der es vertreibt?',
'Kann jemand den hungrigen Löwen im Walde verjagen, oder das Feuer, wenn es das Stroh brennt?',
'Kann jemand den Pfeil zurückhalten, der von einem starken Bogenschützen geschossen ist?',
'Der Herr Gott sendet Unglück, und wer wird es abwenden?',
'Feuer ist von seinem Zorn aufgegangen, und wer wird es löschen?',
'Er leuchtet mit dem Strahlen seines Blitzes, und wer wird ihn nicht sehen?',
'Er donnert mit seiner Stimme, und wer wird nicht zittern?',
'Der Herr droht, und wer wird nicht zerrissen werden von seiner Gegenwart?',
'Die Erde zittert von ihren Grundmauern; das Meer bewegt sich aus seiner Tiefe; seine Wellen und seine Fische werden erschüttert vor dem Herrn und wegen der Herrlichkeit seiner Macht.',
'Denn sein Arm ist stark und er zieht den Bogen; seine Pfeile sind scharf und wenn er sie geschossen hat, werden sie nicht verfehlen die Enden der Welt.',
'Sieh, die Plagen werden gesandt und werden nicht zurückkehren.',
'Das Feuer ist entbrannt und es wird nicht gelöscht, bis es die Fundamente der Erde verbrennt.',
'Wie wenn der Pfeil von einem starken Bogenschützen geschossen wird und nicht zurückkehrt: so werden die Plagen, die für die Erde gesandt werden, nicht zurückkehren.',
'Wehe mir! wehe mir! Wer wird mich retten in jenen Tagen?',
'Der Anfang der Leiden und der große Jammer: der Hunger und viele Nöte; die Krankheiten und die Schwertgefahr; die Unterdrückung der Großen.',
'Wie ein Acker, der auf die Samen gefallen ist und kein Getreide bringt, so ist diese Zeit auch: saat viel und erntet wenig, und ein Mann wird seinen Nächsten betrauern.',
'Und dann soll das Land erschreckt werden; wie der Boden einer Gruft liegt es wüste.',
'Denn ein Mann wird seinen Nachbar nicht kennen, und Vater und Sohn werden nicht voneinander wissen; und der Bruder wird seinen Bruder nicht kennen.',
'Und die Erde verwüstet das Land, und die Erde wird weinend klagen; denn sie weiß, daß das Ende naht.',
'Und je mehr ich mich verberge und mehr vor dem Herrn verstecke, so kann ich nicht verborgen bleiben; denn meine Sünden sind zu einem Zeugnis von seinem Gericht über mich geworden.',
'Und wie das Feld, wenn die Stoppeln verbrannt sind, nicht verborgen sind, sondern man sie sieht: so werden auch meine Sünden im letzten Gericht bekannt sein.',
'Wehe dir, Sünder! Wehe dir, du Gottloser! wehe denen, die Lüge üben und in ihren Herzen Böses tun!',
'Freut euch nicht, ihr Gottlosen, und prahlt nicht damit in eurer Ungerechtigkeit!',
'Ihr habt keine Ausrede; denn es ist euch Zeit gelassen worden zur Buße!',
'Haben wir Gott nicht gekannt? ist sein Angesicht zu Schanden geworden? er, der aller Herzen Gedanken kennt?',
'Denkt ihr, daß er eure Sünden nicht kennt? er kennt sie alle!',
'Wehe denen, die Sünden begehen und sich selbst mit Sünde decken!',
'Denn er wird kommen und alles heimsuchen: wenn er erscheint, wird er alles Verborgene aufdecken.',
'Denn der Herr ist ein gerechter Richter, der kein Ansehen der Person kennt; er nimmt kein Geld und keine Gegengabe an.',
'Er richtet über alle gleich, arm und reich.',
'Er wird nicht von dem Weg abweichen und kein Unrecht tun und kein Ansehen der Person kennen; denn er hat alle Menschenkinder erschaffen und er kennt alle Dinge auf der Erde.',
'Ihr habt Gott nicht erkannt und darum habt ihr seine Gebote übertreten.',
'Erkennt ihn nun und lebt anders; tuet Buße und kehret um zu Gott und er wird euch gnädig sein.',
'Aber wehe euch, wenn ihr nicht umkehrt!',
'Wehe denen, die in ihrer Bosheit verharren; sie werden nicht treu gerettet werden.',
'Wehe dem, der die Wahrheit nicht weiß, aber wohl das Böse kennt.',
'Wehe dem, der keine Scheu vor Gott hat.',
'Wehe dem, der die Gebote Gottes verachtet.',
'Wehe dem, der sagt: Ich werde nun Böses tun; wenn ich es bereue, bin ich vergeben.',
'Weh dem, der nicht an Gott glaubt, was sein letztes Ende ist.',
'Denn diese Dinge werden euch gesandt werden von dem, der sie erschaffen hat und sie hält in seinem Sinn.',
'Darum werft nicht eure Sünden auf Gott, sondern tragt sie selbst.',
'Ihr habt Sünde getan und müsset dafür Rechenschaft ablegen.',
'Seid nicht erschrocken oder gezwungen; aber seid getrost und fürchtet euch nicht, ihr meine Auserwählten! spricht der Herr.',
'Denn ihr Gott ist euer Herr; er wird nach euch Ausschau halten und euch aus allen Nöten erretten.',
'Wehe denen, die den Auserwählten Böses antun, dem Herrn zuliebe!',
'Wehe denen, die sie hassen und verachten, die ihre Werke verachten!',
'Wehe denen, die meine Auserwählten aus ihrer Wohnung verdrängen!',
'Denn der Herr, ihr Gott, wird sich rächen und euch heimsuchen, er, der seine Auserwählten über alles liebt.',
'Seid stark und bereit, ihr Auserwählten! und fürchtet euch nicht!',
'Denn eure Belohnung wird nicht verloren gehen; sie ist bei dem Herrn, der die letzten Dinge weiß.',
'Und wenn ihr leidet, so wird euch geholfen werden durch das, was der Herr zubereitet hat.',
'Gehet darum in der Zeit nicht irre, und habet Geduld; denn die Zeit kommt und der Herr wird euch nicht vergessen.',
'Seid stark, ihr Auserwählten! und fürchtet euch nicht vor dem Ende, das euch erschrecken will!',
'Denn der Herr ist bei euch; er ist euer Schutzhort und Zuflucht und er ist der, der für euch kämpft in allen Nöten.',
'Denn das Ende aller dieser Dinge ist nahe und wird nicht lange warten.',
'Vergeßt nicht, daß der Herr euch erwählt hat; er wird kommen und seine Auserwählten erretten in dem großen Gericht.',
'Darum steht fest in dem, was ihr geglaubt habt! und fürchtet euch nicht!',
'Damit eure Seelen nicht abgelenkt werden von dem Herrn, der allein gerecht ist.',
'Denn dieser ist der Herr, euer Gott; er wird für euch kämpfen und niemand wird ihm widerstreben können.'
];

const out = JSON.parse(fs.readFileSync(__dirname+'/tmp_b75_c.json','utf8'));
[ch13, ch14, ch15, ch16].forEach((verses, i) => {
  const cn = i+13;
  const vv = {};
  verses.forEach((t,j)=>{ vv[j+1]={verse:j+1,text:t}; });
  out.chapters[cn] = {chapter:cn, name:'', verses:vv};
});

fs.writeFileSync(__dirname+'/tmp_b75_d.json', JSON.stringify(out), 'utf8');
const total = [ch13,ch14,ch15,ch16].reduce((s,c)=>s+c.length,0);
console.log('Batch D fertig: Kapitel 13-16, '+total+' Verse');
