// Batch A: Buch 75 (4. Esra) Kapitel 1–4
const fs = require('fs');

const ch1 = [
'Dies ist das zweite Buch des Propheten Esra, des Sohnes Saraja, des Sohnes Asaria, des Sohnes Helkia, des Sohnes Sadamia, des Sohnes Sadok, des Sohnes Achitob,',
'des Sohnes Achias, des Sohnes Phinees, des Sohnes Heli, des Sohnes Amaria, des Sohnes Asiel, des Sohnes Marimoth, des Sohnes Borith, des Sohnes Abisei, des Sohnes Phinees, des Sohnes Eleazar,',
'des Sohnes Aaron, vom Stamme Levi; der war in der Gefangenschaft im Lande der Meder, zur Zeit der Regierung des Königs Artaxerxes über die Perser.',
'Und das Wort des Herrn kam zu mir und sprach:',
'Geh hin und zeige meinem Volk seine sündigen Werke und seinen Kindern die Bosheit, die sie gegen mich begangen haben, damit sie es ihren Kindeskindern erzählen können:',
'denn die Sünden ihrer Väter haben sich in ihnen vermehrt; denn sie haben mich vergessen und fremden Göttern geopfert.',
'Bin ich nicht eben der, der sie aus dem Lande Ägypten, aus dem Haus der Knechtschaft, herausgeführt hat? Aber sie haben mich zum Zorn gereizt und meinen Rat verachtet.',
'So raufe dir nun die Haare aus dem Kopf und wirf alles Böse auf sie; denn sie haben meinem Gesetz nicht gehorcht, sondern sind ein widerspenstiges Volk.',
'Wie lange soll ich ihrer schonen, die ich so Großes getan habe?',
'Viele Könige habe ich um ihretwillen vernichtet; den Pharao mit seinen Dienern und seinem ganzen Heer habe ich niedergeschlagen.',
'Alle Völker habe ich vor ihnen vertilgt, und im Osten habe ich das Volk zweier Provinzen zerstreut, nämlich Tyrus und Sidon, und alle ihre Feinde erschlagen.',
'Darum sage zu ihnen: So spricht der Herr:',
'Ich habe euch durch das Meer geführt und euch im Anfang einen weiten und sicheren Weg bereitet; ich gab euch Mose zum Führer und Aaron zum Priester.',
'Ich gab euch Licht in einer Feuersäule und große Wunder habe ich unter euch getan; aber ihr habt mich vergessen, spricht der Herr.',
'So spricht der allmächtige Herr: Die Wachteln waren ein Zeichen für euch; ich gab euch Zelte zu eurem Schutz; aber ihr murtet dort,',
'und frohlockt nicht in meinem Namen wegen der Vernichtung eurer Feinde, sondern murrt bis auf diesen Tag immer noch.',
'Wo sind die Wohltaten, die ich euch erwiesen habe? Als ihr in der Wüste hungrig und durstig wart, rieft ihr nicht zu mir',
'und spracht: Warum hast du uns in diese Wüste geführt, um uns zu töten? Es wäre besser gewesen, daß wir den Ägyptern gedient hätten, als daß wir in dieser Wüste stürben.',
'Da erbarmte ich mich über eure Klagen und gab euch Manna zu essen; so habt ihr Engelsbrot gegessen.',
'Als ihr Durst hattet, habe ich nicht den Felsen gespalten und Wasser floß heraus zu eurer Sättigung? Und vor der Hitze bedeckte ich euch mit den Blättern der Bäume.',
'Ich teilte unter euch ein fruchtbares Land aus; ich vertrieb vor euch die Kanaaniter, die Pheresiter und die Philister. Was soll ich noch mehr für euch tun? spricht der Herr.',
'So spricht der allmächtige Herr: Als ihr in der Wüste waret, am Fluß der Amoriter, und Durst hattet, und meinen Namen lästertet,',
'gab ich euch kein Feuer wegen eurer Lästerungen, sondern warf einen Baum in das Wasser und machte den Fluß süß.',
'Was soll ich mit dir tun, o Jakob? Du, Juda, hast mir nicht gehorcht: darum wende ich mich zu anderen Völkern und will ihnen meinen Namen geben, damit sie meine Satzungen halten.',
'Weil ihr mich verlassen habt, will ich euch auch verlassen; wenn ihr mich um Gnade anfleht, werde ich euch nicht barmherzig sein.',
'Wann immer ihr mich anrufet, werde ich euch nicht erhören; denn ihr habt eure Hände mit Blut befleckt, und eure Füße sind schnell, Blut zu vergießen.',
'Nicht als ob ihr mich verlassen hättet, sondern ihr habt euch selbst verlassen, spricht der Herr.',
'So spricht der allmächtige Herr: Habe ich euch nicht gebeten wie ein Vater seine Söhne, wie eine Mutter ihre Töchter und wie eine Amme ihre Kinder,',
'daß ihr mein Volk sein und ich euer Gott sein sollte; daß ihr meine Kinder sein und ich euer Vater sein sollte?',
'Ich habe euch versammelt, wie eine Henne ihre Küchlein unter ihre Flügel sammelt; aber nun, was soll ich mit euch tun? Ich will euch von meinem Angesicht verstoßen.',
'Wenn ihr mir opfert, werde ich mein Angesicht von euch abwenden; denn eure Feste, eure Neumonde und eure Beschneidungen habe ich verworfen.',
'Ich sandte euch meine Knechte, die Propheten, welche ihr ergriffen, getötet und deren Leiber ihr zerrissen habt; deren Blut will ich von euren Händen fordern, spricht der Herr.',
'So spricht der allmächtige Herr: Euer Haus ist wüste; ich will euch von mir stoßen wie der Wind das Stroh.',
'Und eure Kinder werden nicht fruchtbar sein; denn sie haben mein Gebot verachtet und getan, was vor mir böse ist.',
'Ich will euer Haus einem Volk geben, das kommen wird; das hat mich nie gehört, wird mir aber glauben; denen ich keine Zeichen gezeigt habe, werden doch tun, was ich ihnen befehle.',
'Sie haben keine Propheten gesehen, und werden doch ihre Sünden eingedenk sein und sie bekennen.',
'Ich nehme die Gnade des Volkes, das kommen soll, zum Zeugen, dessen Kinder sich mit Freuden erfreuen; und obwohl sie mich nicht mit leiblichen Augen gesehen haben, glauben sie doch dem, was ich sage.',
'Und nun, Bruder, sieh die Herrlichkeit; und schau auf das Volk, das vom Osten kommt:',
'diesen will ich zu Führern geben: Abraham, Isaak und Jakob, Hosea, Amos und Micha, Joel, Obadja und Jona,',
'Nahum und Habakuk, Zephanja, Haggai, Sacharja und Maleachi, der auch ein Engel des Herrn genannt wird.'
];

const ch2 = [
'So spricht der Herr: Ich habe dieses Volk aus der Knechtschaft geführt und ihnen meine Gebote durch meine Knechte, die Propheten, gegeben; doch wollten sie nicht hören, sondern verachteten meinen Rat.',
'Die Mutter, die sie geboren hat, sagt zu ihnen: Gehet euren Weg, ihr Kinder; denn ich bin eine Witwe und verlassen.',
'Ich habe euch mit Freude aufgezogen; aber mit Trauer und Betrübnis habe ich euch verloren; denn ihr habt vor dem Herrn, eurem Gott, gesündigt und getan, was vor ihm böse ist.',
'Aber was soll ich nun mit euch tun? Ich bin eine Witwe und verlassen; gehet euren Weg, ihr Kinder, und bittet den Herrn um Gnade.',
'Dich, Vater, rufe ich zum Zeugen über die Mutter dieser Kinder an, welche meinen Bund nicht halten wollten,',
'daß du sie zur Verwirrung bringest und ihre Mutter zur Beute, daß kein Nachkomme von ihnen übrig bleibe.',
'Laßt sie unter den Heiden zerstreut werden; ihr Name werde aus der Erde vertilgt, denn sie haben meinen Bund verachtet.',
'Wehe dir, Assur, der du die Ungerechten bei dir birgest! O du böses Volk, gedenke, was ich Sodom und Gomorra getan habe;',
'deren Land in Pechklumpen und Aschenhaufen liegt; ebenso will ich auch mit denen verfahren, die mir nicht gehorchen, spricht der allmächtige Herr.',
'So spricht der Herr zu Esra: Sage meinem Volk, daß ich ihnen das Königreich Jerusalem geben werde, das ich Israel geben wollte.',
'Auch will ich ihre Herrlichkeit an mich nehmen und ihnen die ewigen Wohnungen geben, die ich für sie bereitet hatte.',
'Sie sollen den Baum des Lebens als wohlriechendes Salböl haben; sie sollen weder müde noch matt werden.',
'Gehet hin und empfangt; betet um wenige Tage für euch, daß sie verkürzt werden: das Königreich ist schon für euch bereitet; wachet.',
'Nehmet den Himmel und die Erde zum Zeugen; denn ich habe das Böse in Stücke zerbrochen und das Gute erschaffen; denn ich lebe, spricht der Herr.',
'Mutter, umarme deine Kinder und ziehe sie auf mit Freude; stärke ihre Füße wie Pfeiler; denn ich habe dich erwählt, spricht der Herr.',
'Und die Toten will ich von ihren Plätzen wieder auferwecken und aus den Gräbern herausbringen; denn ich habe meinen Namen in Israel erkannt.',
'Fürchte dich nicht, du Mutter der Kinder; denn ich habe dich erwählt, spricht der Herr.',
'Zu deiner Hilfe werde ich meine Knechte Esau und Jeremia senden, nach deren Rat ich dir zwölf fruchtbeladene Bäume geheiligt und bereitet habe,',
'und ebenso viele Quellen, fließend mit Milch und Honig, und sieben gewaltige Berge, auf denen Rosen und Lilien wachsen; womit ich deine Kinder mit Freude erfüllen will.',
'Tue der Witwe Recht, richte für den Vaterlosen, gib dem Armen, schütze den Waisen, bekleide den Nackten,',
'heile den Gebrochenen und den Schwachen, lache den Lahmen nicht aus, verteidige den Verstümmelten und laß den Blinden in das Licht meiner Klarheit eintreten.',
'Bewahre den Alten und den Jungen innerhalb deiner Mauern.',
'Wo immer du Tote findest, nimm sie und begrabe sie, und ich werde dir den ersten Platz in meiner Auferstehung geben.',
'Bleib stille, mein Volk, und ruhe aus; denn deine Ruhe wird kommen.',
'Nähre deine Kinder, du gute Amme; stärke ihre Füße.',
'Was die Knechte betrifft, die ich dir gegeben habe, so soll nicht einer von ihnen umkommen; denn ich werde sie aus deiner Zahl fordern.',
'Werde nicht müde; denn wenn der Tag der Trübsal und Bedrängnis kommt, werden andere weinen und traurig sein, aber du sollst fröhlich sein und Überfluß haben.',
'Die Heiden werden dich beneiden, aber sie werden nichts gegen dich vermögen, spricht der Herr.',
'Meine Hände werden dich bedecken, damit deine Kinder die Hölle nicht sehen.',
'Sei fröhlich, o Mutter, mit deinen Kindern; denn ich werde euch erretten, spricht der Herr.',
'Gedenke deiner Kinder, die schlafen; denn ich werde sie aus den Enden der Erde herausbringen und Erbarmen an ihnen erweisen; denn ich bin barmherzig, spricht der Herr der Heerscharen.',
'Umarme deine Kinder, bis ich komme und ihnen Erbarmen erweise; denn meine Brunnen laufen über und meine Gnade wird nicht ausbleiben.',
'Ich, Esra, empfing einen Befehl vom Herrn auf dem Berge Horeb, nach Israel zu gehen; aber als ich zu ihnen kam, verachteten sie mich und verächteten das Gebot des Herrn.',
'Und darum sage ich euch, ihr Heiden, die ihr höret und verstehet: Wartet auf euren Hirten, er wird euch ewige Ruhe geben; denn er ist nahe, der am Ende der Welt kommen wird.',
'Macht euch bereit zur Belohnung des Königreiches; denn das ewige Licht wird euch in Ewigkeit leuchten.',
'Fliehet den Schatten dieser Welt, empfanget die Freude eurer Herrlichkeit: ich bezeuge meinen Heiland öffentlich.',
'O empfanget das Geschenk, das euch gegeben ist, und seid fröhlich; dank sagt dem, der euch ins himmlische Königreich geführt hat.',
'Stehet auf und tretet hervor; sehet die Zahl derer, die versiegelt sind am Fest des Herrn:',
'die aus dem Schatten dieser Welt geschieden sind und herrliche Kleider vom Herrn empfangen haben.',
'Nimm deine Zahl, o Zion, und schließ jene deiner ein, die in Weiß gekleidet sind und das Gesetz des Herrn erfüllt haben.',
'Die Zahl deiner Kinder, nach denen du dich sehnst, ist voll; bitte die Macht des Herrn, daß dein Volk, das von Anfang an berufen ward, geheiligt werde.',
'Ich, Esra, sah auf dem Berge Zion eine große Menge, die ich nicht zählen konnte, und sie alle priesen den Herrn mit Liedern.',
'Und in ihrer Mitte war ein junger Mann von hohem Wuchs, größer als alle anderen; und auf jeden ihrer Köpfe setzte er Kronen und war noch höher erhoben; was mich sehr verwunderte.',
'Da fragte ich den Engel und sprach: Herr, wer sind diese?',
'Er antwortete und sagte zu mir: Diese sind es, die das sterbliche Kleid abgelegt und das unsterbliche angezogen haben, und haben den Namen Gottes bekannt: nun werden sie gekrönt und empfangen Palmen.',
'Da sprach ich zum Engel: Wer ist der junge Mann, der sie krönt und ihnen Palmen in die Hände gibt?',
'So antwortete er und sprach zu mir: Es ist der Sohn Gottes, den sie in der Welt bekannt haben. Da begann ich sehr die zu rühmen, die so standhaft für den Namen des Herrn standen.',
'Da sprach der Engel zu mir: Geh hin und sage meinem Volk, was für Dinge und wie große Wunder des Herrn, deines Gottes, du gesehen hast.'
];

const ch3 = [
'Im dreißigsten Jahr nach der Zerstörung der Stadt lag ich in Babel und war beunruhigt auf meinem Bett, und meine Gedanken stiegen mir ins Herz:',
'denn ich sah die Verwüstung Zions und den Reichtum derer, die in Babel wohnten.',
'Und mein Geist war sehr bewegt, so daß ich begann, Worte voll Furcht zum Allerhöchsten zu reden, und sprach:',
'O Herr, der du herrschest, du hast geredet im Anfang, als du die Erde schufst, und das du allein und befaßlest dem Volk,',
'und gabst dem Adam einen Leib ohne Seele, der das Werk deiner Hände war, und hauchtest ihm den Lebensatem ein, und er wurde lebendig vor dir.',
'Und du führtest ihn in das Paradies, das deine Rechte gepflanzt hatte, bevor die Erde fertig war.',
'Und du gabst ihm das Gebot, deinen Weg zu lieben: aber er übertrat es, und alsbald verhängtest du den Tod über ihn und seine Nachkommen, aus denen Völker, Stämme, Nationen und Geschlechter entstanden, ohne Zahl.',
'Und ein jedes Volk wandelte nach seinem eigenen Willen, und tat wunderliche Dinge vor dir, und verachtet deine Gebote.',
'Und wiederum brachtest du nach einiger Zeit die Sintflut über die, die in der Welt wohnten, und vertilgtest sie.',
'Und es geschah bei einem jeden von ihnen: wie der Tod dem Adam, so war die Sintflut diesen.',
'Gleichwohl ließ du einem von ihnen übrig, nämlich Noach mit seinem Hause, aus dem alle gerechten Menschen kamen.',
'Und es begab sich, als die auf der Erde zu wohnen begannen, sich mehrten und viele Kinder bekamen und ein großes Volk wurden, begannen sie abermals gottloser als die ersten zu sein.',
'Da nun diese so gottlos vor dir lebten, erwähletest du dir einen Mann aus ihnen, der Abraham hieß.',
'Den liebtest du, und ihm allein offenbartest du deinen Willen:',
'und machtest mit ihm einen ewigen Bund, indem du versprachst, daß du seinen Samen niemals verlassen würdest.',
'Und du gabst ihm Isaak, und dem Isaak wiederum Jakob und Esau. Den Jakob erwähletest du dir, Esau aber ließ du beiseite; und so wurde Jakob ein großes Volk.',
'Und es geschah, als du seinen Samen aus Ägypten führtest, brachtest du ihn an den Berg Sinai.',
'Du beugtest den Himmel und befestigtest die Erde, bewegtest die ganze Welt und ließest die Tiefen erbeben und erschrecktest die Menschen jenes Zeitalters.',
'Und deine Herrlichkeit ging durch vier Pforten, durch Feuer und Erdbeben, Wind und Kälte, damit du dem Samen Jakobs das Gesetz geben konntest und dem Geschlecht Israels den Eifer.',
'Gleichwohl nahmst du ihnen das böse Herz nicht, damit dein Gesetz in ihnen Frucht brächte.',
'Denn der erste Adam trug ein böses Herz und übertrat, und wurde überwunden; und ebenso alle, die von ihm geboren sind.',
'So wurde die Schwachheit dauerhaft; und das Gesetz war im Herzen des Volkes, neben der Schlechtigkeit der Wurzel; so daß das Gute wich und das Böse blieb.',
'So vergingen die Zeiten und die Jahre wurden vollendet; da erwecktest du dir einen Knecht, der David hieß:',
'dem du befahlst, dir eine Stadt zu bauen und in ihr Räucherwerk und Opfer darzubringen.',
'Als dies viele Jahre getan war, verließen die Einwohner der Stadt dich,',
'und in allem taten sie wie Adam und alle seine Geschlechter; denn sie hatten auch ein böses Herz:',
'und so gabst du deine Stadt in die Hände deiner Feinde.',
'Sind nun die, die in Babel wohnen, besser in ihren Werken, daß sie darum Gewalt über Zion haben sollen?',
'Denn als ich dorthin kam und die Gottlosigkeiten ohne Zahl sah, da sah meine Seele viele Übeltäter in diesem dreißigsten Jahr, so daß mein Herz mir versagte.',
'Denn ich habe gesehen, wie du sie sündigen läßt und duldest die Gottlosen; wie du dein Volk vernichtet und deine Feinde verschont und nicht ein Zeichen davon gegeben hast.',
'Ich bedenke nicht, wie dieser Weg verlassen werden kann: Sind denn die von Babel besser als die von Zion?',
'Oder ist ein anderes Volk, das dich kennt außer Israel? oder welches Geschlecht hat deinen Bündnissen so geglaubt wie Jakob?',
'Und doch erscheint ihre Belohnung nicht, und ihre Mühe hat keine Frucht; denn ich bin hier und dort unter den Heiden gewesen und habe gesehen, daß sie in Reichtum schwelgen und nicht an deine Gebote gedenken.',
'Wäge nun unsere Gottlosigkeit auf der Waage und auch die derer, die auf der Welt wohnen; so wird dein Name nirgendwo gefunden werden als in Israel.',
'Oder wann haben die, die auf Erden wohnen, nicht vor deinen Augen gesündigt? oder welches Volk hat deine Gebote so gehalten?',
'Du wirst finden, daß Israel deinem Gebot namentlich gehorcht hat; nicht aber die Heiden.'
];

const ch4 = [
'Und der Engel, der zu mir gesandt war, dessen Name Uriel war, gab mir Antwort',
'und sagte: Dein Herz ist zu weit gegangen in dieser Welt, und meinst du die Wege des Allerhöchsten begreifen zu können?',
'Da sprach ich: Ja, mein Herr. Und er antwortete mir und sprach: Ich bin gesandt, um dir drei Wege zu zeigen und dir drei Gleichnisse vorzulegen:',
'und kannst du mir eines davon erklären, so will ich dir auch den Weg zeigen, den du zu sehen begehrst, und dir zeigen, woher das böse Herz kommt.',
'Und ich sprach: Rede, mein Herr. Da sprach er zu mir: Geh hin, wäge mir das Gewicht des Feuers, oder miß mir den Hauch des Windes, oder ruf mir den Tag zurück, der vergangen ist.',
'Da antwortete ich und sprach: Welcher Mensch kann das tun, daß du solche Dinge von mir forderst?',
'Er aber sprach zu mir: Wenn ich dich fragte, wieviele Wohnstätten im Mittelpunkt des Meeres sind, oder wieviele Quellen am Anfang der Tiefe sind, oder wieviele Quellen über dem Firmament sind, oder welches die Ausgänge des Paradieses sind:',
'vielleicht würdest du zu mir sagen: Ich bin nie in die Tiefe hinabgestiegen, noch in die Hölle, noch bin ich je in den Himmel hinaufgestiegen.',
'Gleichwohl habe ich dich nur nach Feuer und Wind und dem Tag gefragt, durch den du gegangen bist, und von Dingen, von denen du dich nicht scheiden kannst, und doch kannst du mir keine Antwort darauf geben.',
'Er sprach weiter zu mir: Deine eigenen Dinge, die mit dir aufgewachsen sind, kannst du nicht erkennen;',
'wie sollte denn dein Gefäß vermögen, den Weg des Allerhöchsten zu fassen, und, da die Welt schon äußerlich verdorben ist, die Verderbnis zu verstehen, die offenkundig vor meinen Augen ist?',
'Da sprach ich zu ihm: Es wäre besser, daß wir gar nicht wären, als daß wir weiter in Bosheit leben und leiden und nicht wissen warum.',
'Er antwortete mir und sprach: Ich ging in einen Wald auf ein Feld, und die Bäume hielten Rat',
'und sprachen: Kommt, laßt uns hingehen und Krieg gegen das Meer führen, daß es vor uns zurückweiche und wir uns mehr Wälder machen können.',
'Die Fluten des Meeres hielten ebenfalls Rat und sprachen: Kommt, laßt uns hinaufgehen und die Wälder der Ebene unterjochen, damit wir dort auch ein anderes Land gewinnen.',
'Der Plan des Waldes war eitel; denn das Feuer kam und verbrannte ihn.',
'Der Plan der Fluten des Meeres kam ebenfalls zu nichte; denn der Sand stellte sich auf und hemmte sie.',
'Wenn du nun zwischen diesen beiden Richter wärst, wen würdest du zuerst rechtfertigen? oder wen würdest du verdammen?',
'Ich antwortete und sprach: Fürwahr, es ist ein törichter Gedanke, den sie beide entworfen haben; denn der Grund ist dem Wald gegeben, und das Meer hat auch seinen Platz, seine Fluten zu tragen.',
'Da antwortete er mir und sprach: Du hast recht geurteilt; aber warum richtest du dich nicht auch selbst?',
'Denn wie der Grund dem Wald gegeben ist und das Meer seinen Fluten: so können die, die auf Erden wohnen, nur verstehen, was auf Erden ist; und der, der über den Himmeln wohnt, kann nur die Dinge verstehen, die über der Höhe der Himmel sind.',
'Da antwortete ich und sprach: Ich bitte dich, Herr, laß mich Verstand haben:',
'denn es war nicht meine Absicht, neugierig auf die hohen Dinge zu sein, sondern auf solche, die täglich an uns vorübergehen: warum nämlich Israel den Heiden zur Schmach preisgegeben ist, warum das Volk, das du geliebt hast, gottlosen Nationen übergeben ward, warum das Gesetz unserer Väter zunichte gemacht und die geschriebenen Bündnisse außer Kraft gesetzt sind,',
'und wir wie Heuschrecken aus der Welt scheiden und unser Leben Schrecken und Furcht ist, und wir nicht würdig sind, Erbarmen zu erlangen.',
'Was wird er dann mit seinem Namen tun, nach dem wir genannt sind? Von diesen Dingen habe ich gefragt.',
'Da antwortete er mir und sprach: Je mehr du nachforschst, desto mehr wirst du staunen; denn die Welt eilt schnell dahin,',
'und vermag nicht, die Dinge zu fassen, die den Gerechten in der zukünftigen Zeit verheißen sind; denn diese Welt ist voll von Ungerechtigkeit und Schwachheiten.',
'Was aber die Dinge betrifft, nach denen du mich fragst, so werde ich dir sagen; denn das Böse ist gesät, aber seine Vernichtung ist noch nicht gekommen.',
'Wenn darum das Gesäte nicht umgekehrt wird, und wenn der Ort, an dem das Böse gesät ist, nicht vergeht, dann kann das, was mit Gutem gesät ist, nicht kommen.',
'Denn das Korn des bösen Samens wurde im Herzen Adams von Anfang gesät, und wieviel Gottlosigkeit hat es bis jetzt hervorgebracht? und wieviel soll es noch hervorbringen, bis die Zeit der Dreschwanne kommt?',
'Bedenke nun bei dir selbst, welch große Frucht von Bosheit das Korn des bösen Samens hervorgebracht hat.',
'Und wenn die Ähren, die ohne Zahl sind, abgehauen werden, wie großen Boden werden sie dann füllen?',
'Da antwortete ich und sprach: Wie und wann sollen diese Dinge geschehen? warum sind unsere Jahre so wenige und böse?',
'Er antwortete mir und sprach: Eile nicht über den Allerhöchsten; denn deine Eile ist vergeblich, ihn zu überholen; denn du hast zu weit ausgegriffen.',
'Haben nicht die Seelen der Gerechten auch in ihren Kammern nach diesen Dingen gefragt: Wie lange soll ich so harren? Wann kommt die Frucht der Tenne unserer Belohnung?',
'Und diesen Dingen antwortete Uriel, der Erzengel, und sprach: Wenn die Zahl der Samen unter euch voll ist; denn er hat die Welt in der Waage gewogen.',
'Er hat die Zeiten nach dem Maß gemessen und die Zeiten nach der Zahl gezählt; und er rührt und bewegt sie nicht, bis das genannte Maß voll ist.',
'Da antwortete ich und sprach: O Herr, der du herrschest, wir alle sind voll von Ungerechtigkeit.',
'Und um unsertwillen vielleicht werden die Tennen der Gerechten nicht gefüllt, weil die Sünden derer, die auf Erden wohnen, sie aufhalten.',
'So antwortete er mir und sprach: Geh hin zu einer schwangeren Frau und frage sie, wenn sie ihre neun Monate erfüllt hat, ob ihr Leib das Kind noch länger in sich halten kann.',
'Da sprach ich: Nein, Herr, das kann sie nicht. Und er sprach zu mir: In der Unterwelt sind die Kammern der Seelen wie der Leib einer Frau:',
'denn wie eine Frau, die in Wehen liegt, sich beeilt, der Not der Wehen zu entfliehen: so beeilen sich auch diese Orte, das abzuliefern, was ihnen anvertraut ist.',
'Von Anfang an, schau: was du zu sehen begehrst, soll dir gezeigt werden.',
'Da antwortete ich und sprach: Wenn ich Gnade vor deinen Augen gefunden habe, und wenn es möglich ist, und wenn ich dafür geeignet bin:',
'zeige mir denn, ob mehr kommen wird als vergangen ist, oder ob das Vergangene mehr ist als das Zukünftige.',
'Was vergangen ist, weiß ich; was aber kommen soll, weiß ich nicht.',
'Da sprach er zu mir: Tritt auf die rechte Seite, und ich werde dir das Gleichnis erklären.',
'So trat ich vor und sah: und sieh, ein heißer brennender Ofen ging vor mir vorüber; und es begab sich, als die Flamme vorübergegangen war, daß ich noch den Rauch aufsteigen sah.',
'Danach ging vor mir eine wasserreiche Wolke vorüber und ließ viel Regen mit Sturm herunterfallen; und als der Sturmregen vorüber war, blieben die Tropfen noch.',
'Da sprach er zu mir: Bedenke bei dir selbst: wie der Regen mehr ist als die Tropfen und das Feuer mehr als der Rauch; aber die Tropfen und der Rauch bleiben zurück: so hat die Menge des Vergangenen das Zukünftige übertroffen.',
'Da bat ich und sprach: Meinst du, daß ich leben werde bis zu jener Zeit? oder was soll in jenen Tagen geschehen?',
'Er antwortete mir und sprach: Was die Zeichen betrifft, nach denen du mich fragst, so kann ich dir einen Teil davon sagen; was aber dein Leben betrifft, bin ich nicht gesandt, dir das zu sagen; denn ich weiß es nicht.'
];

const out = {chapters:{}};
[ch1, ch2, ch3, ch4].forEach((verses, i) => {
  const cn = i+1;
  const vv = {};
  verses.forEach((t,j)=>{ vv[j+1]={verse:j+1,text:t}; });
  out.chapters[cn] = {chapter:cn, name:'', verses:vv};
});

fs.writeFileSync(__dirname+'/tmp_b75_a.json', JSON.stringify(out), 'utf8');
const total = [ch1,ch2,ch3,ch4].reduce((s,c)=>s+c.length,0);
console.log('Batch A fertig: Kapitel 1-4, '+total+' Verse');
