'use strict';
/**
 * build-sw.js
 * Scans dist-alquran and dist-diebibel, then generates a sw.js for each
 * with the complete list of files to precache at install time.
 */
const fs   = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const VERSION = new Date().toISOString().slice(0, 10).replace(/-/g, '');

// Extensions to include in precache
const INCLUDE_EXT = new Set(['.html', '.js', '.json', '.png', '.jpg', '.jpeg', '.ico', '.webp', '.svg', '.woff2']);

function scanDir(distPath) {
  const urls = [];
  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else {
        const ext = path.extname(entry.name).toLowerCase();
        if (INCLUDE_EXT.has(ext)) {
          // Convert to URL path relative to dist root
          const rel = '/' + path.relative(distPath, full).replace(/\\/g, '/');
          // Skip the sw.js itself to avoid circular caching
          if (rel === '/sw.js') continue;
          urls.push(rel);
        }
      }
    }
  }
  walk(distPath);
  return urls.sort();
}

function generateSW(cacheName, urls) {
  const urlsJson = JSON.stringify(urls, null, 2);
  return `/* sw.js — generated by build-sw.js on ${VERSION} */
/* Cache: ${cacheName} | ${urls.length} files */
'use strict';

const CACHE = '${cacheName}';

const PRECACHE = ${urlsJson};

/* ── Install: precache ALL files ─────────────────────────────── */
self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c =>
      // Use individual add() calls so one failure doesn't abort the whole install
      Promise.all(PRECACHE.map(url => c.add(url).catch(() => {})))
    ).then(() => self.skipWaiting())
  );
});

/* ── Activate: remove old caches ─────────────────────────────── */
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE).map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

/* ── Fetch: cache-first for same-origin GET ───────────────────── */
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== location.origin) return; // skip cross-origin (Google Fonts etc.)

  e.respondWith(
    caches.match(req).then(cached => {
      if (cached) return cached;

      return fetch(req).then(res => {
        if (!res || res.status !== 200 || res.type !== 'basic') return res;
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(req, clone));
        return res;
      }).catch(() => {
        if (req.mode === 'navigate') {
          return caches.match('/cover.html');
        }
        return new Response('', { status: 503, statusText: 'Offline' });
      });
    })
  );
});
`;
}

const apps = [
  { dist: path.join(ROOT, 'dist-alquran'),  name: 'alquran'  },
  { dist: path.join(ROOT, 'dist-diebibel'), name: 'diebibel' },
];

for (const app of apps) {
  console.log(`\nScanning ${path.basename(app.dist)}...`);
  const urls = scanDir(app.dist);
  console.log(`  → ${urls.length} Dateien gefunden`);

  const cacheName = `${app.name}-v${VERSION}`;
  const swContent = generateSW(cacheName, urls);
  const swPath = path.join(app.dist, 'sw.js');

  fs.writeFileSync(swPath, swContent, 'utf8');
  console.log(`  ✓ ${swPath} geschrieben (Cache: ${cacheName})`);
}

console.log('\n✅ build-sw.js: beide Service Worker generiert.');
